duckduckgo/apple-browsers

iOS/DuckDuckGo/Base.lproj/TabSwitcher.storyboard, iOS/DuckDuckGo/TabSwitcherViewController+MultiSelect.swift, iOS/DuckDuckGo/TabSwitcherViewController.swift, iOS/DuckDuckGo/TabViewCell.swift, iOS/DuckDuckGo/UserText.swift, iOS/DuckDuckGo/en.lproj/Localizable.strings, iOS/DuckDuckGo/en.lproj/Localizable.stringsdict
Task/Issue URL: https://app.asana.com/0/1209332416733187/1209387726611067
CC:
**Description**:
Address some feedback with the multi-select tabs work on iOS.
**Steps to test this PR**:
Check following fixes have been applied to the tab switcher in selection mode:
1. [Fix tab count on button after long press selection change ](https://app.asana.com/0/1209332416733187/1209379111139815)
2. [Fix title to show number of selected items](https://app.asana.com/0/1209332416733187/1209387069429640)
3. [Fix long press menu title and items](https://app.asana.com/0/1209332416733187/1209387069429644)
4. [Fix corners of items showing on long press](https://app.asana.com/0/1209332416733187/1209387069429641)
5. [Fix tab switcher title when moving back to non-select …
=> tab switcher updates (iOS)

macOS/UITests/UI Tests.xctestplan
Task/Issue URL: https://app.asana.com/0/1206488453854252/1209419738997272
**Description**: Temporarily Disable Failing UI Tests. Disable tests will be then investigated [here](https://app.asana.com/0/1206488453854252/1209421937530812).
**Steps to test this PR**:
1. Green CI
---
[Pull Request Review Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)
=> Add failing tests to skipped tests

.github/workflows/ios_end_to_end.yml, .github/workflows/ios_sync_end_to_end.yml
Task/Issue URL: https://app.asana.com/0/1200194497630846/1209428652263302
CC:
This PR fixes the workflow URL included in the Asana workflow failure task that we send to Asana.
1. Check that there are no other references in the codebase to `duckduckgo/${{ github.repository }}`
---
=> Fix end-to-end failure workflow URLs

.github/workflows/bsk_pr_checks.yml, .github/workflows/ios_pr_checks.yml, .github/workflows/macos_pr_checks.yml, .github/workflows/swiftlint.yml
Task/Issue URL: https://app.asana.com/0/1193060753475688/1209416652835637
CC:
This PR migrates SwiftLint to a shared workflow, replacing the old approach which was running effectively the same workflow step three times.
1. Check that SwiftLint runs and passes
---
=> Migrate to shared SwiftLint workflow

.github/workflows/bsk_pr_checks.yml, .github/workflows/ios_pr_checks.yml, .github/workflows/macos_pr_checks.yml
Task/Issue URL: https://app.asana.com/0/1199333091098016/1209452489210579
CC:
This PR removes some workflow references that no longer exist.
---
=> Fix SwiftLint job references

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/LocalPackages/SyncUI-iOS/Package.swift, iOS/LocalPackages/Waitlist/Package.swift, macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/0/0/1209441254376015
Bumping Apple Toolbox (and also using PR to test the latest Asana task creation changes)
1. Green CI
---
=> Bump Apple Toolbox to 3.1.3

BrowserServicesKit/Package.swift, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209464112525120
sync_crypto PR: https://github.com/duckduckgo/sync_crypto/pull/21
- Update Clibsodium.xcframework from https://github.com/jedisct1/swift-sodium for the binary to contain arm64e architecture
1. Validate sync_crypto lib works as intended (sync works)
2. Turn on Editor -> Canvas -> Use legacy previews
3. Clean-build for testing
4. Validate Xcode previews works
--- …
=> Update Clibsodium.xcframework to fix Xcode Previews

macOS/UITests/OnboardingUITests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209493214374905
Fix testOnboardingToBrowsing test
1. Run the testOnboardingToBrowsing test and see if it passes
=> Fix expected label for UI test

macOS/DuckDuckGo/Updates/UpdateController.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209470800728356
CC:
1. Go to Preferences > About
2. Switch between Automatic and Manual update
3. The updater should dismiss the current update progress and restart itself with the new setting
---
=> Fix toggling automatic update and manual update not working properly

.maestro/shared/copy_recovery_code_from_settings.yaml, .maestro/shared/open_debug_menu.yaml, .maestro/shared/set_internal_user_from_settings.yaml, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo/DebugScreensViewController.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1209492383712538
Fix e2e failed due to the new Debug menu.
[Test run](https://github.com/duckduckgo/apple-browsers/actions/runs/13514490488) failed on my branch due to Robin issue. 
I retried the tests on Robin and [succeeded](https://app.robintest.com/project/proj_01jbvx6s96ewmaza6kdnhqctjc/maestro-test/app/app_01jbw1evv8evxswcf2ge5bncnt/upload/mupload_01jmxtd18re5eszqc82w0ft1g0?sort=name-asc). 
1. Ensure CI is green.
2. Check Robin is [green](https://app.robintest.com/project/proj_01jbvx6s96ewmaza6kdnhqctjc/maestro-test/app/app_01jbw1evv8evxswcf2ge5bncnt/upload/mupload_01jmxtd18re5eszqc82w0ft1g0?sort=name-asc) …
=> Fix sync end to end tests ios

.github/workflows/bsk_pr_checks.yml, .github/workflows/ios_end_to_end.yml, .github/workflows/ios_nightly.yml, .github/workflows/ios_pr_checks.yml, .github/workflows/macos_pr_checks.yml, iOS/README.md
Task/Issue URL: https://app.asana.com/0/1199333091098016/1209528263812418
CC:
This PR updates the simulator version to match the version of Xcode that we use.
1. Check that the iOS PR checks workflow ran and that CI is green
---
=> Update iOS PR check workflow simulator version

iOS/Core/FeatureFlag.swift, iOS/DuckDuckGo/NetworkProtectionStatusView.swift, iOS/DuckDuckGo/NetworkProtectionStatusViewModel.swift, iOS/DuckDuckGo/NetworkProtectionTunnelController.swift, iOS/DuckDuckGo/TipKit/TipKitAppEventHandling.swift, iOS/DuckDuckGo/VPNTipsModel.swift, macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarPopoverManager.swift, macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift, macOS/DuckDuckGo/TipKit/TipKitAppEventHandling.swift, macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift, macOS/LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Menu/StatusBarMenu.swift, macOS/LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/TipViews/Model/VPNTipsModel.swift
Task/Issue URL: https://app.asana.com/0/1203108348835387/1209271788879117
Removes some old feature flags.
If you need a PrivacyPro subscription please follow [these instructions](https://app.asana.com/0/1207603085593419/1209162040898809).
Notes:
- Use the Sparkle build, not the App Store one as it no longer supports some of the tips.
- For these test use the in-app VPN status view, not the menu app we show in macOS's status view.
1. Launch the app.
2. Make sure you're an internal user.
3. Debug menu > TipKit > Reset
4. Relaunch the app.
5. Start the VPN.
6. Once the connection is established you should see the "Change your location" tip.  Dismiss it.
7. Make sure the VPN status view is hidden, and load a site in our browser.
8. Open the VPN status view while keeping the site frontmost.
9. …
=> Removes the enforceRoutes and user tips feature flags

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/0/1199333091098016/1209549009976075
CC:
This PR removes the remote BSK dependency from the iOS project.
This PR has a large diff as this change involved deleting BSK, which removed all of its libraries from each target, and then adding the libraries back.
2. Open the project and confirm that BSK has been removed from the iOS project
3. Give the app a run and make sure it launches fine
No risk here, the app won't compile and run if its dependencies are not correctly linked
--- …
=> Remove the remote BSK dependency from iOS

macOS/DuckDuckGo/History/View/HistoryBurning.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209559057616601
This change adjusts FireHistoryBurner initializer so that it takes an async closure for fetching FireproofDomains.
1. Ensure that burning data from history view works fine.
This is crash fix. I had this crash for me once on one machine for a new user account, for an app that wasn't in /Applications. It was crashing repeatedly but then I wasn't able to reproduce it on any other machine and user account. When I moved the app to /Applications, it stopped crashing and launched fine.
Nothing, thanks to structured concurrency and the fact that the closures are bound to the Main Actor.
---
[Definition of …
=> Fix a crash in FireHistoryBurner initializer for new users

.github/actions/send-release-annotation-pixel/action.yml
Task/Issue URL: https://app.asana.com/0/1199333091098016/1209563179113082
CC:
This PR removes the debug pixel annotation name. Turns out this action is still called with `workflow_dispatch`, not `workflow_call` like I thought, so we can just remove the dispatch check now that the test workflow is gone anyway.
1. Check that the diff looks sensible
---
=> Remove the debug annotation

macOS/DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift, macOS/DuckDuckGo/Statistics/GeneralPixel.swift, macOS/DuckDuckGo/Updates/UpdateController.swift, macOS/DuckDuckGo/Updates/UpdateMenuItemFactory.swift, macOS/DuckDuckGo/Updates/UpdateUserDriver.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209426446786548
CC:
Addresses the "multiple updates in succession" issue by dismissing the pending update and re-check the appcast if it has been 7 days since the last update (for external users) or 1 day for internal users.
This should've targeted 1.129.0.
1. https://app.asana.com/0/1202500774821704/1209475513300640
2.
---
=> Need to update multiple times if I don’t install an available update quickly enough

.maestro/release_tests/bookmarks-multi.yaml, .maestro/release_tests/tabswitcher.yaml, .maestro/setup_ui_tests.sh
Task/Issue URL: https://app.asana.com/0/414709148257752/1209569151580686
CC:
Addresses changes from https://github.com/duckduckgo/apple-browsers/pull/104
1. E2E tests pass
2.
---
=> Fix e2e tests

BrowserServicesKit/Package.resolved, BrowserServicesKit/Package.swift, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Task/Issue URL: https://app.asana.com/0/1206594217596623/1209492139389493/f
CC:
- Updates copy for the onboarding browser comparison chart
1. Open the macOS app
2. Navigate to duck://onboarding
3. Check that the following changes have been made
Old: Block targeted ads
New: Block tracking ads
Old: Erase browsing data swiftly
New: Delete browsing data with one button
Old: YouTube without targeted ads
New: Play YouTube without targeted ads
--- …
=> Bump C-S-S to 7.27.0 - Onboarding copy update

macOS/UITests/FindInPageTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209603746941336
Use temporary directory instead of documents directory for storing the test HTML document.
This is to avoid denied permission to access user’s documents directory on macOS 15.
Verify that [this UI Tests workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/13716253063) is green on macOS 15.
---
=> Fix Find In Page UI Tests

macOS/DuckDuckGo/Common/Extensions/URLExtension.swift, macOS/DuckDuckGo/Menus/MainMenuActions.swift, macOS/DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift, macOS/DuckDuckGo/Preferences/Model/AboutPreferences.swift, macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209568166517627
This change unifies app feedback handling to a single entry point via MainMenuActions.swift
and it replaces native Feedback Form with opening Internal Feedback Form website for internal users.
1. Launch the app and make sure you’re not an internal user.
2. Select _More Options Menu -> Send Feedback -> Send Browser Feedback_ and verify that it opens a native feedback form.
3. Open _Settings -> About_ and click Send Feedback button. Verify that it opens a native feedback form.
4. Open a website and click on Privacy Shield in the address bar. In Privacy Dashboard, click “Report a problem with this website” and then “General DuckDuckGo browser feedback”. Verify that it opens a native feedback form.
5. Set internal user …
=> Use Internal Feedback Form for internal users

iOS/DuckDuckGo/UserText.swift, iOS/DuckDuckGo/bg.lproj/Localizable.strings, iOS/DuckDuckGo/cs.lproj/Localizable.strings, iOS/DuckDuckGo/da.lproj/Localizable.strings, iOS/DuckDuckGo/de.lproj/Localizable.strings, iOS/DuckDuckGo/el.lproj/Localizable.strings, iOS/DuckDuckGo/en.lproj/Localizable.strings, iOS/DuckDuckGo/es.lproj/Localizable.strings, iOS/DuckDuckGo/et.lproj/Localizable.strings, iOS/DuckDuckGo/fi.lproj/Localizable.strings, iOS/DuckDuckGo/fr.lproj/Localizable.strings, iOS/DuckDuckGo/hr.lproj/Localizable.strings, iOS/DuckDuckGo/hu.lproj/Localizable.strings, iOS/DuckDuckGo/it.lproj/Localizable.strings, iOS/DuckDuckGo/lt.lproj/Localizable.strings, iOS/DuckDuckGo/lv.lproj/Localizable.strings, iOS/DuckDuckGo/nb.lproj/Localizable.strings, iOS/DuckDuckGo/nl.lproj/Localizable.strings, iOS/DuckDuckGo/pl.lproj/Localizable.strings, iOS/DuckDuckGo/pt.lproj/Localizable.strings, iOS/DuckDuckGo/ro.lproj/Localizable.strings, iOS/DuckDuckGo/ru.lproj/Localizable.strings, iOS/DuckDuckGo/sk.lproj/Localizable.strings, iOS/DuckDuckGo/sl.lproj/Localizable.strings, iOS/DuckDuckGo/sv.lproj/Localizable.strings, iOS/DuckDuckGo/tr.lproj/Localizable.strings
Task/Issue URL: https://app.asana.com/0/0/1209552448272701
This PR updates some onboarding browser comparison copy. 
1. Delete iOS app from simulator
2. Run and check that browser comparison onboarding screen matches the one shown [here](https://app.asana.com/0/1206488453854252/1209552448272701)
—
=> iOS: Update Onboarding Browser Comparison Copy

.github/workflows/ios_shared_web_tests.yml, iOS/DuckDuckGo/AutomationServer.swift, iOS/DuckDuckGo/MainViewController+Automation.swift, iOS/scripts/shared_web_tests.sh
Task/Issue URL: https://app.asana.com/0/72649045549333/1208763070373634
CC:
This updates the automation server to be more deterministic, have better logs and additionally now run in CI.
1. See the CI is now running.
---
=> Shared web tests ci automation

.github/workflows/macos_ui_tests.yml, macOS/DuckDuckGo/NewTabPage/Features/NewTabPageConfigurationErrorHandler.swift, macOS/DuckDuckGo/Statistics/NewTabPagePixel.swift
Task/Issue URL: https://app.asana.com/0/1201899738287924/1209641120603220
---
=> Remove message parameter from newTabPageExceptionReported pixel

iOS/DuckDuckGo/OnboardingExperiment/ContextualDaxDialogs/NewTabDaxDialogFactory.swift
Task/Issue URL: https://app.asana.com/0/1206329551987282/1209649481723910
Fix onboarding symbols being renamed in main while changed  in release branch
1.
2.
---
=> [iOS] Fix onboarding symbols being renamed in main while merging into release branch

macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Shared/Model/Actions/GetCaptchaInfo.swift, macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Shared/Model/Actions/SolveCaptcha.swift, macOS/LocalPackages/DataBrokerProtection/Tests/DataBrokerProtectionTests/DataBrokerOperationActionTests.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209568501732207
CC:
Expanding the captcha models ahead of the C-S-S changes landing.
1.
2.
---
=> Add optional captchaType key to captcha models

macOS/DuckDuckGo/Preferences/View/PreferencesAboutView.swift
Task/Issue URL: https://app.asana.com/0/1201048563534612/1209644943362614
CC:
Use this build: https://staticcdn.duckduckgo.com/macos-desktop-browser/a81f9679-e41d-404d-81a6-fd4a461d82f7/testbuilds/9b52725/duckduckgo-1.130.0.300.dmg
1. Go to Preferences > About
2. Select Manual Update
3. Choose Update DDG
4. Expect no crash
---
=> Fix macOS 12 crash on Preferences > About

BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift, iOS/Core/FeatureFlag.swift, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo/CheckDefaultBrowser/DefaultBrowserManager.swift, iOS/DuckDuckGo/OnboardingExperiment/Manager/OnboardingManager.swift, iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingIntroViewModel.swift, iOS/DuckDuckGoTests/DefaultBrowserManagerMock.swift, iOS/DuckDuckGoTests/MockFeatureFlagger.swift, iOS/DuckDuckGoTests/OnboardingIntroViewModelTests.swift, iOS/DuckDuckGoTests/OnboardingManager+SetDefaultBrowserExperimentTests.swift, iOS/DuckDuckGoTests/OnboardingManagerMock.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209505775591508
Add logic to handle onboarding experiment Set as Default browser. 
**Prerequisites:** Run the build on a device with iOS 13.3 installed.
**Scenario 1: Control Group**
1. Open the Debug menu.
2. Ensure the `Internal User State` toggle is on.
3. Tap the `Feature Flags` item.
4. Tap “onboardingSetAsDefaultBrowser”.
5. Choose the `control` cohort.
6. Go back to the main debug menu.
7. Tap `Onboarding`.
8. Tap “Preview Onboarding Intro”.
9. Wait for the onboarding to appear and tap the `Let’s do it!` button.
10. Wait for the `Protections activated!` screen to appear.
11. Tap the `Choose Your Browser` button.
12. Ensure that the DuckDuckGo settings in the System settings open.
**Scenario 2 Treatment Group**
1. Open the …
=> [iOS] Onboarding experiment - Set as Default flow

.github/workflows/ios_shared_web_tests.yml
Task/Issue URL: https://app.asana.com/0/72649045549333/1208763070373634
CC:
Removes the conditional checkout which is why it failed in ci when scheduled.
1.
2.
---
=> Remove conditional checkout on ios_shared_web_tests.yml

.maestro/release_tests/bookmarks-multi.yaml, .maestro/release_tests/tabswitcher.yaml, iOS/DuckDuckGo/TabSwitcherBarsStateHandler.swift, iOS/DuckDuckGo/TabSwitcherViewController+MultiSelect.swift, iOS/DuckDuckGo/TabSwitcherViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209667419126827?focus=true
CC: @loremattei 
Fixes e2e release tests related to tab switcher. Minor changes to accessibility labels to improve the tests.
Run release UI tests and make sure they all pass
1. `./.maestro/setup_ui_tests.sh`
2. `./.maestro/run_ui_tests.sh .maestro/release_tests/`
Low
=> fix tab switcher related e2e tests

BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
Task/Issue URL: https://app.asana.com/0/72649045549333/1209505775591506/f
Use existing parent feature for Set as Default subfeature.
Prerequisites: Run the build on a device with iOS 13.3 installed.
Override Privacy Config URL with: https://www.jsonblob.com/api/1344905087407022080
Smoke test Set as Default experiment works. 
**Scenario 1: Treatment Group**
1. Open the Debug menu.
2. Ensure the Internal User State toggle is on.
3. Tap the Feature Flags item.
4. Tap “onboardingSetAsDefaultBrowser”.
5. Choose the treatment cohort.
6. Go back to the main debug menu.
7. Tap Onboarding.
8. Tap “Preview Onboarding Intro”.
9. Wait for the onboarding to appear and tap the Let’s do it! button.
10. Wait for the Protections activated! screen to appear.
11. Tap the 'Choose Your Browser' button.
12. …
=> Use existing parent feature for set as deafult browser subfeature

fastlane/Fastfile, fastlane/README.md
Task/Issue URL: https://app.asana.com/0/1201899738287924/1209718156754294/f
This change adds `update_dependencies` lane in top-level Fastfile, to resolve package dependencies
in all of BSK, iOS, macOS projects and the workspace.
1. Edit `BrowserServicesKit/Package.swift` to use a C-S-S branch:
```swift
.package(url: "https://github.com/duckduckgo/content-scope-scripts", branch: "pr-releases/pr-1561")
```
2. Run `bundle exec fastlane update_dependencies` in the root directory of the repo.
3. Verify that Package.resolved files in BSK, iOS, macOS and the workspace are updated to point to the C-S-S branch.
--- …
=> Add fastlane lane to update SPM dependencies in all projects

iOS/DuckDuckGo/SettingsOthersView.swift
Task/Issue URL: https://app.asana.com/0/392891325557410/1209731450894633/f
CC:
Adds version to about link in settings.
1. Launch the app
2. Visit settings
3. Observe correct version number as the right detail for the about link in settings.
Low: Minor visual change
Not much
It's a limited text change.
n/a
---
=> Add version to about link in settings

.github/workflows/macos_pir_end_to_end_tests.yml
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209746603208461/f
CC:
This PR fixes PIR test failures, caused by a Homebrew issue.
---
=> Fix PIR E2E test failures

.github/workflows/ios_pr_checks.yml
Task/Issue URL: https://app.asana.com/0/1200194497630846/1209748540383575/f
CC:
This PR fixes an issue where the workflow step to closing a failing CI task was itself failing, because it hadn't checked out the code.
1. Check that the diff looks sensible
---
=> Checkout the repo when closing tasks

macOS/UITests/TabBarTests.swift
Task/Issue URL: https://app.asana.com/0/1204006570077678/1209653104775609/f
CC:
Adds and fixes UI tests for recently closed tab tests.
1. You can run the UI tests locally
2. Or you can trust our CI and check is green here: https://github.com/duckduckgo/apple-browsers/actions/runs/13973392355
None
These are just UI tests.
I’m using an external site this time (privacy-config). We use it for other tests, so I do not see any problem.
Nothing.
—
=> Add close tab UI tests

iOS/Gemfile.lock, iOS/fastlane/Pluginfile, macOS/Gemfile.lock, macOS/fastlane/Pluginfile
Task/Issue URL: https://app.asana.com/0/1203301625297703/1209770970102542/f
This change updates the plugin to the version that uses HTTP URL for TrackerRadarKit
to run performance tests.
Verify that CI is green
None
---
=> Update fastlane plugin to 2.2.1

macOS/LocalPackages/DataBrokerProtectionShared/Sources/DataBrokerProtectionShared/Operations/DataBrokerJobRunner.swift, macOS/LocalPackages/DataBrokerProtectionShared/Sources/DataBrokerProtectionShared/Operations/DataBrokerProfileQueryOperationManager.swift
Task/Issue URL: https://app.asana.com/0/481882893211075/1209794552038676/f
CC:
This PR removes a couple seemingly unused PIR extensions, found while reviewing all parts of the operation stack.
1. Check that CI is green - if these extensions are actually used, then the app will fail to compile
---
=> Remove unused PIR extensions

iOS/Core/AppPrivacyConfigurationDataProvider.swift, iOS/Core/ios-config.json
Task/Issue URL: https://app.asana.com/0/1206488453854252/1208681881503648/f
We want to enable an experiment Monday March 31st. We can do this remotely of course. However, the experiment is part of onboarding and so I want to mitigate any risk of the remote file not being available, and so enable it also in the embedded config.
1. Smoke test the iOS app
---
=> iOS: Privacy Pro Onboarding Promo - Update Embedded Config To Enable Experiment

BrowserServicesKit/Package.swift, BrowserServicesKit/Sources/BrowserServicesKit/ContentScopeScript/ContentScopeUserScript.swift, BrowserServicesKit/Sources/PrivacyDashboard/BrokenSiteReporting/BrokenSiteReport.swift, BrowserServicesKit/Sources/PrivacyDashboard/PrivacyInfo.swift, BrowserServicesKit/Tests/PrivacyDashboardTests/BrokenSiteReportMocks.swift, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo/AutofillLoginListViewModel.swift, iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift, iOS/DuckDuckGo/TabViewController.swift, iOS/DuckDuckGoTests/BrokenSiteReportingTests.swift, macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift, macOS/DuckDuckGo/Tab/TabExtensions/PrivacyDashboardTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift, macOS/UnitTests/PrivacyReferenceTests/BrokenSiteReportingReferenceTests.swift, macOS/UnitTests/WebsiteBreakageReport/WebsiteBreakageReportTests.swift
Task/Issue URL: https://app.asana.com/0/1204186595873227/1209774321274642
1. From the debug menu override the privacy configuration with the following (https://jsonblob.com/api/jsonBlob/1351496735427584000) this contains the experiment feature with relevant sub feature which will enrol you to the treatment cohort
2. Open a new tab (this should reload the contentScope user script)
3. Visit https://bad.third-party.site/features/canvas-draw.html
4. go to the privacy Dashboard and click on Report a problem with this site and go through the the flow (it doesn’t matter what you chose) get to sending the report
5. Check on the debugger that on the epbf pixel there are the following parameters: "debugFlags": “fingerprintingCanvas” and "fingerprintingCanvas": “treatment”
6. Visit wikipedia 
7. go …
=> Add breakage metrics

BrowserServicesKit/Package.swift, BrowserServicesKit/Sources/BrowserServicesKit/ContentScopeScript/ContentScopeUserScript.swift, BrowserServicesKit/Sources/PrivacyDashboard/BrokenSiteReporting/BrokenSiteReport.swift, BrowserServicesKit/Sources/PrivacyDashboard/PrivacyInfo.swift, BrowserServicesKit/Tests/PrivacyDashboardTests/BrokenSiteReportMocks.swift, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo/AutofillLoginListViewModel.swift, iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift, iOS/DuckDuckGo/TabViewController.swift, iOS/DuckDuckGoTests/BrokenSiteReportingTests.swift, macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift, macOS/DuckDuckGo/Tab/TabExtensions/PrivacyDashboardTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift, macOS/UnitTests/PrivacyReferenceTests/BrokenSiteReportingReferenceTests.swift, macOS/UnitTests/WebsiteBreakageReport/WebsiteBreakageReportTests.swift
Task/Issue URL: https://app.asana.com/0/1204186595873227/1209774321274642
1. From the debug menu override the privacy configuration with the following (https://jsonblob.com/api/jsonBlob/1351496735427584000) this contains the experiment feature with relevant sub feature which will enrol you to the treatment cohort
2. Open a new tab (this should reload the contentScope user script)
3. Visit https://bad.third-party.site/features/canvas-draw.html
4. go to the privacy Dashboard and click on Report a problem with this site and go through the the flow (it doesn’t matter what you chose) get to sending the report
5. Check on the debugger that on the epbf pixel there are the following parameters: "debugFlags": “fingerprintingCanvas” and "fingerprintingCanvas": “treatment”
6. Visit wikipedia
7. go …
=> Add breakage metrics (#372)

SharedPackages/BrowserServicesKit/Sources/NetworkProtection/PacketTunnelProvider.swift, SharedPackages/BrowserServicesKit/Sources/NetworkProtection/Settings/VPNSettings.swift, iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift, iOS/DuckDuckGo/SubscriptionDebugViewController.swift, iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift, macOS/DuckDuckGo/Application/AppDelegate.swift, macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift, macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift, macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift, macOS/DuckDuckGoVPN/VPNAppEventsHandler.swift, macOS/LocalPackages/NetworkProtectionMac/Sources/VPNAppState/Extensions/UserDefaults+isVPNMigratedToAuthV2.swift, macOS/LocalPackages/NetworkProtectionMac/Sources/VPNAppState/VPNAppState.swift
Task/Issue URL: https://app.asana.com/0/1205842942115003/1209325145462547/f
CC:
1.
2.
---
=> AuthV2 - Use of VPN app state

BrowserServicesKit/Package.swift, BrowserServicesKit/Sources/BrowserServicesKit/ContentScopeScript/ContentScopeUserScript.swift, BrowserServicesKit/Sources/PrivacyDashboard/BrokenSiteReporting/BrokenSiteReport.swift, BrowserServicesKit/Sources/PrivacyDashboard/PrivacyInfo.swift, BrowserServicesKit/Tests/PrivacyDashboardTests/BrokenSiteReportMocks.swift, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo/AutofillLoginListViewModel.swift, iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift, iOS/DuckDuckGo/TabViewController.swift, iOS/DuckDuckGoTests/BrokenSiteReportingTests.swift, macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift, macOS/DuckDuckGo/Tab/TabExtensions/PrivacyDashboardTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift, macOS/UnitTests/PrivacyReferenceTests/BrokenSiteReportingReferenceTests.swift, macOS/UnitTests/WebsiteBreakageReport/WebsiteBreakageReportTests.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209776702731200/f
CC: @samsymons @quanganhdo @SabrinaTardio 
Reverting https://github.com/duckduckgo/apple-browsers/commit/b39177b50c68b3b49ce51fd1033049b4a5c59c5c that created a DBP regression
1. get a subscription
2. open DBP
---
=> DBP bug revert

BrowserServicesKit/Package.swift, BrowserServicesKit/Sources/BrowserServicesKit/ContentScopeScript/ContentScopeUserScript.swift, BrowserServicesKit/Sources/PrivacyDashboard/BrokenSiteReporting/BrokenSiteReport.swift, BrowserServicesKit/Sources/PrivacyDashboard/PrivacyInfo.swift, BrowserServicesKit/Tests/PrivacyDashboardTests/BrokenSiteReportMocks.swift, DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo/AutofillLoginListViewModel.swift, iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift, iOS/DuckDuckGo/TabViewController.swift, iOS/DuckDuckGoTests/BrokenSiteReportingTests.swift, macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift, macOS/DuckDuckGo/Tab/TabExtensions/PrivacyDashboardTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift, macOS/UnitTests/PrivacyReferenceTests/BrokenSiteReportingReferenceTests.swift, macOS/UnitTests/WebsiteBreakageReport/WebsiteBreakageReportTests.swift
Task/Issue URL: https://app.asana.com/0/1207183872881295/1209822612505437/f 
Reverting
https://github.com/duckduckgo/apple-browsers/commit/b39177b50c68b3b49ce51fd1033049b4a5c59c5c that created a DBP regression
2. Check that the diff matches https://github.com/duckduckgo/apple-browsers/pull/388
---
=> DBP bug revert (#388)

iOS/Core/PixelEvent.swift, iOS/DuckDuckGo/AppServices/AutofillService.swift, iOS/DuckDuckGo/AutofillSettingStatus.swift
Task/Issue URL: https://app.asana.com/0/1203822806345703/1208356133120985/f
CC:
1. Testing on device, save a password for `autofill.me` & disable your passcode
2. Set a breakpoint at line 72 of `AutofillSettingStatus`, launch the app and load the `autofill.me` login page.
3. Confirm the breakpoint hits and that the pixel `m_autofill_device_capability_device_auth_disabled` fires
4. Confirm that there are no key icons in the web form and no autofill fill prompt
5. Open a new tab, load a website and confirm the breakpoint does not hit again
6. Re-enable your device passcode and re-open the app
7. Reload the tab with the `autofill.me` login page and confirm autofill prompts as normal
Low: New pixel & minor improvements …
=> Autofill pixel updates

SharedPackages/BrowserServicesKit/Sources/NetworkProtection/Settings/VPNSettings.swift, iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift, iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
Task/Issue URL: https://app.asana.com/0/0/1209325145462547
1.
2.
---
=> iOS VPN v2 fix

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Pixels/FreemiumDBPExperimentPixel.swift, macOS/DuckDuckGo/Application/AppDelegate.swift, macOS/DuckDuckGo/Freemium/DBP/Experiment/FreemiumDBPPixelExperimentManaging.swift, macOS/UnitTests/Freemium/DBP/Experiment/FreemiumDBPPixelExperimentManagingTests.swift, macOS/UnitTests/Freemium/DBP/FreemiumDBPFeatureTests.swift
Task/Issue URL: https://app.asana.com/0/1206488453854252/1209667521089787/f
Remove temporary Freemium PIR experiment pixel, previously added [here](https://app.asana.com/0/1206488453854252/1209669505169616/f).
1. Green CI
—
=> macOS: Remove Temporary Freemium PIR pixel

macOS/DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser.xcscheme
Task/Issue URL: https://app.asana.com/0/0/1209837134147760
Disabling this test for now. I will look into this as part of [this task](https://app.asana.com/0/0/1209837134147761). I’ve also confirmed this is just a flakey test, and not an actual functional failure.
---
=> Freemium PIR: Disable Flakey Test

macOS/IntegrationTests/NavigationProtection/NavigationProtectionIntegrationTests.swift
Task/Issue URL: https://app.asana.com/0/1205237866452338/1205328646802302/f
Disable verifying one of the results which tends to be very flaky.
---
=> Update GPC integration test to skip frame JS API entry

iOS/DuckDuckGo/PullToRefreshViewAdapter.swift
Task/Issue URL: https://app.asana.com/0/0/1209837728974660/f
CC: @dus7 
As in title.
1. Have experimental flag turned on.
2. Pull to refresh page and see that further you go down it is harder to move the card.
3. Make sure it is still possible to refresh site.
None: Feature is behind flag
---
=> Add resistance to pulling if you reach certain threshold to make it feel more natural

iOS/DuckDuckGo/AppConfiguration/AppConfiguration.swift, iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1209837728974677/f
CC: @jonathanKingston 
Just keeping the launching code clean.
1. Make sure the automation server code still works.
---
=> Move automation server code into AppConfiguration

SharedPackages/BrowserServicesKit/Sources/Networking/Auth/OAuthClient.swift
Task/Issue URL: https://app.asana.com/0/1205842942115003/1208723559486362
Fixed an error where the expiry buffer time was too big for non-Debug apps using the staging API
---
=> Expiry buffer fixed

iOS/DuckDuckGo/MainViewController.swift
Task/Issue URL: https://app.asana.com/0/0/1209885802768382/f
CC:
OmniBar background has been changed to an invalid color in #405. This reverts the change.
1. Check OmniBar background matches the toolbar when set to bottom and upper part of the screen when set to top.
Nothing - this reverts back the color to a proper value.
---
=> Fix OmniBar background color

macOS/UnitTests/NewTabPage/NewTabPageCustomizationProviderTests.swift
Task/Issue URL: https://app.asana.com/0/1205237866452338/1209325499010383/f
---
=> Stabilize New Tab Page Customization tests

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/ContentScopeScript/ContentScopeUserScript.swift, SharedPackages/BrowserServicesKit/Sources/PrivacyDashboard/BrokenSiteReporting/BrokenSiteReport.swift, SharedPackages/BrowserServicesKit/Sources/PrivacyDashboard/PrivacyInfo.swift, SharedPackages/BrowserServicesKit/Tests/BrowserServicesKitTests/ContentScopeScriptTests/ContentScopeUserScriptTests.swift, SharedPackages/BrowserServicesKit/Tests/PrivacyDashboardTests/BrokenSiteReportMocks.swift, iOS/DuckDuckGo/AutofillLoginListViewModel.swift, iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift, iOS/DuckDuckGo/TabViewController.swift, iOS/DuckDuckGoTests/BrokenSiteReportingTests.swift, macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift, macOS/DuckDuckGo/Tab/TabExtensions/PrivacyDashboardTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift, macOS/UnitTests/PrivacyReferenceTests/BrokenSiteReportingReferenceTests.swift, macOS/UnitTests/WebsiteBreakageReport/WebsiteBreakageReportTests.swift
Task/Issue URL: https://app.asana.com/0/1204186595873227/1209854647384644/f
On both macOS and iOS
1. From the debug menu override the privacy configuration with the following (https://jsonblob.com/api/jsonBlob/1351496735427584000) this contains the experiment feature with relevant sub feature which will enrol you to the treatment cohort
2. Open a new tab (this should reload the contentScope user script)
3. Visit https://bad.third-party.site/features/canvas-draw.html
4. go to the privacy Dashboard and click on Report a problem with this site and go through the the flow (it doesn’t matter what you chose) get to sending the report
5. Check on the debugger that on the epbf pixel there are the following parameters: "debugFlags": “fingerprintingCanvas” and "fingerprintingCanvas": “treatment”
6. …
=> re introdulce C-S-S flag and cohort moniroting in breakage pixel

macOS/DBPE2ETests/DBPEndToEndTests.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionAppEvents.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionFeatureDisabler.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionMacOSPixelsHandler.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionManager.swift, macOS/DuckDuckGo/Freemium/DBP/FreemiumDBPScanResultPolling.swift, macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/BackgroundAgent/DataBrokerProtectionAgentManager.swift, macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Pixels/DataBrokerProtectionMacOSPixels.swift, macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UINative/DBPUIViewModel.swift, macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/UINative/DataBrokerProtectionViewController.swift
Task/Issue URL: https://app.asana.com/0/1201037661562251/1209880191552590/f
CC:
As title
This consists of two things:
- Going back to making it not a crash
- Adding pixels so it no longer fails silently
This still isn't great as it means in these cases PIR is in an undefined state and just won't work, but at we'll at least have visibility on that and it'll go back to only affecting PIR rather than the rest of the app.
It's not great that this has existed silently forever, so we should endeavor to fix it properly at the earliest opportunity
1. Smoke test PIR 
2. In SecureVaultFactory.makeVault, line 63, make it throw an error
3. Run the main app and check the new pixel is fired with the correct name (i.e. the main app one and not the background agent one), and has the …
=> Make initialial secure vault failures no longer a crash, and add pixels so we know they happen

iOS/DuckDuckGo/MainViewController.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1209892386356515/f
=> Fix crash related on onboarding caused by referencing wrong button

macOS/UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatorTests.swift
Task/Issue URL: https://app.asana.com/0/1199230911884351/1209919641648894/f
- disable flaky test
1.
2.
---
=> disable flaky testCloseAction_dismissesPromotion_andFiresPixel

iOS/DuckDuckGo/Refactoring/Default/DefaultOmniBarViewController.swift
Task/Issue URL: https://app.asana.com/0/414709148257752/1209922915318044/f
CC:
Delegate to first responder funcs in actual implementation
1. Launch app and open new tab - no "click" pixel should fire
2. Tap the omnibar text field - "click" pixel should fire
3. Check other ways to create new tab (swiping, tab switcher) and ensure "click" pixel only fires when tapping the field
4. Ensure tapping and typing into the field shows suggestions and allows navigations.
Low: small bug fixes
Could stop address bar from working
Ensure no core flows broken
n/a
--- …
=> delegate to implementation for first responder funcs

.maestro/browser_features/state_restoration.yaml, .maestro/release_tests/application-lock.yaml, .maestro/release_tests/autoclear.yaml, .maestro/release_tests/backgrounding.yaml, .maestro/release_tests/bookmarks-multi.yaml, .maestro/release_tests/bookmarks.yaml, .maestro/release_tests/favorites.yaml, .maestro/release_tests/firebutton.yaml, .maestro/release_tests/widgets.yaml
Task/Issue URL: https://app.asana.com/0/856498667320406/1209922864994396/f
CC:
Wait for webpage to fully load before moving forward
Run tests locally, they should pass.
---
=> Improve Maestro reliability: Wait for webpage to fully load before moving forward

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/LocalPackages/NetworkProtectionMac/Package.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1209958084516053
1. Validate CI checks pass
2. Launch macOS app, validate the Fire button and Fire animations work
3. Launch iOS app, validate Fire animation works
---
=> Lottie -> 4.5.1

iOS/Gemfile.lock, iOS/fastlane/Pluginfile
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1209986226704283?focus=true
Bump of fastlane plugin with extended Asana URL parsing to also allow optional markdown bold formatting.
---
=> Bump fastlane plugin for iOS to 2.2.3

macOS/DuckDuckGo/Application/AppDelegate.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210000334407470?focus=true
- Disables macOS system window Tabbing support
1. Enter full screen mode
2. Validate View menu has no "Show Tab Bar" and "Show all tabs" items
Low
Nothing
---
=> disable macOS system-wide window tabbing

macOS/DuckDuckGo/Common/View/AppKit/MouseOverButton.swift, macOS/DuckDuckGo/MainWindow/MainViewController.swift, macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, macOS/DuckDuckGo/PinnedTabs/View/PinnedTabsHostingView.swift, macOS/DuckDuckGo/Tab/Model/NewWindowPolicy.swift, macOS/DuckDuckGo/Tab/Model/Tab+UIDelegate.swift, macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift, macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/NavigationHotkeyHandler.swift, macOS/DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift
- Refactor Address Bar to use `LinkOpenBehavior` 
1. Enter some URL in the address bar
2. Cmd+Enter should open background tab (Active if Activate new tab setting is On)
3. Cmd+Shift+Enter should open active tab (Background if Activate new tab setting is On)
4. Cmd+Opt - new background window
5. Cmd+Opt+Shift - new active
6. Opt+Enter start download
---
=> Address bar standard new tab policy

macOS/DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift, macOS/DuckDuckGo/Common/View/AppKit/MouseOverButton.swift, macOS/DuckDuckGo/MainWindow/MainViewController.swift, macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, macOS/DuckDuckGo/PinnedTabs/View/PinnedTabsHostingView.swift, macOS/DuckDuckGo/Tab/Model/NewWindowPolicy.swift, macOS/DuckDuckGo/Tab/Model/Tab+UIDelegate.swift, macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift, macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/NavigationHotkeyHandler.swift, macOS/DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift
- Refactor Bookmark Manager to use `LinkOpenBehavior` 
- Support middle click
- Support cmd+clicking inactive window or window in inactive app
1. Open Bookmarks Manager, have some bookmarks 
2. Open a new window; Activate another app (safari/mattermost..)
3. In the 1st (background) window use middle click to open background tab; middle+shift should open active tab; middle+opt - background window; middle+shift+opt - active window
4. Cmd+Right-Click a bookmark on the inactive window bookmarks, choose Open In new tab/Window - validate the menu items work correctly, …
=> Bookmarks Manager Details view standard new tab policy

macOS/DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift, macOS/DuckDuckGo/Bookmarks/View/BookmarksOutlineView.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.xib, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarMenuViewController.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift, macOS/DuckDuckGo/Common/View/AppKit/MouseOverButton.swift, macOS/DuckDuckGo/MainWindow/MainViewController.swift, macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, macOS/DuckDuckGo/PinnedTabs/View/PinnedTabsHostingView.swift, macOS/DuckDuckGo/Tab/Model/NewWindowPolicy.swift, macOS/DuckDuckGo/Tab/Model/Tab+UIDelegate.swift, macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift, macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/NavigationHotkeyHandler.swift, macOS/DuckDuckGo/Windows/View/WindowControllersManager.swift, macOS/DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift
- Refactor Bookmark Bar to use `LinkOpenBehavior` 
- Support middle click
- Support cmd+clicking inactive window or window in inactive app
1. Open New Tab view, have some bookmarks and folders added on the bookmarks bar
2. Open a new window; Activate another app (safari/mattermost..)
3. In the 1st (background) window use middle click to open background tab; middle+shift should open active tab; middle+opt - background window; middle+shift+opt - active window
4. Cmd+Right-Click a bookmark on the inactive window bookmarks bar, choose Open In new tab/Window - validate …
=> Bookmarks Bar standard new tab policy

macOS/DuckDuckGo/Bookmarks/Services/BookmarksContextMenu.swift, macOS/DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift, macOS/DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift, macOS/DuckDuckGo/Bookmarks/View/BookmarksOutlineView.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.xib, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarMenuViewController.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift, macOS/DuckDuckGo/Common/View/AppKit/MouseOverButton.swift, macOS/DuckDuckGo/MainWindow/MainViewController.swift, macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, macOS/DuckDuckGo/PinnedTabs/View/PinnedTabsHostingView.swift, macOS/DuckDuckGo/Tab/Model/NewWindowPolicy.swift, macOS/DuckDuckGo/Tab/Model/Tab+UIDelegate.swift, macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift, macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift, macOS/DuckDuckGo/Tab/TabExtensions/NavigationHotkeyHandler.swift, macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift, macOS/DuckDuckGo/Windows/View/WindowControllersManager.swift, macOS/DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift, macOS/UnitTests/Bookmarks/Model/ContextualMenuTests.swift, macOS/UnitTests/Freemium/DBP/FreemiumDBPPresenterTests.swift, macOS/UnitTests/RecentlyClosed/RecentlyClosedCoordinatorTests.swift, macOS/UnitTests/Suggestions/Model/SuggestionContainerTests.swift
- Refactor Bookmark List to use `LinkOpenBehavior` 
- Support middle click
- Respect “When opening links select tab” when opening item in New Tab from context menu
1. Open New Tab view
2. Open a new window
3. In the 1st (background) window command-click the Bookmarks shortcut on the nav bar: bookmark list should open in the background
4. Middle-click bookmarks: should open in background tabs; middle+shift should open active tab; middle+opt - background window; middle+shift+opt - active window
5. Cmd+Click should open new background tab (in the same window)
6. …
=> Bookmark list standard new tab policy

macOS/DuckDuckGo/Statistics/GeneralPixel.swift, macOS/DuckDuckGo/Updates/UpdateController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205278999335242/task/1209550949030968
CC:
Removes temp pixels as part of Privacy Triage clean up process. 
1. CI passes
---
=> Remove temp Sparkle pixels

iOS/DuckDuckGo-iOS.xcodeproj/xcshareddata/xcschemes/iOS Browser.xcscheme, iOS/DuckDuckGoTests/SyncSettingsViewControllerErrorTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1207832286109554?focus=true
1. Chec CI is green
---
=> fix and re-enable test

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift, macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift, macOS/UITests/AIChatTests.swift
Task/Issue URL: https://app.asana.com/0/1204167627774280/1209993325158889/f
Add a couple tests for AI Chat button settings
1. Check if CI is green and running the new tests
Low: Couple of accessibility labels and tests
=> Add initial set of tests for AI Chat button

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210033048220391?focus=true
CC:
This PR fixes iOS ATB UI test compilation.
1. Run the ATB UI test target locally and check that it compiles correctly
None, internal tooling change
A change I'd like to make later is to pull out the ATB and Fingerprinting workflow steps into their own file, able to be dispatched separately without triggering an alpha build. I'm keeping it out of scope here since the change is simple and verifying this locally is quick.
--- …
=> Fix iOS ATB UI test compilation

.github/workflows/ios_adhoc.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210057065449918?focus=true
Verify that [this workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/14625262243) posts the build with codename BUNN to the Asana task linked above.
---
=> Support Asana V1 URL in ios_adhoc.yml

macOS/DuckDuckGo/BookmarksBar/View/BookmarksBar.storyboard, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.xib, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewModel.swift, macOS/DuckDuckGo/MainWindow/MainView.swift, macOS/DuckDuckGo/MainWindow/MainViewController.swift, macOS/DuckDuckGo/MainWindow/MainWindowController.swift, macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204517122485752/task/1205091603309347?focus=true
- Update Bookmark Bar to match updated designs
- https://www.figma.com/design/VBVsz82msH2KB1skRaFIVF/%F0%9F%93%99-Bookmark-Management?node-id=7410-45295&m=dev
- Move constants to separate `enum`
- Fix issues related to Full Screen Hide tab bar setting (empty bookmarks bar visible when the Default prompt is shown)
1. add `setPromptShown(false)` to `DefaultBrowserAndDockPromptStoring.init` so the Set Default prompt is shown on launch; Activate View -> Bookmarks Bar -> Always show
2. Enter full screen, turn off View -> Show Tab Bar and Bookmarks Bar: validate the UI with the Default Prompt doesn‘t show the empty bookmarks bar
3. Toggle on View -> Show Tab Bar and Bookmarks Bar, …
=> Bookmarks bar design update

macOS/DuckDuckGo/Bookmarks/View/BookmarkFolderPicker.swift, macOS/DuckDuckGo/SecureVault/View/PopUpButton.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1208767189188914?focus=true
- Fixes folder chooser popup button title appearing in gray color in Add Bookmark popover with dark system them
1. Activate system dark theme in settings
2. Open a website, click the Bookmark button in the address bar
3. Validate the Folder Chooser title color is white
4. Change system color to Light
5. Validate the folder chooser title color changes to black
Low
Label color not changing when system/browser them change
---
=> Fix folder chooser popup font color in Bookmark popover

SharedPackages/BrowserServicesKit/Sources/Networking/Auth/OAuthClient.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/DataBrokerOperation.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210107502538281?focus=true
CC: @THISISDINOSAUR 
- PIR: Log containing personal info has been removed
- AuthV2: Token expired related log has been improved
No testing needed
---
=> AuthV2 and PIR logs improved

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210124812962106?focus=true
Provides a workaround for the PIF build errors.
1. `git checkout tags/1.137.0-422+macos `
2. Build
3. Do not close the project, keep it open in Xcode
4. `git checkout main`
5. Build
6. You should see the PIF error
1. `git checkout tags/1.137.0-422+macos `
2. Build
3. Do not close the project, keep it open in Xcode
4. `git checkout diego/tentative-fix-for-pif-errors`
5. Build
6. You should NOT see the PIF error
None.
Nothing
NA
NA
---
=> Workaround for the PIF build errors

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, SharedPackages/BrowserServicesKit/Package.resolved, SharedPackages/BrowserServicesKit/Package.swift, SharedPackages/DataBrokerProtectionCore/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Task/Issue URL: https://app.asana.com/1/137249556945/project/1207252092703676/task/1210128066798031?focus=true
CC: @shakyShane @afterxleep 
Bumps C-S-S to version 8.19.0, which adds the `color=white` to Duck Player embedded URLs. This forces the classic YouTube player UI to display.
The new UI is being rolled out to mobile first, therefore this is easier to test on iOS
- Open Duck Player on any video
- Use Safari to inspect the Duck Player window
- Confirm that the iframe has a src attribute that includes the query param `color=white` . You can run this on the console to confirm `document.querySelector('iframe').src.includes('color=white');`
- Confirm that the player interface looks like this
and not like this
---
[Definition of Done](https://app.asana.com/0/1202500774821704/12076346335370 …
=> Bump C-S-S to 8.19.0

.github/workflows/ios_shared_web_tests.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210120666150496?focus=true
CC:
This PR updates the shared web tests workflow to create a failure task with a disambiguated name from typical failure tasks.
1. Check that [this failure task](https://app.asana.com/1/137249556945/project/1205237866452338/task/1210120907154359?focus=true) looks correct and was added to the right section
---
=> Update shared web tests failure workflow

iOS/DuckDuckGo/SwipeTabsCoordinator.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210150959864255?focus=true
CC:
1. Set address bar to the bottom
2. Rotate the device to landscape
3. Swipe the page
4. Omnibar should not disappear.
---
=> Revert changes to OmniBar

DuckDuckGo.xcworkspace/contents.xcworkspacedata
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203108348835387/task/1210158392953352
Add a top level SharedPackages group folder so that shared packages can be collapsed.
Just make sure the CI goes green.
Low: this could cause trouble with the project file, but the CI going green should help validate there's no issue.
NA
NA
NA
---
=> Adds SharedPackages top-level folder

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210124812962106?focus=true
CC:
Addresses PIF issue similar to https://github.com/duckduckgo/apple-browsers/pull/634
1. CI passes
2.
---
=> PIF workaround for DuckUI

macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210166303053316?focus=true
CC:
After the merge of #632, I realized I made a mistake and introduced lag when opening new tabs.
The fix is to inject the style, instead of the manager, which needs to make the call about checking the feature flag and more.
Note: This is not part of the internal release, so no need to merge to the release branch.
**Fix**
1. Open the app
2. Use the CMD+T shortcut to open a lot of tabs
3. The result should be smooth
**Current state**
1. Open the app (from the `main` branch)
2. Use the CMD+T shortcut to open a lot of tabs
3. Check that there is a lag when opening new tabs.
This doesn’t get merged before the next …
=> Fix lag when creating multiple tabs

SharedPackages/BrowserServicesKit/Sources/Networking/Auth/README.md, SharedPackages/BrowserServicesKit/Sources/Networking/README.md
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1209672964727004?focus=true
CC:
AuthV2 README documentation
---
=> AuthV2 documentation

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/UIWeb/DBPUICommunicationLayer.swift, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo/AppLifecycle/AppDependencies.swift, iOS/DuckDuckGo/AppLifecycle/AppStates/Background.swift, iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift, iOS/DuckDuckGo/AppServices/DBPService.swift, iOS/DuckDuckGo/Info.plist, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataBrokerProtectionIOSManager.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210171783578081?focus=true
CC:
Adds rudimentary background processing for PIR
This includes actually setting up the DBPiOSManager, so now the database viewer will work hurray (Although there's still now way to get anything into the database 😅. But for now for debug and alpha builds it hardcodes a profile into the DB )!
For now it only does so for debug and alpha builds since we're a long way from wanting any of this in production
1. For now we don't actually want PIR to do anything, so make sure the general app works, and particularly keep an eye on cpu usage etc to check it isn't affected
--- …
=> PIR iOS initial implementation: background processing

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/CCF/WebViewHandler.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/UIWeb/DBPUICommunicationLayer.swift, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo/AppLifecycle/AppDependencies.swift, iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift, iOS/DuckDuckGo/AppLifecycle/AppStates/Background.swift, iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift, iOS/DuckDuckGo/AppServices/DBPService.swift, iOS/DuckDuckGo/DataBrokerProtectionDebugViewController.swift, iOS/DuckDuckGo/Debug.storyboard, iOS/DuckDuckGo/DebugScreensViewModel+Screens.swift, iOS/DuckDuckGo/Info.plist, iOS/DuckDuckGo/Subscription/Extensions/DataBrokerProtectionSettings+Environment.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataBrokerProtectionIOSManager.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataCaching/DataBrokerProtectionDataManager.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/Debug/DatabaseBrowser/DebugDatabaseBrowserView.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/Debug/DatabaseBrowser/DebugDatabaseBrowserViewController.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/Debug/DatabaseBrowser/DebugDatabaseBrowserViewModel.swift, macOS/DuckDuckGo/Subscription/DataBrokerProtectionSettings+Environment.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210171783578079?focus=true
CC:
Does the required auth and environment setup (i.e. staging v production) for DBP
It also includes the DataManager from macOS since it is required in the absence of any alternative. The intention is to delete this even before we go to alpha. The diff looks a lot larger than it is because of this
1. Smoke test iOS to ensure nothing is broken
---
=> PIR iOS initial implementation: environment and data setup

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/BrokerManaging/LocalBrokerJSONService.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/BrokerManaging/RemoteBrokerJSONService.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Step.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/invalid-broker-with-unsupported-action.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/invalid-broker-with-unsupported-step.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/valid-broker.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1205508328452434?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209813786547143
CC:
Adds better handling code to skip incompatible JSONs.
1. CI passes
---
=> Remote broker delivery: Better JSON handling

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift, SharedPackages/DataBrokerProtectionCore/Package.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/BrokerManaging/LocalBrokerJSONService.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/BrokerManaging/RemoteBrokerJSONService.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Step.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCoreTestsUtils/Mocks.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/invalid-broker-with-unsupported-action.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/invalid-broker-with-unsupported-step.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/valid-broker.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerTests.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/LocalBrokerJSONServiceTests.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/RemoteBrokerJSONServiceTests.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/Utils.swift, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo/DBP/DataBrokerProtectionDebugMenu.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionManager.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/BackgroundAgent/DataBrokerProtectionAgentManager.swift, macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1205508328452434?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209813786547143
CC:
Adds feature flag to gate remote broker delivery.
1. Make sure remote broker delivery doesn't happen by default (check the console logs). Note that database migration still happens.
2. Use `https://raw.githubusercontent.com/duckduckgo/privacy-configuration/490c474f4e1ff4caf0261bf34eca67b42493a49f/overrides/macos-override.json` as the privacy config
3. Trigger remote broker update by editing your profile (and having new scan jobs created)
--- …
=> Remote broker delivery: Add feature flag

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/OperationQueueManaging/DataBrokerProtectionQueueManager.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCoreTestsUtils/Mocks.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionQueueManagerTests.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataBrokerProtectionIOSManager.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/BackgroundAgent/DataBrokerProtectionAgentManager.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Tests/DataBrokerProtection-macOSTests/DataBrokerProtectionAgentManagerTests.swift, macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1205508328452434?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209813786547143
CC:
Addresses https://github.com/duckduckgo/apple-browsers/pull/597#discussion_r2071467480
Extracts brokerUpdater out of the queue manager.
1. Change `remoteBrokerDelivery` flag to `enabled`
2. Follow 2 scenarios outlined in https://github.com/duckduckgo/apple-browsers/pull/597#issue-3020812529
---
=> Remote broker delivery: Extract brokerUpdater out of queue manager

macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionAndNotificationTargets/InfoPlist.xcstrings, macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210166303053340?focus=true
Navigation bar corner radius based on the new design specification.
**Test original design**
1. Disable internal user state
2. Open a new window and make sure the navigation bar has correct background color and it doesn't have any corner radius on top.
3. Repeat the test in dark mode
**Test new design**
1. Enable internal user state and the visual refresh feature flag
2. Open a new window and verify the navigation bar matches [the new design](https://www.figma.com/design/hiyClFzZVkiYfLicSaN3iJ/Toolbar-Spec-2025?m=dev), specifically the color and corner radius
5. Repeat the test in dark mode
_Note: The border line will be removed as a part of the different PR_
Low: Minor visual …
=> Navigation bar corner radius

.github/workflows/danger.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210209652200970?focus=true
---
=> Revert to main branch for Danger

macOS/LocalPackages/PreferencesUI-macOS/Package.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210223314979540?focus=true
CC:
Fixing the macOS dependency version mismatch after merging #697.
1. CI is green.
---
=> Fix DRK dependency mismatch

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/DuckDuckGo/LogExporter/LogExporter.swift, macOS/DuckDuckGo/LogExporter/LogExporterView.swift, macOS/DuckDuckGo/LogExporter/MainViewController+LogExporter.swift, macOS/DuckDuckGo/Menus/MainMenu.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210170292495852?focus=true
CC: @diegoreymendez @quanganhdo @mallexxx 
Refactoring of the pre-existing `Save Logs...` debug menu under `Logging`
Now the menu is called `Export  Logs` and creates a zip file on the desktop containing all the filtered logs required for debugging Subscription, VPN and Sparkle
Debug menu > Logging > Export logs...
---
=> Export logs debug menu

macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210240601513967?focus=true
1. Type in the address bar
2. Verify that the search icon is vertically aligned with search icons in the suggestion window.
---
=> Fix search icon alignment in the address bar

.github/workflows/create_asana_pr_subtask.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210286913760575?focus=true
CC:
This PR skips the `Copilot` user when attempting to generate subtasks.
1. Check that CI is green, and that Copilot was requested for review
2. Check that a non-Copilot review request did have a task generated
---
=> Skip `Copilot` when generating review subtasks

macOS/DuckDuckGo/Common/View/AppKit/MouseOverView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1210175186875474?focus=true
- Fixes an issue when Bookmarks bar item sends mouseUp when clicking outside of it
1. Set bookmarks bar to be always visible.
2. Activate a bookmark from the bookmarks bar and wait for the page to load.
3. Focus URL bar and press enter – the page reloads.
4. Focus the URL bar again – validate the URL bar is not defocused and page does not reload automatically.
5. Open new tab
6. Activate a bookmark from inside a folder in the bookmarks bar, repeat the Enter -> Click sequence, validate everything is expectable.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | …
=> fix mouseUp sent with mouse outside of view

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210332536790935?focus=true
CC:
This PR enables release optimizations for alpha builds.
2. Check that [this workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/15145128893) succeeded (TODO: still running at the time of writing this)
---
=> Turn on optimizations for alpha builds

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/BrokerProfileScanSubJob.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Pixels/DataBrokerProtectionSharedPixels.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Pixels/DataBrokerProtectionStageDurationCalculator.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/UtilsShared/DataBrokerProtectionSettings.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCoreTestsUtils/Mocks.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BrokerProfileOptOutSubJobTests.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionStageDurationCalculatorTests.swift, iOS/DuckDuckGo/AppServices/DBPService.swift, iOS/DuckDuckGo/DataBrokerProtectionDebugViewController.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataBrokerProtectionIOSManager.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/Debug/DatabaseBrowser/DebugDatabaseBrowserViewModel.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/Pixels/IOSPixels.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/UserDefaults/UserDefaultsExtension.swift
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210271610309562?focus=true
CC:
Readds what was reverted in https://github.com/duckduckgo/apple-browsers/pull/809
Adds the pixels and parameters for the required alpha build.
Note that these parameters must never reach production, and are compile flagged and commented appropriately
Do not merge until privacy triage is approved
Also sneaks unrelated changes in:
Fixes an issue where we didn't schedule a new background task if the previous one completed without the expiration handler firing
Changes the events table in the db viewer to show the newest first
Renames a file to remove the DataBrokerProtection prefix as previously discussed. The iOSManager is now the only one with it. I deliberately kept it, since …
=> PIR iOS: Pixels take 2

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBar.storyboard, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionView.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.swift, macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift, macOS/DuckDuckGo/MainWindow/MainViewController.swift, macOS/DuckDuckGo/Tab/View/BrowserTabViewController.swift, macOS/DuckDuckGo/Tab/View/WebViewContainerView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1210110223897550?focus=true
- fixes drag destination when dragging links/bookmarks to web view
1. Drag a bookmark from the bookmarks bar to web view
2. validate website is loaded
3. With Cmd/Option pressed, a new tab should be opened
---
=> fix dragging destination for links/bookmarks dragged to Web View

.maestro/shared/set_sync_dev_environment.yaml, .maestro/sync_tests/01_create_account.yaml, .maestro/sync_tests/02_login_account.yaml, .maestro/sync_tests/03_recover_account.yaml, .maestro/sync_tests/04_sync_data_setup.yaml, .maestro/sync_tests/05_sync_data_check.yaml, .maestro/sync_tests/06_delete_account.yaml
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210348746441845?focus=true
Fixed some sync UI tests by setting the environment (it's not dev for debug builds by default any more).
https://github.com/duckduckgo/apple-browsers/actions/runs/15214212091
---
=> Fix sync iOS e2e tests

iOS/Core/PixelEvent.swift, iOS/DuckDuckGo/DuckPlayer/NativeUI/DuckPlayerNativeUIPresenter.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1210320494056771
CC:
- Fixes some pixel names
- Correctly passing parameters to a daily pixel
- CI should be 🥬 
While not required, if you want to test Daily Pixel changes:
- Open youtube.com and load a video in DuckPlayer
- Confirm Daily pixel `duckplayer_native_daily-unique-view` is fired with 'toggle' and 'setting' parameters 
N/A
Manually tested individual pixels
---
=> iOS: Duckplayer: Pixel Updates

macOS/NetworkProtectionSystemExtension/NetworkProtectionSystemExtension.entitlements, macOS/NetworkProtectionSystemExtension/NetworkProtectionSystemExtension_SparkleDistribution.entitlements
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210372762601258?focus=true
CC:
This PR fixes Keychain access issues with system extensions running in older macOS versions.
1. See builds in [this task](https://app.asana.com/1/137249556945/project/1199333091098016/task/1210372762601258?focus=true) - run these in a macOS 12 or 13 VM to verify the fix
---
=> Fix Keychain access for sandboxed system extensions on macOS 12 and 13

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Action.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionFeatureTests.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/Debug/DataBrokerRunCustomJSONViewModel.swift
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210336468504188?focus=true
CC:
The check should apply to ExpectationAction, not ExtractAction, as literally commented here: https://github.com/duckduckgo/apple-browsers/blob/9d941dffba1bbdb716bb7fea267887696644d5c2/SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Action.swift#L48
1. Refer to https://app.asana.com/1/137249556945/task/1210336468504188?focus=true
2. CI passes
---
=> Fix a typo in timeout check logic

macOS/DuckDuckGo/LoginItems/LoginItemsManager.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210418194047800?focus=true
CC:
This PR fixes a hardcoded error parameter.
1. Make sure the diff makes sense
---
=> [Release PR] Fix hardcoded error pixel parameter

macOS/DuckDuckGo/VisualRefresh/SuggestionsIconsProviding.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210434646583406?focus=true
Fix icons so that search displays a magnifying glass and history entry displays a clock.
Verify that the [UI tests workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/15386324796) is green.
---
=> Update phrase and history icons in LegacySuggestionsIconsProvider

iOS/DuckDuckGo/BlankSnapshotViewController.swift, iOS/DuckDuckGo/MainViewController.swift, iOS/DuckDuckGo/TabsBarViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210454351939907?focus=true
CC:
1. Enable Application Lock
2. Send app to background
3. The app shouldn’t crash
<!— 
High: Could affect user privacy, lose user data, break core functionality
—>
<!— 
- How does this affect performance?
- What documentation needs updating?
- How does this impact privacy/security? …
=> Fix crash for iPad users with Application Lock enabled

.github/workflows/ios_pr_checks.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/856498667320406/task/1210382925425405?focus=true
CC:
Fix wrong condition in PR checks workflow
Validate workflow file.
---
=> Fix wrong condition in PR checks workflow

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift, macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift, macOS/DuckDuckGo/Statistics/NavigationBarPixel.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210448832844157?focus=true
This change adds daily pixels to navigation bar buttons.
Verify that daily pixels are being sent according to the contents of the linked task.
---
=> Add pixels for navigation bar tool buttons

.cursor/rules/analytics-patterns.mdc, .cursor/rules/anti-patterns.mdc, .cursor/rules/architecture.mdc, .cursor/rules/code-style.mdc, .cursor/rules/feature-flags.mdc, .cursor/rules/general.mdc, .cursor/rules/ios-architecture.mdc, .cursor/rules/macos-system-integration.mdc, .cursor/rules/macos-window-management.mdc, .cursor/rules/performance-optimization.mdc, .cursor/rules/privacy-security.mdc, .cursor/rules/property-wrappers.mdc, .cursor/rules/shared-packages.mdc, .cursor/rules/swiftui-advanced.mdc, .cursor/rules/swiftui-style.mdc, .cursor/rules/testing.mdc, .cursor/rules/webkit-browser.mdc, .gitignore
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204099484721401/task/1210460315061997
CC:
This is an initial set of cursor rules that I've originally generated using AI, and have been maintaining over the past few months.  These should help the LLM generate better code, based on the existing codebases for macOS and iOS.
N/A
N/A
N/A
---
=> Initial set of cursor rules

iOS/DuckDuckGo/BlankSnapshotViewController.swift, iOS/DuckDuckGo/MainViewController.swift, iOS/DuckDuckGo/TabsBarViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210454133730706?focus=true
CC:
This fixes a bad conflict resolution after merging hotfix into 7.172.0 release (a6f93c3)
1. Check if there's no regression for #938
---
=> Fix bad hotfix -> release merge

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/DuckDuckGo/Menus/MainMenu.swift, macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift, macOS/DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift, macOS/DuckDuckGo/Sharing/SharingMenu.swift, macOS/DuckDuckGo/Statistics/MoreOptionsMenuPixel.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210459786338668?focus=true
This change adds a number of pixels to measure features discoverability in the More Options Menu
Consult the linked task for the list of pixels that should be fired. Verify that the pixels are firing as expected.
---
=> Add feature discoverability pixels to More Options Menu

iOS/DuckDuckGo/Siri/SiriBubbleView.swift, iOS/DuckDuckGo/ToolbarStateHandling.swift, iOS/DuckDuckGo/Widgets/ControlCenterWidget.swift, macOS/DuckDuckGo/Preferences/View/PreferencesThreatProtectionView.swift, macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210503777847182?focus=true
CC:
This PR fixes Xcode 26 beta compilation.
1. Check that compilation of iOS and macOS clients works in Xcode 16
2. Download the Xcode 26 beta and check that compilation works there too
None, this import change is safe to make
---
=> Fix Xcode 26 beta compilation

iOS/DuckDuckGoTests/MaliciousSiteProtection/MaliciousSiteProtectionDatasetsFetcherTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210472934652739?focus=true
CC:
Disable Flaky tests while finding a solution to avoid CI issues 
1.
2.
---
=> Disable flaky tests that use Expectation class

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift, iOS/DuckDuckGo/MainViewController.swift, iOS/DuckDuckGo/OmniBarDelegate.swift, iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarViewController.swift
=> Handle inputs

macOS/DuckDuckGo/NewTabPage/Features/DefaultSearchActionsHandler.swift, macOS/DuckDuckGo/NewTabPage/NewTabPageActionsManagerExtension.swift, macOS/LocalPackages/NewTabPage/Sources/NewTabPage/Search/NewTabPageDataModel+Search.swift, macOS/LocalPackages/NewTabPage/Sources/NewTabPage/Search/NewTabPageSearchClient.swift, macOS/LocalPackages/NewTabPage/Sources/NewTabPage/Search/NewTabPageSearchModel.swift
=> AI Chat handler

SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/949243614371883/task/1210568913774144?focus=true
CC: @diegoreymendez @graeme 
Hotfix: Resolved an issue on iOS where users could lose access to their subscription unexpectedly.
- Install iOS 7.172.0
- get a subscription
- install the app from this branch
- Subscription is visible and working
Hotfix for a production issue
---
=> isUserAuthenticated Hotfix

.vscode/settings.json, .vscode/tasks.json
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1210549548026817?focus=true
- Fixes incompatible vscode config in settings.json
1. Validate VSCode can clean project with "Sweetpad: Clean" task
2. Validate VSCode build works
No
---
=> Fix vscode settings

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, SharedPackages/BrowserServicesKit/Package.resolved, SharedPackages/BrowserServicesKit/Package.swift, SharedPackages/DataBrokerProtectionCore/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Task/Issue URL: https://app.asana.com/1/137249556945/project/1206594217596623/task/1210128066798037?focus=true
CC: @afterxleep 
Updates C-S-S to version 9.9.0:
- Fixes YouTube links within Duck Player sending user to a blank page
1. Run locally or from a [demo build](https://app.asana.com/1/137249556945/project/1207252092703676/task/1210572366557467?focus=true))
2. Set Duck Player to Always On
3. Play a video on Duck Player
4. Click on the video title or YouTube logo
5. Confirm that new tab opens in YouTube and not Duck Player
---
=> Bump C-S-S to 9.9.0

SharedPackages/BrowserServicesKit/Package.swift, SharedPackages/BrowserServicesKit/Sources/NetworkingTestingUtils/MockOAuthClient.swift, SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift, SharedPackages/BrowserServicesKit/Tests/CrashesTests/CrashLogMessageExtractorTests.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/API/SubscriptionEndpointServiceV2Tests.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+CustomURL.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+Redirect.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/PrivacyProSubscriptionV2IntegrationTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210527222698654?focus=true
CC: @mallexxx @bwaresiak 
- Use a shared referenceDate in CrashLogMessageExtractorTests to avoid flakiness.
- Add PixelKit dependency to the SecureStorageTests target in the package manifest.
---
=> BSK tests improved

.cursor/rules/github-actions.mdc, .cursor/rules/pull-request-creation.mdc
https://app.asana.com/1/137249556945/project/1200194497630846/task/1210592290522867?focus=true
This PR adds comprehensive GitHub Actions workflow management rules and PR creation guidelines to improve developer productivity and prevent common CI/CD issues encountered during workflow automation.
The changes include:
- **GitHub Actions Rules**: Complete reference for all 38 workflows with categorization, CLI pager fixes, branch targeting safety, and agent automation guidelines
- **PR Creation Guidelines**: Updated with username branch naming convention (username/feature-name format) and comprehensive template structure
Test that these natural language requests work correctly with the new rules:
**Workflow Triggering:**
- "run gha notarized build" → Should trigger `macos_build_notarized.yml` …
=> Implement GitHub Actions Rules and PR Guidelines with Username Branch Naming

iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo/ToolbarStateHandling.swift, iOS/DuckDuckGoTests/Toolbar/ToolbarHandlerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/715106103902962/task/1210598884602363?focus=true
CC:
Swaps the bookmarks and passwords icons on the new tab page.
Refactored the code slightly to reduce duplication.
1. Check the bookmarks icon is in the correct place in both legacy and visual updates UI.
not much
* Please check both versions of the UI
n/a
---
=> swap passwords and bookmarks button

macOS/DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser App Store.xcscheme, macOS/DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser.xcscheme
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1210452650078423?focus=true
- disable  test_syncWithAnotherDevicePressed_accountExists_whenExchangeFeatureFlagOff_usesRecoveryCode
1.
2.
---
=> disable flaky sync test

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, SharedPackages/DataBrokerProtectionCore/Package.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/UIWeb/DBPUICommunicationLayer.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/UIWeb/DBPUICommunicationModel.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/UIWeb/DBPUICommunicationModelScanStateExtensions.swift, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo/AppServices/DBPService.swift, iOS/DuckDuckGo/SettingsRootView.swift, iOS/DuckDuckGo/SettingsSubscriptionView.swift, iOS/DuckDuckGo/Subscription/Views/SubscriptionEmailView.swift, iOS/DuckDuckGo/Subscription/Views/SubscriptionFlowView.swift, iOS/DuckDuckGo/Subscription/Views/SubscriptionPIRMoveToDesktopView.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataBrokerProtectionIOSManager.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/UINative/DBPUIViewModel.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/UINative/DataBrokerProtectionViewController.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/DataCaching/DataBrokerProtectionDataManager.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Tests/DataBrokerProtection-macOSTests/DBPUICommunicationLayerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205142657210376/task/1210593346157996?focus=true
CC:
Adds the remainder of the PIR UI, including the entry points, so alpha users can actually use the PIR UI
Also adds a dependency on Swift-Algorithms so we can use uniqued
1. Test on non alpha/debug builds that PIR doesn't show, and it shows the "move to desktop" view
2. Log in to privacy pro and open PIR from settings
3. Save a profile using the onboarding UI
4. Scans should start whilst the app is open, check the dashboard updates appropriately
5. Try editing a profile and check this works correctly
6. Try deleting the profile and check this works
7. Try opening the "FAQ" link at the bottom of the dashboard
---
[Definition of …
=> PIR iOS UI support 3: Add PIR view controller

macOS/UnitTests/UnifiedFeedbackForm/UnifiedFeedbackFormViewModelTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210634650568981?focus=true
1. CI green
---
=> disable flaky test

macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/Debug/DataBaseBrowser/DataBrokerDatabaseBrowserView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1210619058897622?focus=true
CC:
Very simply improves the PIR debug DB browser performance a bit by changing one of the stacks to be lazy
1. Making sure you have a decent amount of PIR data, open the debug db browser and open a table with a lot of data
2. Scrolling performance should now be improved somewhat. Check that it hasn't introduced any layout issues
---
=> Improve macOS PIR DB browser performance

macOS/UnitTests/Permissions/TabPermissionsTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1210006654873574?focus=true
- enable permission tests disabled in #499 and fixed but not enabled in #366
- could not reproduce the flakyness
1. Validate CI is green
---
=> Enable permission tests

iOS/DuckDuckGo/AppServices/DBPService.swift, iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/DataBrokerProtectionIOSManager.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1210640648990407?focus=true
CC:
The values of the compile flags for the #if DEBUG || ALPHA check are inconsistent if done even from a local package
So this just moves them
1. There's not a great way to test this, since if you make an alpha build with Xcode, it worked before the change anyway
2. I've made an ad hoc build from this PR where you can check the PIR UI appears if you like: https://github.com/duckduckgo/apple-browsers/actions/runs/15880201535 (although I've already got Neil to confirm)
--- …
=> PIR iOS: Move feature flagging check outside of local package

macOS/UnitTests/Menus/MoreOptionsMenuTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210671860096867?focus=true
Verify that CI doesn’t fail on paid AI chat tests.
---
=> Disable flaky paid AI Chat tests

macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarPresenter.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210672377843708?focus=true
This change updates the summarization prompt to add more requirements for the output.
1. Enable `aiChatTextSummarization` feature flag.
2. Select some text on a website, open context menu and select “Summarize with Duck.ai"
3. Verify that the new prompt is displayed in the sidebar and that the output matches expectations.
None
—
=> Use a refined prompt for summarization with Duck.ai

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, SharedPackages/BrowserServicesKit/Package.resolved, SharedPackages/BrowserServicesKit/Package.swift, SharedPackages/DataBrokerProtectionCore/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Task/Issue URL: https://app.asana.com/1/137249556945/project/1207252092703676/task/1210699424819073?focus=true
CC:
Fixes a C.S.S issue that could cause Youtube videos to auto-pause in DuckPlayer
1.  Open a few videos in DuckPlayer
2.  Confirm playback works as expected
N/A
---
=> C.S.S Bump for video auto-mute

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210701273845341?focus=true
CC:
This PR tidies up some project file issues:
1. There was an invalid folder reference that can be removed
2. The Autofill version in Package.resolved didn't match the project file, so packages have been resolved and the change has been committed here
None, internal tooling change - the Autofill version was set on the project file so it was being used already
---
=> Project file tidying

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/CCF/DataBrokerProtectionErrors.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/CCF/DataBrokerProtectionFeature.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/CCF/DataBrokerProtectionUtils.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/CCF/WebViewHandler.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Action.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/BrokerProfileJob.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/BrokerProfileJobDependencies.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/QueueManaging/BrokerJobExecutionConfig.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/QueueManaging/BrokerProfileJobQueueManager.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/SubJobWebRunner/BrokerProfileOptOutSubJobWebRunner.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/SubJobWebRunner/BrokerProfileScanSubJobWebRunner.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/SubJobWebRunner/SubJobWebRunner.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BrokerProfileJobActionTests.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionFeatureTests.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/Debug/DataBrokerRunCustomJSONViewModel.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/Debug/DebugScanJob.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205591970852438/task/1210661342132582?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1210669323573932?focus=true
CC:
Timeout handling for scans and opt-outs. 
1. Refer to https://app.asana.com/1/137249556945/project/72649045549333/task/1210698693122550?focus=true
2.
---
=> Background task timeout

iOS/DuckDuckGo/MainViewController.swift, iOS/DuckDuckGo/SettingsRootView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210704949653320
1. Go to debug menu
2. Enable paidAIChat feature flag
3. go to all debug settings -> Set Custom AI Chat URL to https://euw-serp-dev-testing10.duck.co/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
4. Go to Duck.ai and you should see the drop down menu select “Free elegible to subscribe"
5. Go click on the settings icon in the page
6. Test that clicking on "Subscribe to DuckDuck" go and "I have a subscription work"
7. drop down menu select “Subscriber"
8. Go click on the settings icon in the page
9. Test that “Manage Subscription” lead to the subscription setting
<!-- Describe specific scenarios …
=> iOS: fix deeplink

iOS/DuckDuckGo/TabViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/856498667320406/task/1210672892676451?focus=true
CC:
This is complementary to the changes in https://github.com/duckduckgo/apple-browsers/pull/1194
This is actually impossible to trigger with debugger attached, and nearly impossible to trigger in general unless you prolong the operations - so just sanity check for the logic is needed here.
Current setup does not cancel the in flight requests in case of the timeout, assuming it will be extremely rare situation for that handler to be invoked.
--- …
=> Add background assertion for Statistics Loader work triggered by navigation

iOS/DuckDuckGo/TabViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210738986205564?focus=true
CC:
Correctly delegate release of the assertion to main thread so dispatch precondition doesn't fire. 
Test clean install startup.
---
=> Correctly delegate release of the assertion to main thread

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarButtonsView.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210707531805449?focus=true
Adjust padding for text input field
1. Check asana task with the specs
2. Validate if they are implemented
=> Adjust padding

iOS/DuckDuckGo/MainViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210718749358230
Bug introduced by a bad merge
---
=> Merge bug fixed

macOS/UnitTests/Freemium/DBP/FreemiumDBPPromotionViewCoordinatorTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201621708115095/task/1210741697658064?focus=true
Run async tests and await view model updates on main actor.
I ran the full test case locally repeatedly via Xcode (100 times) and it passed.
---
=> Fix flaky Freemium PIR tests

SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionAPIService.swift, SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionEndpointService.swift, SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionEndpointServiceV2.swift, SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/AccountManager.swift, SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift, SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/V1toV2Bridging/SubscriptionAuthV1toV2Bridge.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/API/SubscriptionEndpointServiceV2Tests.swift, SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/AccountManagerTests.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Authentication/DataBrokerProtectionSubscriptionManaging.swift, iOS/DuckDuckGo/AppServices/VPNService.swift, iOS/DuckDuckGo/MainViewController.swift, iOS/DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModel.swift, iOS/DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModelV2.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionAppEvents.swift, macOS/DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift, macOS/DuckDuckGo/NetworkProtection/AppTargets/DeveloperIDTarget/VPNSubscriptionEventsHandler.swift, macOS/DuckDuckGo/Waitlist/VPNFeatureGatekeeper.swift, macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionSettingsModelV1.swift, macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionSettingsModelV2.swift, macOS/UnitTests/DBP/Tests/DataBrokerProtectionFeatureGatekeeperTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1210746879873137
CC:
This PR cherry-picks https://github.com/duckduckgo/apple-browsers/pull/1299 to a hotfix branch.
1. See https://github.com/duckduckgo/apple-browsers/pull/1299
---
=> [Hotfix] Fix v1 entitlements regression

SharedPackages/UIComponents/Sources/UIComponents/iOS/ImageSegmentedPickerView.swift, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/DaxLogoManager.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/DaxLogoManager.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/KeyboardAdjustmentManager.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/NavigationActionBarManager.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/SuggestionTrayManager.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/SwipeContainerManager.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarViewController.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210641337067869?focus=true
Allow users to change chat/search mode by swiping the content area
1. Swipe left and right and check if the state change is being respected
2. Change the state using the toggle at the top to confirm it is still working
3. Test with and without favorites to see if we're displaying them when we should (ie. show favorites when no text is in the suggestion tray)
Broken animation when swiping 
Not setting correct state when swiping
=> Change modes via swipe

macOS/DuckDuckGo/DataImport/Model/DataImportViewModel.swift, macOS/DuckDuckGo/DataImport/View/DataImportErrorView.swift, macOS/DuckDuckGo/DataImport/View/DataImportView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/task/1210732287708280
We've had some reports from internal users that import is failing for some reasons. There appear to be a number of potential causes for this. To narrow them down, it would be useful for internal users to tell us specifically which error(s) they're seeing.
As such, I've made it so that internal users will see a debug panel at the bottom of the import screen whenever an import error is encountered.
1. Install a build from the linked task (not debug; this should work in production builds)
2. [Make yourself an internal user](https://app.asana.com/1/137249556945/project/1202500774821704/task/1205045707803899?focus=true)
3. Go to File -> Import Bookmarks and Passwords
4. Trigger an import error by importing the CSV file …
=> Import debug text

SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/V1toV2Bridging/SubscriptionAuthV1toV2Bridge.swift, iOS/DuckDuckGo/AppServices/SubscriptionService.swift, iOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift, macOS/DuckDuckGo/Application/AppDelegate.swift, macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift, macOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210747547494908?focus=true
CC: @diegoreymendez 
Adding Auth version to the privacyProSubscriptionActive daily pixel for monitoring purposes
---
=> Auth version added to privacyProSubscriptionActive

SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210768120665364 
1. Run the app 
2. open Duck.ai
3. Check no purple warning appears
<!— 
- How does this affect performance?
- What documentation needs updating?
- How does this impact privacy/security?
—>
— …
=> fix main thread warning

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Action.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/CCFResponseParameters.swift, SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/Step.swift, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/BundleResources/valid-broker.json, SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1208671677432066/task/1210743186059311?focus=true
CC:
1. See Asana
---
=> Let macOS ignore the condition step

macOS/LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageProtectionsReportClientTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210774066044351?focus=true
CC:
Remove flaky test, we are doing another tests that check the property is correctly set, so this one can be removed.
Check the CI is green
Nothing
Nothing
Nothing
---
=> Remove flaky test

SharedPackages/BrowserServicesKit/Tests/SyncDataProvidersTests/Settings/SettingsInitialSyncResponseHandlerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210778783882503?focus=true
Verify that CI is green
---
=> Skip flaky Settings sync test

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/NavigationActionBarView.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/NavigationActionBarViewModel.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarHandler.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1210775924411726?focus=true
1. Go to settings -> AI Features -> Enable Search Input
2. Tap the address bar, check if we correctly change the search button to a globe icon if you enter a valid URL
Show the wrong icon on search/duck.ai
=> Use web button when user types an URL

macOS/IntegrationTests/App/WindowManagerStateRestorationTests.swift, macOS/IntegrationTests/Fire/FireTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210770339118156?focus=true
CC:
Fix flaky test `FireTests.testWhenBurnAll_ThenAllWindowsAreClosed`
Green CI
---
=> macOS Use fire visualizer mock in tests

iOS/DuckDuckGo/SettingsSubscriptionView.swift, iOS/DuckDuckGo/SettingsViewModel.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1210733520275433?focus=true
CC:
This PR extracts the `DataBrokerProtectionIOSManager` dependency from `SettingsSubscriptionView` to `SettingsViewModel`. Then `SettingsSubscriptionView` compounds the status indicator logic for the PIR settings item to take the existence of a valid stored profile into consideration.
1. You’ll need to be authenticated with your Privacy Pro account. Launch the debug menu > `Subscription` > `I Have a Subscription` then follow the flow to authenticate.
2. You should see Privacy Pro settings items, but your PIR item should be `off` (you’ll have the entitlement, but no stored profile).
3. Tap the PIR item and follow the flow until you see your scanning results.
4. …
=> Update PIR Status Indicator on Settings Screen to consider stored profiles

macOS/UnitTests/Sync/SyncPreferencesTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1210784449493712?focus=true
This test is flakey. This attempts to stabilise it.
Green CI
---
=> Attempt to stabilise sync test

iOS/Core/PixelEvent.swift, macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift, macOS/PixelDefinitions/pixels/privacy_pro_toolbar_button.json5
Task/Issue URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1210649122070616?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1210649122070619?focus=true
CC: @aataraxiaa 
This PR just defines new Pixels for the upcoming toolbar button upsell. A few things to mention:
* I’m trying to follow the new new process outlined [here](https://app.asana.com/1/137249556945/project/69071770703008/task/1208615048491217?focus=true)
* I also updated `PixelEvent` it made sense to me to do it now, but please let me know if I should do it separately once the triage has finished.
N/A
N/A
N/A
--- …
=> Define Pixels for VPN upsell

.cursor/rules/doc-bot.mdc, CLAUDE.md
Task/Issue URL: N/A
CC:
This updates our Core doc-bot rule to be simpler and use less context.  It also allows futher fine-tuning of the server without needing to manually update anything, and tells the user when the server is not available (but allows to continue), to ensure we are properly enforcing our Global Rules.
---
=> Update doc-bot Core rule

iOS/IntegrationTests/AutoconsentBackgroundTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1210788044594391?focus=true
CC:
Disable flaky `testCosmeticRule` test
Ensure tests are green.
---
=> Disable flaky testCosmeticRule test

macOS/LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageProtectionsReportModelTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210831632709460?focus=true
CC:
1. The CI should be green
Nothing.
Nothing.
I’ve run this tests 1000 times with the repeated tests feature, I didn’t see any ❌, so I hope this fixes it.
---
=> Fix flaky NewTabPage test

iOS/DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.storyboard, iOS/FingerprintingUITests/FingerprintUITest.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210842287122074?focus=true
CC:
Test updated to use accessibility identifier for dismissing the browsing menu
1. Confirm [this workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/16455450704) ran successfully 
=> iOS: Fix failing fingerprinting test

macOS/UITests/UI Tests.xctestplan
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210842472260643?focus=true
Disables a failing UI test.
No test needed beyond the CI going green.
NA
NA
NA
NA
---
=> Disables a failing UI test

iOS/IntegrationTests/AutoconsentBackgroundTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203936086921904/task/1210838938965609?focus=true
CC:
Disable flaky test
Ensure tests are green
Just change to tests
---
=> Disable flaky autoconsent test

macOS/UITests/BookmarkSearchTests.swift, macOS/UITests/FireWindowTests.swift, macOS/UITests/PinnedTabsTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210884830168849?focus=true
CC:
This PR fixes three test files in the macOS UI test suite that are failing consistently.
1. Check that [this workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/16510101770) succeeded
---
=> Fix macOS UI tests

macOS/DuckDuckGo/InfoPlist.xcstrings, macOS/LocalPackages/NewTabPage/Tests/NewTabPageTests/NewTabPageProtectionsReportModelTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210888472737849?focus=true
Always access AsyncStream on MainActor.
---
=> Attempt fixing NewTabPageProtectionsReportModelTests

iOS/DuckDuckGo/ContentBlockingUpdating.swift, iOS/DuckDuckGoTests/ContentBlockingUpdatingTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1210877728312340?focus=true
CC:
Explicitly stop even processing on test conclusion.
Validate tests.
---
=> Content Blocking: Stop updates processing once test is concluded

iOS/PixelDefinitions/pixels/vpn_sub_access_revoked_pixels.json5, iOS/PixelDefinitions/pixels/vpn_sub_client_check_pixels.json5, iOS/PixelDefinitions/pixels/vpn_sub_notification_pixels.json5, iOS/PixelDefinitions/suffixes_dictionary.json5, macOS/PixelDefinitions/pixels/vpn_sub_access_revoked_pixels.json5, macOS/PixelDefinitions/pixels/vpn_sub_client_check_pixels.json5, macOS/PixelDefinitions/pixels/vpn_sub_notification_pixels.json5, macOS/PixelDefinitions/suffixes_dictionary.json5
Task/Issue URL: https://app.asana.com/1/137249556945/project/1206580121312550/task/1210825058136480?focus=true
Add pixel documentation for pixels added during the AuthV2 rollout project.
Just make sure the pixels match [the list in this task](https://app.asana.com/1/137249556945/project/1206580121312550/task/1210825058136480?focus=true).
None
NA
NA
NA
---
=> Add pixel documentation

iOS/DuckDuckGo/UserText.swift, iOS/DuckDuckGo/en.lproj/Localizable.strings
Task/Issue URL: https://app.asana.com/1/137249556945/project/392891325557410/task/1210943550155226?focus=true
CC:
Updates setting name of search input feature
1. Visit settings and check that the copy for the search input toggle matches the copy in the above task
---
=> [iOS][Search input] Update search input name in settings

macOS/Configuration/Tests/TestsServer.xcconfig
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210968881736360?focus=true
CC:
This PR fixes the test-server being embedded in apps that aren't intended to include it.
1. Check that [this workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/16731283724) succeeded
---
=> Fix test server being embedded in review & release targets

SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/contentScope.js, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/contentScopeIsolated.js, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/dist/index.css, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/dist/index.js, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/de/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/en/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/es/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/fr/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/it/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/nl/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/pl/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/pt/new-tab.json, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/locales/ru/new-tab.json, macOS/DuckDuckGo/InfoPlist.xcstrings, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210512075550473?focus=true
C-S-S 11.2.0
1. Make sure tests pass
---
=> C-S-S 11.3.0

.github/workflows/pixel_validation.yml, iOS/PixelDefinitions/pixels/autoconsent.json5
Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210957466937460?focus=true
CC:
Ditto
Check CI run from a commit where linting error was introduced: see how the pixel validation displays a diff of the needed fix
---
=> Show diff when pixel linter fails

macOS/Configuration/Tests/TestsServer.xcconfig
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210981198368268?focus=true
CC:
This PR fixes alpha builds the same way that we fixed release and review builds earlier in the week.
1. Run `./scripts/archive.sh alpha` and check that the build succeeds - notarized might fail but that's fine, you just need to make sure that the archive itself works
---
=> Fix macOS alpha builds

macOS/DuckDuckGo/NavigationBar/View/MenuItemWithBadge.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1206488453854252/task/1210882329335755?focus=true
Based on design feedback we will constrain the Subscription ’Try for Free’ badge to 16px in height, and also lower it one point.
1. Just Green CI (This has already been viewed and approved by design [here](https://app.asana.com/1/137249556945/task/1210882329335755/comment/1210977864688373?focus=true))
Low
---
=> macOS: Minor Changes to ‘Try for Free’ Promotional Badge UI

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj, macOS/UnitTests/Connectivity/HotspotDetectionServiceTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1210977392844642?focus=true
- remove `tests-server` dependency (was used to simulate captive portal build in `DEBUG`
1. Validate CI is green
---
=> remove tests-server dep; fix flaky hotspot test

macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210978328805284?focus=true
- fixes address bar tabViewModel reset on window minimize
1. Open couple of tabs
2. Minimize window
3. Restore window
4. Validate address bar reacts to tab switching
---
=> Fix address bar tab view model reset

SharedPackages/VPN/Sources/VPN/ExtensionMessage/ExtensionRequest.swift, SharedPackages/VPN/Sources/VPN/NetworkProtectionDebugLogCollector.swift, SharedPackages/VPN/Sources/VPN/PacketTunnelProvider.swift, iOS/Configuration/Configuration-Alpha.xcconfig, iOS/Configuration/Configuration.xcconfig, iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj, iOS/DuckDuckGo/Debug.storyboard, iOS/DuckDuckGo/Info.plist, iOS/DuckDuckGo/NetworkProtectionDebugUtilities.swift, iOS/DuckDuckGo/NetworkProtectionDebugViewController.swift, iOS/DuckDuckGo/NetworkProtectionLogManager.swift, iOS/DuckDuckGo/NetworkProtectionLogViewerViewController.swift, iOS/PacketTunnelProvider/Info.plist, macOS/DuckDuckGoVPN/TunnelControllerIPCService.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1211018143619849?focus=true
CC:
This PR adds a log viewer option for the iOS VPN.
1. Sign into Privacy Pro and start the VPN
2. Go to the Debug menu -> VPN -> Create Log Snapshot
3. Wait a minute
4. Tap "View Log Snapshots" and check that your logs were saved, and that you can export them via a Share Sheet
---
=> iOS VPN log viewer

SharedPackages/BrowserServicesKit/Tests/SyncDataProvidersTests/Settings/helpers/TestSettingSyncHandler.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1211005120804619?focus=true
This change removes main queue dispatch from TestSettingSyncHandler to stabilize unit tests.
Verify that BSK tests are green.
---
=> Fix Settings Sync tests

.claude/settings.json, doc-bot/development-commands.md
Updates the doc-bot development-commands.md documentation to include comprehensive build command metadata and variables.
**Scope**: Documentation update only - no code changes
**Testing**: 
- Updated `development-commands.md` to include comprehensive build command templates with variable placeholders
- Added detailed tables showing how to obtain dynamic values (workspace path, simulator IDs, CPU cores, architecture)
- Included concrete examples with actual values for both iOS and macOS builds
- Added environment detection script to automatically determine build parameters
- Set as `alwaysApply: true` so agents always use these standardized commands
This ensures agents have all necessary metadata to correctly build the app regardless of the specific user setup, simulator availability, or …
=> Update doc-bot build commands documentation

.github/actions/ios-simulator-logs/action.yml, .github/actions/select-ios-simulator/action.yml, .github/workflows/bsk_pr_checks.yml, .github/workflows/dbp_pr_checks.yml, .github/workflows/ios_end_to_end.yml, .github/workflows/ios_nightly.yml, .github/workflows/ios_pr_checks.yml, .github/workflows/ios_sync_end_to_end.yml
Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1211034038467055?focus=true
CC:
This PR adds a new action for checking simulator versions in order of preference, in cases where the GitHub Actions runner is in the process of rolling out.
---
=> Allow dynamically looking up the iOS simulator version

macOS/DBPE2ETests/DBPEndToEndTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1211066069009959?focus=true
CC:
This PR re-enables PIR E2E tests, but changes them to no longer run on every PR (for now) until their failures can be figured out.
1. TODO
---
=> Re-enable PIR tests

.claude/settings.json
Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1211086831638596?focus=true
CC:
This PR fixes Claude Code settings.
1. Check out this branch and launch `claude`
2. Check that you don't get a syntax error
---
=> Add a missing comma to the Claude settings

iOS/DuckDuckGo/SettingsAIChatShortcutsView.swift, iOS/DuckDuckGo/SettingsAIFeaturesView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1210947754188321/task/1210625450193838?focus=true
The goal of this task is to show the Voice Search toggle conditionally, based on the Private Voice Search setting.
The `AI Features` screen is behind the feature flag (`isUpdatedAIFeaturesSettingsEnabled`) hence two different recordings.
1. Open Settings, tap on Enable Voice Search
2. Turn on `Private Voice Search`
3. Navigate back and then tap on `AI Features`
4. `Voice Search` should be visible ✅ 
5. Go back to `Enable Voice Search` menu, disable `Private Voice Search`
6. After navigating to `AI Features`, `Voice Search` toggle is not visible ✅
<details>
<summary>Click to see a video</summary>
https://github.com/user-attachments/assets/e178c918-d0e6-4eeb-a097-0aca5afa662a …
=> Show Voice Search shortcut conditionally

macOS/UITests/ContentScopeExperimentsEndToEndTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1211098252598950?focus=true
1. Run testContentScopeExperiments in  ContentScopeExperimentsEndToEndTests or check https://github.com/duckduckgo/apple-browsers/actions/runs/17094356605 passes
---
=> Fix Content Scope Script Experiment e2e test

SharedPackages/BrowserServicesKit/Tests/DDGSyncTests/Mocks/Mocks.swift, SharedPackages/BrowserServicesKit/Tests/DDGSyncTests/SyncConnectionControllerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1209960400666984?focus=true
A test was flaking for what transpired to be an understandable reason. This should stabilise it.
1. Green CI
2. If you want to be really thorough, you can try running the updated test 5000 times.
None: Tests
---
=> Wait for actual callback being tested

iOS/DuckDuckGo/bg.lproj/Localizable.strings, iOS/DuckDuckGo/cs.lproj/Localizable.strings, iOS/DuckDuckGo/da.lproj/Localizable.strings, iOS/DuckDuckGo/de.lproj/Localizable.strings, iOS/DuckDuckGo/el.lproj/Localizable.strings, iOS/DuckDuckGo/es.lproj/Localizable.strings, iOS/DuckDuckGo/et.lproj/Localizable.strings, iOS/DuckDuckGo/fi.lproj/Localizable.strings, iOS/DuckDuckGo/fr.lproj/Localizable.strings, iOS/DuckDuckGo/hr.lproj/Localizable.strings, iOS/DuckDuckGo/hu.lproj/Localizable.strings, iOS/DuckDuckGo/it.lproj/Localizable.strings, iOS/DuckDuckGo/lt.lproj/Localizable.strings, iOS/DuckDuckGo/lv.lproj/Localizable.strings, iOS/DuckDuckGo/nb.lproj/Localizable.strings, iOS/DuckDuckGo/nl.lproj/Localizable.strings, iOS/DuckDuckGo/pl.lproj/Localizable.strings, iOS/DuckDuckGo/pt.lproj/Localizable.strings, iOS/DuckDuckGo/ro.lproj/Localizable.strings, iOS/DuckDuckGo/ru.lproj/Localizable.strings, iOS/DuckDuckGo/sk.lproj/Localizable.strings, iOS/DuckDuckGo/sl.lproj/Localizable.strings, iOS/DuckDuckGo/sv.lproj/Localizable.strings, iOS/DuckDuckGo/tr.lproj/Localizable.strings, iOS/PacketTunnelProvider/it.lproj/Localizable.strings
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1211067369798223?focus=true
Add translations for AI Features settings
1.  Check AI Features settings
=> Add translations for AI Features settings

iOS/Core/FeatureFlag.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1211102788891675?focus=true
Flip feature flag for new AI Features settings page
1. Make sure you're NOT an internal user
2. Go to Settings -> AI Features
3. Check if the experimental bar picker uses a pictogram instead of a normal table cell
=> Flip feature flag for new AI Features settings page

SharedPackages/BrowserServicesKit/Sources/Common/DevicePlatform.swift, SharedPackages/BrowserServicesKit/Tests/CommonTests/DevicePlatformTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211096340359444?focus=true
CC:
This PR adds device cases to `DevicePlatform` for macOS and iOS, and handles unsupported platforms with an `unknown` case. I considered `fatalError`in here instead, but would prefer to see `unknown` in any instrumentation involved and investigate.
1. Check that tests look good
---
=> Add enum cases to `DevicePlatform`

macOS/UnitTests/Configuration/ConfigurationManagerTests.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1211134757129530?focus=true
1. CI is green
---
=> fix flaky test

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift, macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211211991091697
This change adds pageContext subfeature (disabled at the moment).
Launch the app and verify that page context is not available.
---
=> Add page context subfeature

macOS/DuckDuckGo/Preferences/View/PreferencesRootView.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211216212509882?focus=true
CC:
This PR adds an offer screen impression pixel to the macOS preferences view.
1. Open the app and sign out of Privacy Pro
2. Open settings and click `Get Privacy Pro`
3. Confirm that you get an `offer_screen_impression` pixel in the console
---
=> Update offer screen pixels

macOS/DuckDuckGo/Application/AppDelegate.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1206580121312550/task/1211224050332977?focus=true
Fix a crash on launch in debug and alpha builds
Just run the app and make sure it doesn't crash.  Whether extensions work or not is irrelevant since they're internal at this point, and any issues will be explored separately.
LOW: only changing the initialization for an internal feature.
Nothing I can think of.
NA
NA
---
=> Fix a crash on launch in debug and alpha builds

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Authentication/DataBrokerProtectionSubscriptionManaging.swift, macOS/DBPE2ETests/DBPEndToEndTests.swift, macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/Utils/DataBrokerProtectionAgentStopper.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1211305857269378?focus=true
CC:
Some logging improvements to PIR e2e tests to improve debuggability. Includes removing initial login item setup since it will be stopped immediately and confuse the logs
1. Smoke test PIR
2.
---
=> PIR: macOS e2e tests logging improvements

iOS/Gemfile.lock, iOS/fastlane/Pluginfile, macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, macOS/Gemfile.lock, macOS/fastlane/Pluginfile
Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1211354468416267?focus=true
This change pulls in fastlane automation plugin v3.1.0 containing a fix for handling inaccessible tasks in git log.
See https://github.com/duckduckgo/fastlane-plugin-ddg_apple_automation/pull/57
---
=> Filter out inaccessible tasks when populating changes included in the release

SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/contentScope.js, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/dist/index.css, SharedPackages/BrowserServicesKit/Sources/ContentScopeScripts/Resources/pages/new-tab/dist/index.js, package-lock.json, package.json
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201520793593668/task/1211363020741540?focus=true
CC:
Updates C-S-S which includes fixes for telemetry and the enter button.
1. For internal users only:
2. Ensure that telemetry is sent from the sidebar when the user clicks 'enter'
---
=> Update to C-S-S 11.16.0

iOS/DuckDuckGo/UserText.swift, iOS/DuckDuckGo/bg.lproj/Localizable.strings, iOS/DuckDuckGo/cs.lproj/Localizable.strings, iOS/DuckDuckGo/da.lproj/Localizable.strings, iOS/DuckDuckGo/de.lproj/Localizable.strings, iOS/DuckDuckGo/el.lproj/Localizable.strings, iOS/DuckDuckGo/en.lproj/Localizable.strings, iOS/DuckDuckGo/es.lproj/Localizable.strings, iOS/DuckDuckGo/et.lproj/Localizable.strings, iOS/DuckDuckGo/fi.lproj/Localizable.strings, iOS/DuckDuckGo/fr.lproj/Localizable.strings, iOS/DuckDuckGo/hr.lproj/Localizable.strings, iOS/DuckDuckGo/hu.lproj/Localizable.strings, iOS/DuckDuckGo/it.lproj/Localizable.strings, iOS/DuckDuckGo/lt.lproj/Localizable.strings, iOS/DuckDuckGo/lv.lproj/Localizable.strings, iOS/DuckDuckGo/nb.lproj/Localizable.strings, iOS/DuckDuckGo/nl.lproj/Localizable.strings, iOS/DuckDuckGo/pl.lproj/Localizable.strings, iOS/DuckDuckGo/pt.lproj/Localizable.strings, iOS/DuckDuckGo/ro.lproj/Localizable.strings, iOS/DuckDuckGo/ru.lproj/Localizable.strings, iOS/DuckDuckGo/sk.lproj/Localizable.strings, iOS/DuckDuckGo/sl.lproj/Localizable.strings, iOS/DuckDuckGo/sv.lproj/Localizable.strings, iOS/DuckDuckGo/tr.lproj/Localizable.strings
Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211114425558999?focus=true
CC:
Update placeholder copy to -Ask privately-
1. Turn on the duck.ai address bar
2. Check if the placeholder says "Ask privately"
N/A
=> Update placeholder copy to -Ask privately-

iOS/Core/FeatureFlag.swift, iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift, iOS/DuckDuckGo/DefaultOmniBarViewController.swift, iOS/DuckDuckGo/MainViewController.swift
Task/Issue URL: https://app.asana.com/1/137249556945/task/1211381850858631?focus=true
CC:
Remove internal flag and enable the landscape improvement for public with new release.
1. Verify landscape improvement is working as expected for new Search Input (https://github.com/duckduckgo/apple-browsers/pull/1943)
---
=> Remove temporary landscape mode internal flag

iOS/DuckDuckGo/SyncRecoveryPrompt/SyncRecoveryPromptService.swift
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201011656765697/task/1211453809473867?focus=true
Remove code that was commented out
1. This was already tested in other PRs to test the integration with this screen and the duck.ai force-choice screen
---
=> Remove code comment

.maestro/release_tests/password-authentication.yaml, .maestro/release_tests/password-management.yaml
Task/Issue URL: https://app.asana.com/1/137249556945/project/1201462886803403/task/1211519180934305?focus=true
CC:
Fixes failing maestro tests that suddenly & randomly stopped liking `index: 1`
1. Confirm tests under `End to end Tests (release, ipad, iPhone-16, iPhone)` have all passed ([link](https://github.com/duckduckgo/apple-browsers/actions/runs/18195989962/job/51803548495))
=> Fix failing maestro release tests
