duckduckgo/apple-browsers

iOS/DuckDuckGo/SwipeTabsCoordinator.swift

Task/Issue URL: https://app.asana.com/0/392891325557410/1209397835075918
CC:
**Description**:
Ensure that the target row is less than the number of items in the collection at this point and assert if not.
**Steps to test this PR**:
Smoke testing of opening, swiping between and managing tabs:
1. Add a bunch of tabs, swipe between them. 
2. Close tabs, swipe between remaining tabs
3. Repeat with different combinations of single tab, multiple tabs.
**Definition of Done**:

(iOS) Prevent swipe coordinator crash

---

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj

Task/Issue URL: https://app.asana.com/0/1199333091098016/1209429232862986
CC:
This PR fixes ATB UI test compilation.
1. Check that ATB UI tests compile locally
---

Fix ATB UI test compilation

---

iOS/Core/InternalUserStore.swift

Task/Issue URL: https://app.asana.com/0/1204167627774280/1209432030981303
Set alpha builds internal by default
1. Run both alpha and release configurations on a clean install
2. Make sure alpha builds are set as internal by default and release builds aren't
3. You can also check [these builds](https://app.asana.com/0/0/1209432035885355/f) to validate
Low: Release builds should not be set as internal by default.

Set alpha build as internal by default

---

BrowserServicesKit/Package.swift
macOS/LocalPackages/DataBrokerProtectionShared/Package.swift

Task/Issue URL: https://app.asana.com/0/1193060753475688/1209428043078885
CC:
This PR fixes some Swift package warnings with PixelExperimentKit and DataBrokerProtectionShared.
In both cases, the packages were trying to include a Resources directory that doesn't exist - it looks like a copy-paste error with the package configuration, so I've removed those includes.
1. Clean DerivedData
2. Build the macOS and iOS targets locally
3. Check that there is no ⚠️ icon beside any Swift packages in the Xcode sidebar
None
The main risk is that these includes were actually needed, but Xcode is giving us these warnings because it has no files found at the given paths. Also, I checked each of the affected packages and they have no `Resources` directories, so we're safe to remove these. …

Fix Swift package missing resource warnings

---

macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift

Task/Issue URL: https://app.asana.com/0/0/1209434873980812
We received the following feedback:
> Just now I was trying to drag a tab out of the window and even if I brought it to the very tippy top of my screen (see screenshot) it would just bounce back into the existing window. I had to make the window smaller. It just seems unnecessary. Do we have control over this? 
> I notice on Chrome it’s waaaaaaay more responsive — as soon as I pulled a tab several pixels upward it created a new window.
To address this I’ve implemented the following:
* Added a check for `isDroppedAboveTabBar` that triggers when the drop point is more than 10 points above the tab bar
* Now we will create a new window if either:
** The tab is dropped above the tab bar (new condition)
** The tab is dropped far away …

Update Condition for Creating a New Window from a Dragged Tab

---

BrowserServicesKit/Sources/PixelExperimentKit/TDSOverrideExperimentMetrics.swift
iOS/DuckDuckGo/AppPageRefreshMonitor.swift
iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift
iOS/DuckDuckGo/TabViewControllerBrowsingMenuExtension.swift

Task/Issue URL: https://app.asana.com/0/1204186595873227/1209454650312256
---

update metrics windows

---

iOS/DuckDuckGo/DuckPlayer/DuckPlayer.swift

Task/Issue URL: https://app.asana.com/0/1207252092703676/1209403718901685/f
CC:
The URL and tab bar were dissapearing when switching to landscape mode in the new tab page after watching a video in DuckPlayer.
Since the “New Tab” page is not actually a “tab”, DuckPlayer orientation handler was still active, causing the issue.
1. Search 'metallica' on SERP and select 'Videos' from navigation
2. Select any video to play in DuckPlayer and rotate phone to landscape
3. Check if URL and tab bar hide automatically
4. Return to Portrait mode
5. Add a new tab
6. Rotate to landscape while on new tab
7. Verify URL and tab bar are visible (do not hide)
Low: Fixes minor issue
N/A
N/A
— …

[iOS] DuckPlayer: Fix issue with landscape mode + new tab

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/0/414709148257752/1209463640725362
CC:
Makes sure automatically selected tab is populated before transitioning back to the TabViewController.
1. Open a bunch of tabs, close an restart the app
2. Go to tab switcher and close currently selected tab, note newly selected tab
3. Press done
4. Check newly selected tab is now visible.
---

Pre-populate current tab after closing other tab

---

iOS/DuckDuckGo/Base.lproj/TabSwitcher.storyboard

Task/Issue URL: https://app.asana.com/0/414709148257752/1209484209211269
CC: @amddg44 
1. Open a few web pages (imdb is good)
2. Open the tab switcher
3. Check the title extends to the close button (with some padding)
Low: minor visual change.
Not much
This is a fix for the title length
Just the tab switcher.

fix tab switcher layout so that the title isn't too short

---

BrowserServicesKit/Package.resolved
BrowserServicesKit/Package.swift

Task/Issue URL: https://app.asana.com/0/1209465117664031/1209465117664031
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.2
Apple PR: 
Updates Autofill to version [16.2.2](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/16.2.2).
* chore: update actions cache to v3 by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/759
* Update Apple project file references in the release workflow by @samsymons in https://github.com/duckduckgo/duckduckgo-autofill/pull/758
* Update release workflow to support Apple monorepo by @samsymons in https://github.com/duckduckgo/duckduckgo-autofill/pull/756
* [Formatters] Make fixes for credentials less restrictive by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/763
* …

Update autofill to 16.2.2

---

iOS/DuckDuckGo/LaunchOptionsHandler.swift
iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingIntroViewModel.swift
iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingView.swift
iOS/DuckDuckGo/UserText.swift

Task/Issue URL: https://app.asana.com/0/1206226850447395/1209483939027886
CC: @alessandroboron 
1. Check button does not show up on production build
2. Check onboarding can be skipped using the button on a clean install.
Button becomes visible on production build, allowing users to skip onboarding.
---

Add skip onboarding button for Debug and Alpha builds

---

BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
iOS/Core/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/0/0/1208706841336532
Add Privacy Pro Onboarding CTA Experiment Feature Flag, which will be used on iOS
1. Green CI
Experimental feature availability
---

Add Privacy Pro Onboarding CTA feature flag

---

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/AlertPlaygroundView.swift
iOS/DuckDuckGo/DebugScreensViewModel+Screens.swift

Task/Issue URL: https://app.asana.com/0/392891325557410/1209499866654334
CC:
Adds alert playground to the debug screen.
1. Go to the debug screen
2. Tap on Alerts Playground
3. Have a play!
None
Not much
N/A
N/A

[iOS] Add alerts playground to debug screen

---

.github/workflows/macos_pr_checks.yml
macOS/IntegrationTests/Tab/AddressBarTests.swift

Task/Issue URL: https://app.asana.com/0/1199333091098016/1209505008661892
CC:
This PR fixes the paths used by the macOS PR checks workflow when attaching failed test run artifacts.
1. Check that this workflow run contains a list of attached artifacts, like an xcresult file: https://github.com/duckduckgo/apple-browsers/actions/runs/13535222202?pr=105
---

Fix paths used when attaching macOS failed CI run artifacts

---

BrowserServicesKit/Sources/UserScript/UserScriptMessaging.swift
BrowserServicesKit/Tests/UserScriptTests/UserScriptMessagingTests.swift
iOS/DuckDuckGo/Subscription/UserScripts/IdentityTheftRestorationPagesFeature.swift
iOS/DuckDuckGo/Subscription/UserScripts/SubscriptionPagesUseSubscriptionFeature.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/IdentityTheftRestorationPagesUserScript.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift

Task/Issue URL: https://app.asana.com/0/72649045549333/1207974891378353
When creating HostnameMatchingRule also include port number along with the hostname.
1. Following testing steps in https://app.asana.com/0/0/1209495545684681 define a custom URL with a port number e.g. "http://localhost:1234/subs" 
2. Restart the app
3. Set a breakpoint in the init of SubscriptionPagesUseSubscriptionFeature
4. Open purchase page
5. When execution stops at the breakpoint print out "messageOriginPolicy" and confirm that the port number is included in the rule
High: Could affect user privacy, lose user data, break core functionality
Mistake in generating proper "messageOriginPolicy" matching the page URL can result in subscription pages now working (redirect to SERP), including the paywall.
--- …

When creating HostnameMatchingRule also include port number

---

macOS/LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/SwiftUI/MenuItemButton.swift
macOS/LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionUI/Views/StatusView/NetworkProtectionStatusView.swift

Task/Issue URL: https://app.asana.com/0/1203108348835387/1209463463956054
Fixes the coloring for the VPN Status View's exclusion menu item.  The detail color was off when hovered.
Also cleans up the code a bit.
The following screenshot shows the coloring issue:
1. Run target "macOS VPN Agent"
2. Make sure the detail (ie: the count) in the exclusion menu items becomes white when hovered in both light and dark mode.
Low impact and the only identified risk is coloring issues - which we already have.
Nothing I can think of.
Nothing I can think of.
Just make sure the code changes make sense since there's a small refactoring here.
---
[Definition of …

Fixes the color of VPN exclusion details in the VPN Status View menus

---

macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift

Task/Issue URL: https://app.asana.com/0/1204167627774280/1209550650690084
Do not show AI Chat menu bar icon in popup window
1. Enable AI Chat in the browser navigation bar (Right click, show duck.ai)
2. Open a pop-up window on Debug -> UI Trigger Show popup window
3. Make sure AI Chat icon is not visible
Low: Minor visual changes
Hide the icon on the main window when it shouldn't

Do not show AI Chat in popup window

---

iOS/Widgets/QuickActionsSmallWidget.swift

Task/Issue URL: https://app.asana.com/0/0/1209568442838954/f
Update the widget name to avoid iOS issue updating widgets
1. Install the 7.159.0 release on your device (or install it from the app store)
2. Add the Quick Shortcuts widget to your homescreen
3. Install the app using this PR, check if the widget is still working
Medium: Change of breaking the widget and the user having to re-add it

Update widget name

---

macOS/DuckDuckGo/Application/AppDelegate.swift

Task/Issue URL:https://app.asana.com/0/1204006570077678/1209486069724547
CC:
The blue notification dot in the more options menu was shown in a fresh install. The problem was that the blue dot was checking if two days had passed since the `firstLaunchDate`, but for new users, the `DockCustomizer` was being created before its initialization, and the default value of it was a month ago, causing the check to return true.
The fix moves the initialization of the `DockCustomizer` just after the `firstLaunchDate` is initialized.
1. Run `./clean-app.sh debug` to set the state as fresh
2. Run the application
3. The blue dot shouldn’t be present
4. Go to the `DockCustomizer` class and in the `startTimer` function, reduce the timer from `12 * 60 * 60`, to just one. This is just to …

Initialize dock customizer after first launch date is set

---

iOS/DuckDuckGo/TabInteractionStateDiskSource.swift

Task/Issue URL: https://app.asana.com/0/1206226850447395/1209362951077123
CC:
We've been getting a decent amount of web view interaction state write errors with error code 83 (Value too large to be stored in data type). Adding the size of to-be-written data as a parameter to check for unexpectedly large Data instances.
1. Change `tabCacheLocation` in `TabInteractionStateDiskSource` line 74 to unwritable path, e.g. `let tabCacheLocation = URL("///failingPath.json")!`
2. Run the app and browse to any site.
3. Check if data size attribute is added to error pixel.
N/A
N/A
---
[Definition of …

Append error parameter when interaction state write fails

---

BrowserServicesKit/Sources/Subscription/Managers/SubscriptionAuthV1toV2Bridge.swift
BrowserServicesKit/Sources/SubscriptionTestingUtilities/Managers/SubscriptionManagerMock.swift
BrowserServicesKit/Sources/SubscriptionTestingUtilities/Managers/SubscriptionManagerMockV2.swift
iOS/DuckDuckGo/AppServices/VPNService.swift
iOS/DuckDuckGo/Feedback/VPNMetadataCollector.swift
iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/SettingsViewModel.swift
iOS/DuckDuckGo/UICoordination/MainCoordinator.swift

Task/Issue URL: https://app.asana.com/0/1201011656765697/1208864390316201
CC: @Bunn @samsymons @miasma13 
Fix for a bug introduced in https://app.asana.com/0/1205842942115003/1209170372758738 where a failure to fetch the subscription entitlements was treated as the user not having the entitlements at all.
1. Install 7.160.0
2. Subscribe to Privacy pro and enable VPN
3. Install this fix on top
4. Check that subscription is still available and the VPN is still enabled
1. Enable VPN
2. Click on the vpn widget for disabling the VPN
3. All should work as expected
1. Disable VPN
2. Click on the vpn widget for enabling the VPN
3. All should work as expected
High, we could log out the Subscription Pro users
- User can be logged out from Subscription Pro
- The VPN could be disconnected
- We could …

(7.160.0) VPN Entitlement check fix

---

iOS/DuckDuckGo/pl.lproj/Localizable.strings
iOS/DuckDuckGo/sk.lproj/Localizable.strings
iOS/DuckDuckGo/sl.lproj/Localizable.strings

Task/Issue URL: https://app.asana.com/0/1202926619870900/1209568801640823
Some of the link markup on strings added during #61 are badly formed - a space between the square brackets and round brackets will break it. This PR fixes that.
1. Can test the specific languages by going to the About screen and checking the links, but it should really work with this small change.
Broken links on About screen
Additional unspotted issue with translations
---

Fix messed up localizable MD format

---

macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/0/1207603085593419/1209598255904210
App exclusions is still internal and should have been published.
Just make sure that you see the App Exclusions UI in settings after removing your internal user state.
None.
This feature has been available internally for a while and there haven't been issues.
None.
Ideally I'd like to push this today so it's included in tomorrow's internal build and released monday.
--- …

Published VPN app exclusions, which were disabled by mistake

---

iOS/Core/PixelEvent.swift

Task/Issue URL: https://app.asana.com/0/1203936086921904/1209499063210750
CC:
We noticed that the 2 Privacy Pro pixels are badly reported due to having their values switched.
[iOS only]
Since it may be hard to reproduce real error cases to test the pixels, in `SubscriptionPagesUseSubscriptionFeature` you can add to one of the methods a forced `setTransactionError(...)` call that should trigger the pixel being sent.
1. Ensure that for `setTransactionError(.accountCreationFailed)` error a `.privacyProPurchaseFailureAccountNotCreated` pixel is being fired with a value of `m_privacy-pro_app_subscription-purchase_failure_account-creation`
3. Ensure that for `setTransactionError(.missingEntitlements)` error a `.privacyProPurchaseFailureBackendError` pixel is being fired with a value of …

iOS: Fix pixel values for subscription related errors

---

macOS/DuckDuckGo/MainWindow/MainViewController.swift

Task/Issue URL: https://app.asana.com/0/1201899738287924/1209532040383733
This change simplifies the logic of displaying Dax logo next to the address bar
by removing dead code of the Big Search Box experiment.
1. Launch the app and verify that Dax logo is shown next to the address bar while on NTP.
2. Open new tab and verify that it shows Dax logo
3. Open new window and verify that it shows Dax logo
4. Open new Fire Window and verify that it shows Dax logo
Low
Big Search Box was part of native NTP which is no more displayed, so we can safely remove it (the full native NTP code removal is still due).
N/A
N/A
—
[Definition of …

Fix displaying Dax logo in new window

---

macOS/UITests/Common/UITests.swift
macOS/UITests/FindInPageTests.swift

Task/Issue URL: https://app.asana.com/0/1201037661562251/1209624775880991
This change improves checking for search status field value by awaiting the actual value, not the field visibility.
Verify that Find in Page tests pass in [this UI tests](https://github.com/duckduckgo/apple-browsers/actions/runs/13760652904) run.
---

Fix Find in Page UI tests

---

macOS/DuckDuckGo/Tab/Model/TabContent.swift

Task/Issue URL: https://app.asana.com/0/1201048563534612/1209628040657468
1. Launch the app
2. Open Bookmarks Manager
3. Open Settings
4. Verify that you can’t bookmark either of the two tabs via tab context menu or Main Menu -> Bookmarks -> Bookmark This Page.
Not much, it’s a straightforward change.
This doesn’t affect `canBookmarkAllOpenTabs` logic as it checks canBeBookmarked so will return proper result for the “Bookmark All Open Tabs” action.
—
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | …

Disable bookmarking Bookmarks and Settings pages

---

macOS/DuckDuckGo/Sharing/SharingMenu.swift

Task/Issue URL: https://app.asana.com/0/1201048563534612/1209580911916105
- Fix opening System Sharing preferences on macOS 15
1. Open a tab, navigate somewhere
2. Click “⋮” menu -> Share -> More… item
3. Validate System Sharing Settings is opened
---

Fix sharing preferences on macOS 15

---

iOS/Core/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/0/392891325557410/1209568168593153
CC:
Makes the feature flag for tab switcher changes remote confurable.
1. Open a few tabs
1. Check tabManager -> multiSelection feature is set to minimum supported 7.160.0 in https://jsonblob.com/1348616393872039936 (if not, change it)
2. Then using debug screen, update the privacy config to use the json: https://jsonblob.com/api/jsonBlob/1348616393872039936
3. Open tab switcher - it should be enabled (edit button present)
4. Update the above JSON Blob and set the the minimum supported to 7.161.0 
5. Reload the config via the debug screen
6. Open tab switcher - it should be disabled (edit button not visible)
Medium
Could accidentally enable this feature before the main release where it is completed. …

make tab switcher remote switchable

---

BrowserServicesKit/Package.resolved
BrowserServicesKit/Package.swift
BrowserServicesKit/Sources/BrowserServicesKit/Autofill/AutofillUserScript+SourceProvider.swift
DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/Autofill/ContentOverlayViewController.swift

Task/Issue URL: https://app.asana.com/0/1209632498809625/1209632498809625
Autofill Release: https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/17.0.0
Apple PR: 
Updates Autofill to version [17.0.0](https://github.com/duckduckgo/duckduckgo-autofill/releases/tag/17.0.0).
* [Workflow] Upgrade ubunutu in workflows by @dbajpeyi in https://github.com/duckduckgo/duckduckgo-autofill/pull/767
* Update password-related json files (2025-03-05) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/768
* Update password-related json files (2025-03-07) by @daxmobile in https://github.com/duckduckgo/duckduckgo-autofill/pull/771
* build: drop apple-specific assets by @shakyShane in https://github.com/duckduckgo/duckduckgo-autofill/pull/772
* build: migrate to esbuild by …

Update autofill to 17.0.0

---

iOS/DuckDuckGo/Base.lproj/TabSwitcher.storyboard
iOS/DuckDuckGo/TabSwitcherViewController+MultiSelect.swift

Task/Issue URL: https://app.asana.com/0/72649045549333/1209647050352109
CC:
Fixes a bug where the collection view wasn't using the full space on iPad.
1. Check the tab manager collection view uses the full size of the view on iPad
2. Check the tab manager collection view respects the toolbar on iPhone

iOS - fix tab switcher collectionview size

---

macOS/DuckDuckGo/Common/Extensions/NSPopoverExtension.swift
macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/History/View/Onboarding/HistoryViewOnboardingPopover.swift
macOS/DuckDuckGo/History/View/Onboarding/HistoryViewOnboardingView.swift
macOS/DuckDuckGo/Localizable.xcstrings
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Resources/Localizable.xcstrings

Task/Issue URL: https://app.asana.com/0/1142021229838617/1209662271514050
This change updates the message in History View onboarding popover and fixes positioning so that
the popover is always contained in the parent window.
1. Launch the app and select Main Menu -> Debug -> History -> Show History View Onboarding.
2. Verify that it uses the new copy as linked in the Asana task, and that it’s fully visible in the containing window.
---

Update History View onboarding popover copy and positioning

---

iOS/Core/UserDefaultsPropertyWrapper.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/CheckDefaultBrowser/CheckDefaultBrowserService.swift
iOS/DuckDuckGo/CheckDefaultBrowser/DefaultBrowserInfoStore.swift
iOS/DuckDuckGo/CheckDefaultBrowser/DefaultBrowserManager.swift
iOS/DuckDuckGoTests/CheckDefaultBrowser/CheckDefaultBrowserServiceTests.swift
iOS/DuckDuckGoTests/CheckDefaultBrowser/DefaultBrowserInfoStoreTests.swift
iOS/DuckDuckGoTests/CheckDefaultBrowser/DefaultBrowserManagerTesting.swift

Task/Issue URL: https://app.asana.com/0/72649045549333/1209503813353609
Add manager to check if web browser is default and persist result
Ensure unit tests pass.
---

[iOS] Set As Default Browser Manager

---

.github/workflows/create_asana_pr_subtask.yml
.github/workflows/ios_pr_task_url.yml
.github/workflows/macos_pr_task_url.yml
iOS/Gemfile.lock
iOS/fastlane/Pluginfile
macOS/DuckDuckGo/History/View/HistoryViewActionsHandler.swift
macOS/DuckDuckGo/Statistics/HistoryViewPixel.swift
macOS/Gemfile.lock
macOS/UnitTests/History/View/HistoryViewActionsHandlerTests.swift
macOS/fastlane/Pluginfile

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1209676887976296?focus=true
1. Launch the app and filter logs by PixelKit subsystem
2. Open history view (cmd+y)
3. Double click a single item on the list. Verify that it opens the URL and sends _m_mac_history-page_item-opened_ pixel with _"type": "single”_
4. Select multiple history items, show context menu and trigger any of the open actions. Verify that it opens URLs and sends _m_mac_history-page_item-opened_ pixel with _"type": “multiple”_
—

Add single/multiple parameter to history item opened pixel

---

iOS/DuckDuckGo/DuckPlayer/NativeUI/DuckPlayerNativeUIPresenter.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204099484721401/task/1209531197736712
CC:
Bugfix: Disable interactions when DuckPlayer Pill is hidden
1. Make youself internal
2. Go to DuckPlayer > Settings > Enable Native UI
3. Tab Fire button
4. Go to a youtube.com and open a video
5. DuckPlayer Pill should appear at the bottom
6. Scroll the page until pill hides
7. Confirm webview receives touch events where the pill was showing.
---

iOS: DuckPlayer: 44. Disable pill interaction when hidden

---

macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/Freemium/DBP/Experiment/FreemiumDBPPixelExperimentManaging.swift
macOS/LocalPackages/DataBrokerProtection/Sources/DataBrokerProtection/Pixels/FreemiumDBPExperimentPixel.swift
macOS/UnitTests/Freemium/DBP/Experiment/FreemiumDBPPixelExperimentManagingTests.swift
macOS/UnitTests/Freemium/DBP/FreemiumDBPFeatureTests.swift

Task/Issue URL: https://app.asana.com/0/1206488453854252/1209643339074944
This PR implements a follow-up retroactive measurement to enable us to compare subscriptions between the control and treatment cohorts. Our metric works as follows:
* Adds a new pixel which is fired under the following conditions:
** User is in the control or treatment cohort
** User has an active PP subscription (wouldn't include users who have since cancelled)
* The pixel includes the following parameters:
** Cohort
** Days enrolled (the number of days the user has been enrolled in the experiment)
* The pixel is unique (fired once per user)
1. Launch the browser. 
2. Via the debug `Freemium` menu, select `Enroll into Experiment`
3. Filter the Xcode console by “pixel"
4. Re-launch the browser
5. Ensure the …

macOS: Freemium PIR - Add Follow-up Pixel Measurement of Cohort Subscriptions

---

macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarPopoverManager.swift
macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift
macOS/DuckDuckGoVPN/VPNProxyLauncher.swift
macOS/LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/Controller/TransparentProxyController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/0/task/1209699791105436
The VPN menu app can become unresponsive in our App Store builds due to a never ending loop where status updates cause our proxy configuration to be loaded, which in turns trigger another status update.
Also pushing some changes to make sure the exclusions menu is not visible in App Store builds.
1. Run the App Store build.
2. Ensure the VPN menu app stays responsive.
NA
If the logic isn't right we introduce a regression, but I believe it's pretty much self-explanatory.
NA
Focus on making sure the changes are logical, and testing shows no issues.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/19906486 …

Fixes some VPN issues

---

iOS/Core/PixelEvent.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/CheckDefaultBrowser/DefaultBrowserManager.swift
iOS/DuckDuckGo/CheckDefaultBrowser/DefaultBrowserManagerEventMapper.swift
iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingIntroViewModel.swift
iOS/DuckDuckGo/OnboardingExperiment/Pixels/OnboardingPixelReporter.swift
iOS/DuckDuckGoTests/DefaultBrowserManagerMock.swift
iOS/DuckDuckGoTests/OnboardingFirePixelMock.swift
iOS/DuckDuckGoTests/OnboardingIntroViewModelTests.swift
iOS/DuckDuckGoTests/OnboardingPixelReporterMock.swift
iOS/DuckDuckGoTests/OnboardingPixelReporterTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1209505775591510
This PR add experiment pixels for Set as Default Browser experiment. 
Prerequisites: Run the build on a device with iOS 13.3 installed.
Override Privacy Config URL with: https://www.jsonblob.com/api/1344905087407022080
Scenario 1: Control Group
1. Open the Debug menu.
2. Ensure the Internal User State toggle is on.
3. Tap the Feature Flags item.
4. Tap “onboardingSetAsDefaultBrowser”.
5. Choose the control cohort.
6. Go back to the main debug menu.
7. Tap Onboarding.
8. Tap “Preview Onboarding Intro”.
9. Wait for the onboarding to appear and tap the Let’s do it! button.
10. Wait for the Protections activated! screen to appear.
11. Tap the 'Choose Your Browser' button.
12. Ensure pixel …

[iOS] Onboarding Experiment - Set as default browser pixels implementation

---

iOS/DuckDuckGo/AIChat/AIChatDeepLinkHandler.swift
iOS/DuckDuckGo/AIChat/AIChatViewControllerManager.swift
iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL:
CC:
Allow duck.ai to be opened from already presented modals
1. Open tab switcher, tap on duck.ai, check if it works
2. Open random modals like passwords, bookmarks, etc. Then open duck.ai from widgets. Validate that it first dismisses whatever was presented and then opens duck.ai

Modal changes for tab switcher

---

iOS/DuckDuckGo/AIChat/AIChatViewControllerManager.swift
iOS/LocalPackages/AIChat/Sources/AIChat/AIChatViewModel.swift
iOS/LocalPackages/AIChat/Sources/AIChat/AIChatWebViewController.swift
iOS/LocalPackages/AIChat/Sources/AIChat/Public API/AIChatUserAgentProviding.swift
iOS/LocalPackages/AIChat/Sources/AIChat/Public API/AIChatViewController.swift

Task/Issue URL: https://app.asana.com/0/1204167627774280/1209701767587116/f
CC:
Set UA on duck.ai webview
1. Go to the debug settings, and enable inspectable webview
2. Open a tab on the SERP, inspect the webview and check the UA with `navigator.userAgent`
3. Open duck.ai, inspect the webview and check the UA with `navigator.userAgent`
4. Both UA should match 
Low: small bug fixes
Wrong UA is set

Set UA on duck.ai webview

---

.maestro/shared/sync_recover_data.yaml

Task/Issue URL: https://app.asana.com/0/414709148257752/1209708332006139/f
CC:
Update order of actions so that `assertVisible` is called before `tapOn`, since tapping causing a blocking UI passcode prompt which causes the `assertVisible` to fail
1. Confirm Sync UI tests complete successfully ->  https://github.com/duckduckgo/apple-browsers/actions/runs/13928524239
---

Maestro Sync test fix: Assert visibility of 'Recover Synced Data’ Sync row before tapping

---

macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/Bookmarks/Model/BookmarkManager.swift
macOS/UnitTests/Bookmarks/Model/LocalBookmarkManagerTests.swift

Task/Issue URL: https://app.asana.com/0/1205237866452338/1209660514434895/f
This change adds completion handler to some of the BookmarkManager APIs in order to allow for more reliable unit testing.
None (tests code + some API changes but made in a way that is transparent to the existing code).
---

Stabilize LocalBookmarkManager unit tests

---

macOS/DuckDuckGo/Fire/Model/Fire.swift
macOS/DuckDuckGo/Windows/View/WindowsManager.swift

Task/Issue URL: https://app.asana.com/0/1199178362774117/1209703704629721/f
This change remembers burned window frame in order to reopen a new window with the same exact frame
(instead of cascading from that frame that resulted in shifting the window to the right and down).
1. Launch the app and, to simplify testing, put the window in the upper-left corner of the screen.
2. Burn all data. Verify that the new window is placed in the exact same frame in the upper-left corner of the screen.
3. Repeat the same with burning “current window”.
4. Repeat the same with burning “current tab” when you only have 1 tab.
5. Open multiple windows and burn all data. Verify that the new window is placed in the exact same frame as the window you’ve initiated burning from.
Low
Nothing really – we’re …

Reopen window in the same position after burning

---

iOS/DuckDuckGo/PrivacyProPromotionExperiment/OnboardingPrivacyProPromoExperiment.swift
iOS/DuckDuckGoTests/Onboarding/PrivacyProPromotionExperiment/OnboardingPrivacyProPromoExperimentTests.swift

Task/Issue URL: https://app.asana.com/0/0/1209678164669763
This PR contains a minor change to remove unnecessary code relating to the Privacy Pro Onboarding experiment. This code checked privacy pro eligibility to ensure a user is eligible before enrolling them to the experiment. However, we have decided to only target the US, and so this check is redundant. See the related Privacy Config [here](https://github.com/duckduckgo/privacy-configuration/pull/2876).
1. Green CI is adequate here, as this is removing redundant code and updating tests.
Low: If the privacy config was incorrectly configured, non-US users might be incorrectly enrolled.
--- …

Privacy Pro Onboarding Experiment - Remove Redundant Code & Update Test

---

macOS/DuckDuckGoVPN/VPNProxyLauncher.swift

Task/Issue URL: https://app.asana.com/0/1199230911884351/1209699791105436/f
This is a follow up to [a previous attempt at fixing this issue](https://github.com/duckduckgo/apple-browsers/pull/252).  While my previous attempt did mitigate the issue, the issue was not fully resolved.
1. Start the VPN.  Ensure CPU usage is normal.
2. If testing on the Sparkle build make sure the proxy is launched when exclusions are added, and stopped when there are no app or website exclusions
Low
Not much really.  This would only affect the VPN proxy, which is mostly not noticeable.
Ensure the logical changes make sense.
NA
--- …

Fixes an issue where the proxy can cause high CPU usage

---

iOS/DuckDuckGo/DaxDialogs.swift
iOS/DuckDuckGo/NewTabPageViewController.swift
iOS/DuckDuckGo/OnboardingExperiment/ContextualDaxDialogs/NewTabDaxDialogFactory.swift
iOS/DuckDuckGoTests/ContextualOnboardingNewTabDialogFactoryTests.swift
iOS/DuckDuckGoTests/DaxDialogTests.swift
iOS/DuckDuckGoTests/NewTabPageControllerDaxDialogTests.swift
iOS/DuckDuckGoTests/NewTabPageControllerPixelTests.swift
iOS/DuckDuckGoTests/TabViewControllerDaxDialogTests.swift

Task/Issue URL: https://app.asana.com/0/0/1209738106994913
This PR makes changes to ensure we display/dismiss the keyboard as expected when displaying/dismissing the Privacy Pro Onboarding Promotion. See test cases below.
1. Force a treatment cohort by adding `return .treatment` as the first line of the `getCohortIfEnabled` method in `OnboardingPrivacyProPromoExperiment`
1. Fresh install the app on a physical device
2. Launch and proceed to the ‘High Five’ last onboarding step
3. Tap ‘High Five’ to display the PP promotion
4. Ensure the Keyboard is dismissed
5. Tap ‘Learn More'
6. Ensure the keyboard remains dismissed the the PP paywall is opened
1. Fresh install the app on a physical device
2. Launch and proceed to the ‘High Five’ last onboarding step
3. Tap ‘High Five’ to display the PP …

iOS: Privacy Pro Onboarding Promotion - Ensure Correct Keyboard Behavior

---

iOS/DuckDuckGo/TabSwitcherViewController+MultiSelect.swift

Task/Issue URL: https://app.asana.com/0/1209499866654340/1209755087595724/f
CC:
Fire a pixel when de/select all tabs is tapped.
1. Open tab switcher. 
2. Tap edit
3. Tap select tabs
4. Tap Select all button - check select all tabs and select all tabs daily button fired
5. Tap Deselect all button - check deselect all tabs and deselect all tabs daily button fired
6. Repeat and check the daily not sent again
Low: minor fix for pixels
Not much
Only affects the de/select all tabs functionality.
Just the tab switcher and firing pixels.

fire pixel on de/select all tabs

---

.github/workflows/macos_ui_tests.yml

Task/Issue URL: https://app.asana.com/0/1203301625297703/1209765123515594/f
This change updates macOS UI Tests workflow so that it runs single workflow per test case per OS version,
reducing total run time to <30 minutes. UI Tests will now run on macOS-related pull requests (only testing
macOS 15 to reduce costs).
1. Verify [this workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/14022842581) output for testing all OS versions.
2. Verify that this pull request runs UI tests for macOS 15.
None
---

Run macOS UI Tests on all macOS-related pull requests

---

macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift
macOS/LocalPackages/NetworkProtectionMac/Sources/NetworkProtectionProxy/Provider/TransparentProxyProvider.swift

Task/Issue URL: https://app.asana.com/0/1207603085593419/1207633069844317/f
Resolve the VPN's `StartError` code `2`.
This won't fix all VPN start issues.  Only a specific one.
Start the VPN, delete the configuration from settings, start the VPN again.
Make sure you never see a "[DEBUG] Connection status invalid" message or "An unexpected error occurred, please try again".
Medium
A mistake in my changes could cause trouble for users starting the VPN, but our testing is aimed to handle that.
None
Focus on making sure the changes make sense, and testing that the VPN doesn't become completely broken.
--- …

Fixes VPN StartError 2

---

iOS/DuckDuckGo/SwipeTabsCoordinator.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201392122292466/task/1209485028986793
CC: @dus7 
Fixes the issue with dax logo jumping on swipe.
This code needs to be refactored to create snapshot based on the new NewTabPageViewController and not logoContainer which no longer displays.
1. Make sure tab swiping works as on main, and doesn't glitch for regular pages.
Low: Minor visual changes
---

Fix issue with jumping dax logo

---

macOS/DuckDuckGo/Fire/View/FireViewController.swift

Task/Issue URL: https://app.asana.com/0/1201048563534612/1209535721897918/f
This change attempts closing all windows before fire animation is played. Otherwise, if there
was a popover open (e.g. location permission or search suggestions), the animation would be
played “below” the popover and only after that the popover would be closed.
1. Run the app and visit maps.google.com
2. Request current location to trigger the location permission popover.
3. Burn all data using Fire button.
4. Verify that the location permission popover is closed before playing fire animation.
5. Type a search phrase in the address bar (so that the suggestions window is open) but don’t trigger the search.
6. Burn all data using Fire button and verify that the suggestions window is closed before playing fire …

Close all child windows before playing fire animation

---

.maestro/release_tests/backbutton-close-tab.yaml
iOS/DuckDuckGo/TabsModel.swift
iOS/DuckDuckGoTests/TabManagerTests.swift

Task/Issue URL: https://app.asana.com/0/392891325557410/1209761300722413/f
CC:
When the back button is used on a tab that was open from another page it should go back to that page.
1. Visit https://privacy-test-pages.site
2. Open a new tab and visit https://www.search-company.site
3. Go back to the first tab and long press on a link, then select open in new tab
4. Tap the back button - should return to the privacy test pages
5. Open a few tabs and try closing with the tab switcher
Medium
Could disrupt back button flow
* UI and unit tests were added, especially around the tab manager.
Focus on opening and closing tabs in various ways.
--- …

iOS - Fix app switches to wrong tab when pressing back

---

macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/DuckDuckGo/TabBar/ViewModel/TabCollectionViewModel.swift
macOS/UITests/TabBarTests.swift

Task/Issue URL: https://app.asana.com/0/1204006570077678/1209751086393041/f
CC:
This reverts commit 7e15ec6e4f6f83c084e71cd052fcef41249109de.
I was testing the new internal release, and I realized that if you have a pinned tab and try to close the only unpinned tab, the application would be in a weird state where the unpinned tab would not disappear, and new tabs would not appear.
1. Open a tab and pin it
2. Open an unpinned tab
4. Close the unpinned tab
5. The unpinned tab should disappear and adding new tabs should work as normal
Low: we are removing a change that introduced a bug.
Nothing

Revert "Fix scrolling when moving to a not visible tab (#311)"

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift

Task/Issue URL: https://app.asana.com/0/1201037661562251/1209784430748045/f
This change removes the native NTP dead code from the address bar classes.
Run the app and smoke test the address bar:
1. Verify that it displays correctly in dark and light mode
2. Verify that suggestions window displays correctly (shadow + border color) in dark and light mode.
Low/None: removing unused code branches.
---

Remove AddressBarTextField.isSearchBox

---

macOS/DuckDuckGo/Tab/TabExtensions/FaviconsTabExtension.swift

Task/Issue URL: https://app.asana.com/0/72649045549333/1209796699357949/f
This change fixes favicons being initially cleared on all tabs upon state restoration.
1. Open a few tabs
2. Enable state restoration
3. Quit the app (cmd+q, not via Xcode or the state won’t be persisted).
4. Launch the app and verify that favicons are immediately shown on tabs, even before lazy loading starts.
None: clear bug fix.
---

Ignore initial (nil) favicon event in favicon publisher

---

macOS/DuckDuckGo/Suggestions/Model/SuggestionContainer.swift
macOS/DuckDuckGo/Suggestions/ViewModel/SuggestionViewModel.swift
macOS/UnitTests/Suggestions/ViewModel/SuggestionViewModelTests.swift

Task/Issue URL: https://app.asana.com/0/1201048563534612/1209769319551329/f
This change adds internal History page to search suggestions.
1. Launch the app
2. Type “history” in the address bar and verify that History View displays as the last suggestion. Verify that it opens History View.
3. Enable `autocompleteTabs` feature flag via _Main Menu -> Debug -> Feature Flag Overrides_
4. Keep History tab open and open a new tab. Type “history” and verify that it displays as “Switch to tab” suggestion. Verify that it correctly switches to History tab.
Low/None: Minor visual changes, small bug fixes, improvement to existing features
I’ve updated unit tests.
--- …

Display History View in search suggestions

---

BrowserServicesKit/Sources/PixelKit/PixelKit.swift

Task/Issue URL: https://app.asana.com/0/0/1209797430851748/f
CC:
Makes it so pixelkit pixels on iOS won't errantly get macOS prefixes
1. Run the iOS app and use it a bit then check the console that no pixel names have changed (e.g. nothing has two prefixes, or zero prefixes). (Pixel kit isn't really being used on iOS, so this really is just double checking)
2. Run the macOS app and use it a bit, including using PIR (e.g. edit profile data and set scans running)
3. Check that PIR pixels haven't changed and have the correct Mac prefix
4. Check that debug pixels haven't changed and have the correct debug prefix. One you can look for is m_mac_debug_content_blocking_lookup_rules_succeeded
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | …

PIR shared code extraction: Pixelkit iOS support

---

macOS/DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser App Store.xcscheme
macOS/DuckDuckGo-macOS.xcodeproj/xcshareddata/xcschemes/macOS Browser.xcscheme

Task/Issue URL: https://app.asana.com/0/1200194497630846/1209802344094592/f
This was brought to my attention by https://app.asana.com/0/1205237866452338/1209801961396805/f
I had previously brought it up in the team channel that these tests were being quite flakey lately so I disabled them.
NA
Low
Scam and malware detection failing would be bad for optics, but disabling these tests isn't introducing an issue - just making the CI focus on what we know NOT to be broken.
NA
I've opened [a task](https://app.asana.com/0/1200194497630846/1209802344094592/f) to report these tests are being disabled.
--- …

Disables a flakey test

---

.github/workflows/update_code_signing.yml
iOS/fastlane/Fastfile
macOS/fastlane/Fastfile
macOS/fastlane/README.md

Task/Issue URL: https://app.asana.com/0/1201899738287924/1209731854785342/f
This change adds a new workflow to be used to update code signing assets
See historical runs [here](https://github.com/duckduckgo/apple-browsers/actions/workflows/update_code_signing.yml)
---

Add a workflow to sync signing assets

---

iOS/fastlane/Fastfile

Task/Issue URL: https://app.asana.com/0/1203301625297703/1209796700502819/f
CC:
This PR skips waiting for iOS build processing, as the processing times have gotten extremely long recently.
1. Check that the diff looks good - not sure we can test this otherwise without doing an actual build upload
2. Check that no other iOS uses of `upload_to_testflight` need to be modified
I'm sending this to the release branch since that's where we are most affected by this right now. Another PR will be available for the macOS branch soon.
---

[Release PR] Skip waiting for iOS build processing

---

macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift
macOS/DuckDuckGoVPN/VPNAppEventsHandler.swift
macOS/LocalPackages/NetworkProtectionMac/Sources/VPNAppState/Extensions/UserDefaults+isVPNMigratedToAuthV2.swift
macOS/LocalPackages/NetworkProtectionMac/Sources/VPNAppState/VPNAppState.swift

Task/Issue URL: https://app.asana.com/0/0/1209809380088650
Make sure the VPN is launched on V2 right after the first migration by restarting the VPN manually.
1. Launch the VPN on V1
2. Switch on the V2 flag
3. Relaunch the app
Ensure the VPN is running on V2 immediately.
Low
I can't think of anything.
If we roll back v2 we'll need to change this default to something else.
None
---

macOS: Launch VPN on V2 right after the migration

---

iOS/DuckDuckGo/DuckPlayer/NativeUI/DuckPlayerNativeUIPresenter.swift
iOS/DuckDuckGo/DuckPlayer/NativeUI/Views/DuckPlayerContainer.swift
iOS/DuckDuckGo/DuckPlayer/NativeUI/Views/DuckPlayerEntryPillView.swift
iOS/DuckDuckGo/DuckPlayer/NativeUI/Views/DuckPlayerMiniPillView.swift
iOS/DuckDuckGo/DuckPlayer/NativeUI/Views/DuckPlayerViewUtils.swift
iOS/DuckDuckGo/SettingsDuckPlayerView.swift
iOS/DuckDuckGo/UserText.swift
iOS/DuckDuckGo/en.lproj/Localizable.strings

Task/Issue URL: https://app.asana.com/0/0/1209731245273066
CC:
- Adds ability to dismiss DuckPlayer pill, or drag up to open DuckPlayer
1. Set yourself as internal user
2. Enable DuckPlayer Native UI (Settings > DuckPlayer), confirm it's on "Let me choose" mode
3. Go to a youtube.com and open a video
4. Grab Duckplayer pill by the handle and drag it outside the view
5. Scroll through the page, and refresh
**6. Confirm the pill keeps hidden**
7. Navigate to other video
8. Confirm Pill shows up again
9. Drag up and release
**10. Confirm DuckPlayer opens**
--- …

iOS: DuckPlayer: 48. Add grab handle to DuckPlayer Pill

---

SharedPackages/BrowserServicesKit/Tests/CommonTests/Extensions/DateExtensionTest.swift

Task/Issue URL: https://app.asana.com/0/1205237866452338/1209168582277729/f
CC:
This PR attempts to fix a flaky test that looks to be related to date precision. The fix is to allow a `0.1` second tolerance in the checks.
1. Check that `testStartOfMinuteNow` didn't fail on CI
---

Attempt to fix flaky date check tests

---

iOS/Core/PixelEvent.swift
iOS/DuckDuckGo/UICoordination/LaunchActionHandler.swift
iOS/DuckDuckGoTests/LaunchActionHandlerTests.swift

Task/Issue URL: https://app.asana.com/0/0/1209593812414962
This PR adds new pixels to measure:
1. When the app is launched by tapping an external link (cold start and resume from backround)
2 When the app is launched by sharing a link/search via the share extension. (cold start and resume from background)
**NOTE**
I will open the Privacy Triage once the review has been approved to avoid creating extra works for Privacy team if we decide to change pixels name or add more of them. Hence, the `DO NOT MERGE` label.
**Privacy Triage**
[Privacy Triage Approved](https://app.asana.com/0/69071770703008/1209811367393595/f)
**Scenario 1 - Measure App launched by external link (cold start)** ✅ 
1. Ensure to select `iOS Browser` scheme and change app launch to “Wait for executable to be launched” in …

[iOS]Add new pixels to measure app launches

---

macOS/DuckDuckGo/Bookmarks/Services/BookmarksContextMenu.swift
macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/History/View/HistoryViewActionsHandler.swift
macOS/DuckDuckGo/Localizable.xcstrings
macOS/DuckDuckGo/NewTabPage/Features/DefaultsFavoritesActionHandler.swift
macOS/LocalPackages/NewTabPage/Sources/NewTabPage/Favorites/NewTabPageFavoritesActionsHandler.swift
macOS/LocalPackages/NewTabPage/Sources/NewTabPage/Favorites/NewTabPageFavoritesModel.swift
macOS/LocalPackages/NewTabPage/Sources/NewTabPage/internal/UserText.swift
macOS/LocalPackages/NewTabPage/Tests/NewTabPageTests/Mocks/CapturingNewTabPageFavoritesActionsHandler.swift
macOS/UnitTests/Bookmarks/Model/ContextualMenuTests.swift
macOS/UnitTests/History/View/HistoryViewActionsHandlerTests.swift

Task/Issue URL: https://app.asana.com/0/1148564399326804/1209296794793953/f
Adding a new "Copy" context menu item to new tab page favorites
1. Make a couple of favorites
2. Open a new tab page
3. Open a context menu on a random favorite and select "Copy"
4. Paste the content of a clipboard to the address bar and verify it contains the URL of favorite
5. Open a context menu on a different favorite and select "Copy" again
4. Paste the content of a clipboard to a third party app (Notes) and verify it contains the URL of the last copied favorite
Low
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | [Tech Design Template](https://app.asana.com/0/59792373528535/1847099713119 …

Copy context menu item added to new tab page favorites

---

macOS/DuckDuckGo/NewTabPage/NewTabPageWebViewModel.swift
macOS/DuckDuckGo/Tab/View/BrowserTabViewController.swift
macOS/LocalPackages/NewTabPage/Sources/NewTabPage/NewTabPageUserContentController.swift

Task/Issue URL: https://app.asana.com/0/1199333091098016/1209821590760695/f
CC:
This PR fixes (in a not so ideal way) a leak with the NTP user scripts. I'll elaborate on why it's not ideal in the comments.
1. Open and close a bunch of windows
2. Open the memory graph debugger
3. Filter for `NewTab` and check that you don't see a large number of user content controllers, user scripts, etc.
4. Test that the repro steps in the [original Asana task](https://app.asana.com/0/1201037661562251/1209767015721459/f) are fixed too
---

Fix NTP User Script leak

---

macOS/DuckDuckGo/Preferences/Model/PreferencesSection.swift

Task/Issue URL: https://app.asana.com/0/0/1209810971334424/f
CC:
Changes ‘DuckDuckGo on Other Platforms’ URL to point to `https://duckduckgo.com/app/devices?origin=funnel_app_macos` instead of `https://duckduckgo.com/app?origin=funnel_app_macos`
1. Go to settings
2. Tap on 'DuckDuckGo on Other Platforms’ (below About)
3. Check the URL is pointing to: https://duckduckgo.com/app/devices?origin=funnel_app_macos
Low
Nothing
No impact
Nothing.
—

Change ‘DuckDuckGo on Other Platforms’ URL

---

macOS/DuckDuckGo/Preferences/Model/TabsPreferences.swift
macOS/DuckDuckGo/StateRestoration/AppStateRestorationManager.swift
macOS/DuckDuckGo/StateRestoration/WindowManager+StateRestoration.swift

Task/Issue URL: https://app.asana.com/0/1201037661562251/1209850219424385/f
This refactor fixes unexpected behavior in windows after the pinned tabs setting has been migrated.
**Test migration of pinned tabs from previous version**
1. Download [1.132.0.400](https://staticcdn.duckduckgo.com/macos-desktop-browser/duckduckgo-1.132.0.400.dmg) and install it
2. Pin a couple of tabs
3. Quit the app
4. Open Xcode, checkout `tom/pinned-tabs-presented` and edit the build configuration to `RELEASE`
5. Run the app
6. Verify pinned tabs from previous session are visible in the restored window
7. Make sure Settings for Pinned tabs are set to "Shared across all windows"
**Test default setting**
1. Edit the build configuration back to `DEBUG`
2. Erase data to simulate the clean installation …

Pinned tabs setting migration refactored to avoid unexpected behavior

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleConfigurable.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/0/72649045549333/1209793701087222/f
CC:
Adds the `visualRefresh` feature flag and creates a manager to handle the old and new visual styles.
This change does not apply any style yet, it only adds the feature flag so we can add all the changes behind the feature flag so internal users can test incrementally, it will also speed up merging to main and review time, giving that I will be creating smaller PRs for each visual change.
1. Check that `visualRefresh` feature flag is part of the Local Overrides in the debug menu
2. Verify you can turn the override on and off (the default should be off)
Nothing I’m aware of.
What do you think about the separation of …

Add visual refresh feature flag for internal testing

---

SharedPackages/BrowserServicesKit/Sources/Bookmarks/FaviconsFetcher/BookmarksFaviconsFetcher.swift
SharedPackages/BrowserServicesKit/Tests/BookmarksTests/FaviconsFetcher/BookmarksFaviconsFetcherTests.swift
iOS/Core/SyncBookmarksAdapter.swift
macOS/DuckDuckGo/Sync/SyncBookmarksAdapter.swift

Task/Issue URL: https://app.asana.com/0/1201037661562251/1209852916533543/f
Make sure that favicons fetcher store is accessed on main thread now that we’ve removed FaviconsManager.shared
and replaced it with an instance owned by App Delegate.
1. Verify that [macOS Sync E2E Tests](https://github.com/duckduckgo/apple-browsers/actions/runs/14217350676) and [iOS Sync E2E Tests](https://github.com/duckduckgo/apple-browsers/actions/runs/14217355529) workflows pass 
2. Launch the macOS app and set up Sync
3. Verify that it doesn’t crash and that it also doesn’t display main thread checker warnings in runtime.
Low: 
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | [Tech …

Update Sync BookmarksFaviconsFetcher to access FaviconManager on main thread

---

macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
macOS/UnitTests/TabBar/View/MockTabViewItemDelegate.swift
macOS/UnitTests/TabBar/View/TabBarViewItemTests.swift

Task/Issue URL: https://app.asana.com/0/1208937634215685/1209014735687766/f
This change adds a delegate callback to TabBarViewItem, triggered before showing context menu.
This callback is handled in TabBarViewController by hiding any tab preview shown.
1. Launch the app and hover over a tab bar item view.
2. Wait until a tab preview is shown, and trigger context menu.
3. Verify that the tab preview was hidden before context menu was shown.
Low
---

Hide tab preview before displaying context menu for a tab item view

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleConfigurable.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/0/1204006570077678/1209350564013383/f
CC:
This adds the new height for the navigation bar; now, it is `52` for both the default and home page. The pop-up remains unchanged.
It also changes the paddings, and now we have `6` for both the top and bottom.
This change introduces how we will use the feature flag to apply the different changes.
1. Select the feature flag from `Debug -> Feature Flag Overrides -> visualRefresh`
2. Open a new window
3. The navigation bar should be taller compared to the other one
4. Turn off the override
5. Open another window
6. The navigation bar size should be back to production values
I moved some logic around in the …

Increase navigation bar size and change paddings for new visual refresh

---

macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/0/1204006570077678/1209793701087213/f
CC:
The corner radius of the navigation bar buttons will be changed depending on the style. It will be 9px for the new/current style and 4px for the legacy.
| Before | After |
| ------ | ----- |
1. Turn on the override of `visualRefresh`
2. Open a new window
3. Hover the different buttons in the navigation bar
4. Check they are more rounded.
Nothing I can think of.
N/A
N/A
—

Apply corner radius to navigation bar buttons depending on style

---

SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/MockPixelHandler.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+CustomURL.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+Redirect.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/PrivacyProSubscriptionV2IntegrationTests.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift
iOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift
iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
macOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift
macOS/DuckDuckGo/Subscription/SubscriptionManager+StandardConfiguration.swift
macOS/DuckDuckGoDBPBackgroundAgent/DuckDuckGoDBPBackgroundAgentAppDelegate.swift
macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift

Task/Issue URL: https://app.asana.com/0/72649045549333/1209710701141726
CC: @miasma13
All Subscription AuthV2 related pixels are now fired from the same struct, and now all parts of the iOS and macOS apps are firing them.
I've also added a`source` parameter to every relevant pixel that will be usefull for filtering them in the grafana board
---

Pixel handler improvements

---

macOS/DuckDuckGo/Tab/Model/Tab.swift

Task/Issue URL: https://app.asana.com/0/1201037661562251/1209884224558923/f
This change disables tab deallocation check for integration tests runs.
---

Fix crashing in tab deallocation check in CI

---

iOS/Core/UIColorExtension.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/PullToRefreshViewAdapter.swift
iOS/DuckDuckGo/SiteThemeColorManager.swift
iOS/DuckDuckGo/TabViewController.swift

Task/Issue URL: https://app.asana.com/0/1201392122292466/1209485028986795/f
Figma spec: https://www.figma.com/design/triNDLtPcx4by8Hsw9CzYt/%F0%9F%96%8D%EF%B8%8F-2025-Visual-Design-Update-%26-1-Tap-AI-ChatOS-%2B-Android?node-id=4986-136394&p=f&t=kmrB3uAPfU8inDSj-0
CC: @dus7 
Change parts of UI based on site's theme color.
Please note, there's no decision yet on how want to change the color of activity indicator so it contrasts with the site's color.
1. Have your search bar at the bottom.
2. Visit a site with a theme color, e.g. www.filmweb.pl (black one).
3. Notice the color change of the top status bar and webview background.
4. Try to break it, refresh, open new site, open new tab, close tab, long press, open favorites, rotate, change dynamically bar position (in settings), swipe …

Add UI based on site theme color

---

macOS/DuckDuckGo/Preferences/Model/SyncPreferences.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199230911884351/task/1209962162926952?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/1199230911884351/task/1209571867429615?focus=true
I found an issue where the "Copy Code" button for sync doesn't work on macOS at the end of the backup flow. I think this was masked before because codes often remain on the pasteboard after testing another flow. This fixes it and also generally makes the copyCode function more robust than it was before.
See linked asana task
This could have a side-effect I haven't spotted yet. But I'm pretty happy that the updated logic is more robust.
Just this sync bug and other flows that show the recovery code dialog (generally …

Make sure recovery code displayed on backup

---

SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionURL.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionURLTests.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/PrivacyProPromotionExperiment/OnboardingPrivacyProPromoExperiment.swift
iOS/DuckDuckGo/SettingsRootView.swift
iOS/DuckDuckGo/Subscription/SubscriptionFunnelOrigin.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/Preferences/View/PreferencesRootView.swift
macOS/DuckDuckGo/Subscription/SubscriptionAttributionPixelHandler.swift
macOS/DuckDuckGo/Subscription/SubscriptionFunnelOrigin.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/0/task/1209939561643745
The goal of these changes is significantly reduce the number of unattributed subscriptions by adding/updating Privacy Pro origins. 
**Note:** Each iOS test requires a sandbox user who is eligible for purchase (i.e not a subscriber)
**Prerequisites:**
*  Place a breakpoint at line `1224` of `SubscriptionPagesUseSubscriptionFeature` to allow observation of pixel origin
*  Add `return .treatment` to line `92` of `OnboardingPrivacyProPromoExperiment` to force onboarding experiment
1. Run a fresh install of the app on a device
2. Navigate through onboarding to the privacy pro promotion (last onboarding dialog)
3. Tap `Learn More`
4. On the paywall, purchase a subscription
5. When the purchase succeeds, ensure …

macOS/iOS: Implement new and updated Privacy Pro Origins 

---

macOS/DuckDuckGo/MainWindow/MainWindowController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1209999815083499?focus=true
1. Enter Full Screen mode
2. Hide the Tab Bar (View → Show Tabs and Bookmarks Bar in Full Screen)
3. Show the Tab Bar again
4. Make sure the 1px line doesn‘t appear below the tab bar
5. Test the Tab Bar controls (selection/closing/new tab), Navigation bar controls (Back/Forward/Address Bar/Menu) - they should work
Low
Tab bar or navigation bar becomes unresponsive 
---

Prevent 1px line from appearing below Tab Bar

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210000017647881?focus=true
CC:
Fix bookmarks padding
1. Open a long URL, like [this](https://duckduckgo.com/?q=wgsdgsgdsgsdgdsgdsgsgwgsdgsgdsgsdgdsgdsgsgwgsdgsgdsgsdgdsgdsgsgwgsdgsgdsgsdgddddsgdsgsg&ia=web)
2. Enable Show Full Website Address
3. Check if when you hover the mouse in the address bar, the bookmark button is not beneath the url text
Low: Minor visual change
Missing some state where this new constraint might break the UI

Fix omnibar button padding

---

macOS/SyncE2EUITests/CriticalPathsTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1209998672880350?focus=true
There's been a slight change in the sync logic determining what is a recovery. Previously, the recovery codes was used for connecting as well as recovery, but now it's only used for recovery. This means that the recovery code modal will not show when logging in in the UI tests (as they only ever use a recovery code). 
This change should capture both the old and new flow.
CI on the sync e2e job should be green: https://github.com/duckduckgo/apple-browsers/actions/runs/14492806184
Low
Failing tests
--- …

Fix macos sync UI tests

---

iOS/DuckDuckGo/DuckPlayer/NativeUI/Views/DuckPlayerWebView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210001303846098
CC:
Compilation fails on Xcode 16.3 because of function ambiguity. This helps the compiler with choosing a proper function. Backwards compatible with Xcode 16.2.
1. Verify compilation succeeds
Duck player timestamp reading could stop working.
---

Fix ambiguity when compiling using iOS SDK 18.4

---

macOS/DuckDuckGo/Common/View/AppKit/HoverTrackingArea.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/DuckDuckGo/TabPreview/TabPreviewWindowController.swift
macOS/LocalPackages/AppKitExtensions/Sources/AppKitExtensions/NSEventExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1208347387296425
- Mitigate issue when `mouseEntered` events are received after `mouseExited` causing Tab Previews and buttons to stack in hovered state
- Test mouse movements from the attached videos to cause the input events breakage:
https://github.com/user-attachments/assets/3d7aac49-faea-436f-8581-e0bdf4a931ff
https://github.com/user-attachments/assets/67063d95-d341-46d8-8335-1e96f5d8bbf2
- Validate the events are caught and the wrong state is noticed: the testing window will appear - keep the cursor in one place while it counts; and after the timer is done the stuck state should be recovered from (the test window code will be rolled back before merged)
High
Code breakage on future macOS releases
--- …

Fix stuck tab previews

---

macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
macOS/DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift

- Refactor Duck Player to use `LinkOpenBehavior` 
1. Open youtube; enable Duck Player 
2. Validate cmd+/cmd+shift/cmd+opt/cmd+opt+shift/middle/middle+shift/middle+cmd+shift/middle+opt/middle+cmd+opt/[+shift] - clicking links correctly opens Duck Player in expected tab configurations
---

Duck player new tab policy

---

macOS/DuckDuckGo/Tab/Model/NewWindowPolicy.swift
macOS/DuckDuckGo/Tab/Model/Tab+UIDelegate.swift
macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift
macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
macOS/DuckDuckGo/Tab/TabExtensions/NavigationHotkeyHandler.swift
macOS/DuckDuckGo/YoutubePlayer/YoutubeOverlayUserScript.swift

- Refactor Navigational links to use `LinkOpenBehavior` 
1. Open Serp, cmd+/cmd+shift/cmd+opt/cmd+opt+shift/middle/middle+shift/middle+cmd+shift/middle+opt/middle+cmd+opt/[+shift] - links, validate they‘re correctly opened respecting the Activate new tab setting
2. Validate "Open tabs instead of windows" setting works for popups when "Open in new tabs" setting in SERP is On
--- …

Navigation standard new tab policy

---

iOS/DuckDuckGo/Refactoring/Common/OmniBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1209375583889148
CC:
Animations were not completed properly when in background, leaving blank space in OmniBar. This change cancels the animations in case app is being backgrounded.
1. Open any site with trackers.
2. Wait for tracker animation to begin.
3. Put app to background
4. Go back after a few seconds, verify URL address is visible.
---

Cancel OmniBar animations on entering background

---

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
SharedPackages/BrowserServicesKit/Sources/MaliciousSiteProtection/Services/DataManager.swift
SharedPackages/BrowserServicesKit/Sources/MaliciousSiteProtection/Services/UpdateManager.swift
SharedPackages/BrowserServicesKit/Tests/MaliciousSiteProtectionTests/MaliciousSiteProtectionDataManagerTests.swift
SharedPackages/BrowserServicesKit/Tests/MaliciousSiteProtectionTests/MaliciousSiteProtectionUpdateManagerTests.swift
SharedPackages/BrowserServicesKit/Tests/MaliciousSiteProtectionTests/Mocks/MockMaliciousSiteProtectionDataManager.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/AppServices/MaliciousSiteProtectionService.swift
iOS/DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
iOS/DuckDuckGo/MaliciousSiteProtection/Services/Logger+MaliciousSiteProtection.swift
iOS/DuckDuckGo/MaliciousSiteProtection/Services/MaliciousSiteProtectionDatasetsFetcher.swift
iOS/DuckDuckGoTests/MaliciousSiteProtection/MaliciousSiteProtectionDatasetsFetcherTests.swift
iOS/DuckDuckGoTests/MaliciousSiteProtection/MaliciousSiteProtectionManagerTests.swift
iOS/DuckDuckGoTests/MaliciousSiteProtection/Mocks/MaliciousSiteProtectionMocks.swift
iOS/DuckDuckGoTests/MaliciousSiteProtection/Mocks/MockMaliciousSiteProtectionManager.swift

Task/Issue URL: https://app.asana.com/0/1206329551987282/1209638992004951/f
This PR attempts to mitigate crashes happening for Malicious Site Protection by:
1. Use `fatalError` if ApplicationSupportDirectory is unavailable when the DataManager is initialised. This is a slight improvement as the `fatalError` message should be available in the crash logs. [fc3b11f](https://github.com/duckduckgo/apple-browsers/commit/fc3b11ff388d280c2c656a58f70c4abd5744c3c9)
2. Ensure Background Tasks identifiers are registered only once. [9914e8a](https://github.com/duckduckgo/apple-browsers/commit/9914e8a23ce2c8dfbbd8e8206833223e357619ad)
3. Prevent starting new dataset updates if there are already requests in flight. [603ec57](https://github.com/duckduckgo/apple-browsers/commit/603ec576f3f6a7dc0589ba0b70df …

Malicious Site Protection - Attempt to prevent crashes

---

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/BarsAnimator.swift
iOS/DuckDuckGo/BrowserChromeManager.swift
iOS/DuckDuckGo/MainView.swift
iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/MainViewCoordinator.swift
iOS/DuckDuckGoTests/BarsAnimatorTests.swift
iOS/DuckDuckGoTests/MockOmniBar.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1208698793834668
CC: @afterxleep 
https://github.com/duckduckgo/iOS/pull/3519 introduced a debounce which was supposed to prevent hangs in some cases ([see Asana](https://app.asana.com/1/137249556945/project/414709148257752/task/1208671955053442?focus=true)), however it introduced a bug when some of the events could be fired out of order, causing the bars to remain in mid-transition state.
I removed the debounce and forced a layout pass after applying the transition to prevent late layout loop right before going to the next update.
Additionally I improved the scrolling experience to not show up blank bars container when find in page control is visible (additional constraint).
Do each for bottom and top bar setting: …

Prevent OmniBar "ghosting" and fix scroll-related glitches

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1209974629791759
CC:
1. Enable Experimental appearance in Settings -> Appearance (internal user flag is required)
2. Long press tab switcher icon to open new tab.
3. Ensure a **single** tab is created and a haptic feedback is fired.
---

Properly handle gesture recognizer events for New Tab Shortcut

---

iOS/DuckDuckGo/ExperimentalThemingManager/ExperimentalThemingManager.swift
iOS/DuckDuckGo/SwipeTabsCoordinator.swift
iOS/DuckDuckGo/TabViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210012760498370
CC:
This disables rounded corners on iPad when experimental appearance is enabled.
1. Enable Experimental Appearance in Settings -> Appearance (internal user flag needs to be enabled)
2. Check rounded corners are not visible on iPad.
---

Disable rounded corners treatment for iPad

---

iOS/DuckDuckGo/SuggestionTrayViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210031492395115
CC:
Reorder constant activation to prevent crash caused by exclusive constraints.
1. On an iPad mini simulator open our app and another app in Split View in landscape mode.  Our app should be in "phone" mode.
3. Type in to the search bar so that the suggestions appear
4. Rotate the device - the suggestion should change into a floating suggestion window
5. Repeat the above steps, but put the device into the background before rotating
6. Foreground the app - the suggestion tray has likely been closed, if not it should now be a floating tray
Medium: Could disrupt specific features or user flows - might not fix the crash detected.
* This is a speculative crash fix and might not …

re-order constraints to prevent crash

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/Localizable.xcstrings
macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarMenuButton.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard

Task/Issue URL: https://app.asana.com/0/1204167627774280/1210039888145881
Add right-click option to hide duck.ai
1. Right click the duck.ai button, click on hide it
2. Make sure the button is gone
3. Right click in the address bar, select duck.ai to show it again
4. Make sure the button is now visible
5. Click the duck.ai button, check if it opens duck.ai
Low: Minor visual changes
Regression on the fix https://app.asana.com/1/137249556945/project/1177771139624306/task/1203899219213416

Add right-click option to hide duck.ai

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
macOS/DuckDuckGo/YoutubePlayer/DuckPlayer.swift
macOS/UnitTests/TabExtensionsTests/DuckPlayerTabExtensionTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1209942314782124?focus=true
CC:
Fixes an issue on macOS 15.4+ breaking the functionality of the "Watch in Youtube" button in DuckPlayer when DuckPlayer is Enabled
1.  Use macOS 15.4
2. Go to Settings > Duck Player and set it to "Always Open Videos in Duck Player."
3. Go to Youtube.com and open a video - Confirm opens in Duck Player
4. Click "Watch in YouTube" button - Confirm opens in Youtube
- There are no unit tests for DuckPlayer navigation so this may have some unexpected side effects.  Make sure to smoke test Duckplayer in both 15.3 and 15.4
- Added tests for this specific scenario
- 
--- …

macOS: Fix issues with Watch In Youtube from Duck Player

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/Contents.json
macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/TabSeparatorNew.colorset/Contents.json
macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
macOS/DuckDuckGo/VisualRefresh/TabStyleProviding.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1209793701087217?focus=true
CC:
Adds a new tab style provider that will handle all the visual changes related to tabs. At the moment, I’ve only added changes to the divider/separator.
The new separator will be 16 pixels high (the old was 20) and a different color for dark and light.
1. Be an internal user
2. Go to Debug -> Feature Flag Overrides -> Select `visualRefresh`
3. Open a new window
4. See the difference vs production app on the tab dividers
**New dividers**
**Old dividers**
Low: Minor visual changes, small bug fixes, and improvement to existing features
The feature is behind a feature flag.
This is a simple change
Focus on providers.
—
[Definition of …

Change tab separator height and color

---

iOS/DuckDuckGoTests/ContextualDaxDialogsFactoryTests.swift
iOS/DuckDuckGoTests/ContextualOnboardingNewTabDialogFactoryTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1208837629360126?focus=true
Re-enable DaxDialogs factory tests that were flaky. 
**Background:**
Some of these tests rely on SwiftUI’s `onAppear` being triggered in order to assert certain conditions.
For onAppear to be called, the view must be part of a view hierarchy attached to a window. Simply creating a `UIHostingController` is not enough — and even presenting it from another `UIViewController` does not trigger `onAppear`. The view needs to be rendered inside a visible (non-hidden) window for the SwiftUI lifecycle to begin.
Previously, the tests were using `makeKeyAndVisible()` on a dummy `UIWindow` to satisfy this requirement. However, this unintentionally replaced the main window of the host app, …

[iOS][Onboarding] Fix flaky tests by avoid replacing the host app root window in tests

---

macOS/DuckDuckGo/Autofill/AutofillPixelEvent.swift
macOS/DuckDuckGo/Statistics/GeneralPixel.swift
macOS/DuckDuckGo/Sync/Promotion/SyncPromoPixelKitEvent.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201462886803403/task/1210000018374573
CC:
Updates some autofill pixels for a more consistent naming convention
1. Lightly test the sync promo & onboarding prompts to confirm the pixel names are updated to use `_mac` suffix as per the asana task
---

Update macoOS autofill pixels names for consistency

---

.github/workflows/ios_adhoc.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210057070554701?focus=true
This change updates ios_adhoc.yml so that it uploads dSYM archive to S3. The archive contains a timestamp
and an optional suffix, so the target file name won’t clash with any release dSYMs.
Verify that [this workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/14639278095/job/41077629475#step:11:1) uploaded dSYM archive to S3.
---

Upload dSYM for iOS adhoc builds to S3

---

SharedPackages/BrowserServicesKit/Sources/DDGSync/SyncConnectionController.swift
iOS/DuckDuckGo/SyncSettingsViewController+SyncDelegate.swift
iOS/DuckDuckGo/SyncSettingsViewController.swift
macOS/DuckDuckGo/Preferences/Model/SyncPreferences.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202926619870900/task/1210047340594635?focus=true
There has been a slight rise in macOS login errors after rolling out [✓ Align the sync connect flow with the recovery flow](https://app.asana.com/1/137249556945/task/1209569901379921).
This improves Pixel reporting to include underlying specific errors (which we already should be doing).
Low risk as just pixels and somewhat hard to test
1. Make sure you're plugged into the debugger so you can watch the console.
2. Using a proxy (e.g Charles or Proxyman) stub the `sync/login` so it returns an error of some kind
3. Go to Settings -> Sync and Backup
4. Follow the sync flow with another device
5. Check that a `...login_error...` Pixel is sent with an `e` parameter containing the …

Improve sync connection pixel reporting

---

iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarSearchView.swift
iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1209950595275304
CC:
The spacing between clear and microphone caused an illusion of having too large spacing in between. This adjusts the spacing to be negative so that it reduces this illusion.
1. Enable experimental appearance. Restart the app
2. Enable voice search and type something into the search field - microphone and clear button should be a bit closer to each other. To validate that press down both buttons simultaneously. Notice highlighted areas overlapping.
3. Disable voice search and start editing the search field - clear button should not appear to close to the separator.
Weird placement of clear …

Reduce clear button spacing when next to microphone

---

macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
macOS/DuckDuckGo/PinnedTabs/View/PinnedTabsView.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
macOS/DuckDuckGo/VisualRefresh/TabStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1209350566464644?focus=true
CC:
Increases the height of tabs so no space is left between the top and tabs.
1. Run the app, go to Debug -> Feature Flag Overrides -> and select `visualRefresh`
2. Open a new window, open some standard tabs and some pinned tabs
3. Check no space is between the top and the tabs.
Nothing comes to mind. Simple change
@ayoy check if there is something I need to change related to the logic of some pinned tabs calculations done with the old value.
— …

Visual Refresh: Increase standard and pinned tabs height

---

macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/VPNAppEventsHandler.swift
macOS/DuckDuckGo/Waitlist/VPNFeatureGatekeeper.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210072526046001?focus=true
Make some changes to that macOS won't fire unnecessary uninstall attempts.
1. Place a breakpoint [here](https://github.com/duckduckgo/apple-browsers/blob/dcd685ef93a1444d327ce313d0b03624fb650fb9/macOS/DuckDuckGo/Waitlist/VPNUninstaller.swift#L178).
2. Enable the VPN on AuthV1.
3. Enable AuthV2.
4. When launching the app again make sure the breakpoint isn't hit.
Medium: could affect VPN uninstallation when the subscription expires, which is not a huge issue since users without a subscription won't be able to connect anyway.
That this was necessary to properly expire subscriptions, but we've tested that.
NA
NA
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | …

macOS: Fix cancelled uninstall attempts

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/Localizable.xcstrings
macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
macOS/DuckDuckGo/Statistics/GeneralPixel.swift
macOS/DuckDuckGo/Tab/Model/TabCrashIndicatorModel.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabCrashRecoveryExtension.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
macOS/UnitTests/Tab/Model/TabCrashIndicatorModelTests.swift
macOS/UnitTests/TabExtensionsTests/TabCrashRecoveryExtensionTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209974112904841?focus=true
This change adds 2 pixels to track tab crash recovery, and also updates translations for the tab crash popover.
Note that both pixels have no extra parameters (just app version and pixel source).
1. Enable `tabCrashRecovery` and `tabCrashDebugTools` feature flags.
2. Crash a tab and then crash is again to cause a crash loop.
3. Verify that `m_mac_webkit_termination_loop` and `m_mac_webkit_termination_loop_daily` are fired.
4. Crash a tab one more time and click the icon to display a popover.
5. Verify that `m_mac_webkit_termination_indicator_clicked` and `m_mac_webkit_termination_indicator_clicked_daily` are fired.
Low: Minor visual changes, small bug fixes, improvement to existing …

Add pixels for Tab Crash recovery

---

macOS/DuckDuckGo/Tab/Model/Tab.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210078432720306?focus=true
Use a different private API call to reliably crash a tab if needed.
1. Enable `tabCrashDebugTools` feature flag via Debug Menu.
2. Right click a tab and select “Crash Tab” option.
3. Verify that the tab is reloaded.
I’ve tested it on 15.4 and 15.3.2.
---

Fix Tab Crash action on macOS 15.4

---

macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
macOS/DuckDuckGo/Tab/ViewModel/TabViewModel.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1142021229838617/task/1210079281181693?focus=true
When a pinned tab crashes, display a yellow alert favicon in place of the website favicon.
1. Enable `tabCrashRecovery` and `tabCrashDebugTools` feature flags.
2. Pin a tab
3. Use pinned tab context menu -> Crash Tab to crash the pinned tab
4. After it reloads, crash it again within 5 seconds so that it displays the error page.
5. Verify that the pinned tab favicon displays a yellow alert icon.
--- …

Use alert favicon for crashed pinned tabs

---

SharedPackages/BrowserServicesKit/Sources/PrivacyDashboard/BrokenSiteReporting/BrokenSiteReport.swift
SharedPackages/BrowserServicesKit/Tests/PrivacyDashboardTests/BrokenSiteReportMocks.swift
iOS/DuckDuckGo/AutofillLoginListViewModel.swift
iOS/DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift
iOS/DuckDuckGoTests/BrokenSiteReportingTests.swift
macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift
macOS/UnitTests/PrivacyReferenceTests/BrokenSiteReportingReferenceTests.swift
macOS/UnitTests/WebsiteBreakageReport/WebsiteBreakageReportTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201141132935289/task/1210044338818074?focus=true
CC:
The goal here is to add a new param to the breakage form submission. the new param should ONLY be present if the current user has PIR available AND has been through the onboarding phase (so, they currently have a profile stored).
- When PIR is not available to you, the new param should be absent when you send a report from the privacy dashboard
- But, when you are a PIR user and you have a profile stored, the field should be present and should be a "true"
--- …

pir: added a flag to breakage report

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1209793701087218?focus=true
CC:
In the past, we only showed the outline border in the address bar when the home page was opened. Now we want to show it in all states when the address bar is the first responder and the suggestions view is not being shown.
| Before | After |
| ------ | ----- |
**With FF turned on**
1. Run the app, go to Debug -> Feature Flag Overrides -> and override the `visualRefresh` FF
2. Open a new window
3. Open a site, and tap in the address bar, it should show the outline border in the address bar
**With FF turned off**
1. Run the app, go to Debug -> Feature Flag Overrides -> and remove the `visualRefresh` FF
2. Open a new window
3. Open a site, and tap in the address …

Show address bar outline borders in all states

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210076795711877
CC:
Fixes an issue when the collection containing omni bar is not refreshed properly. 
(See https://app.asana.com/1/137249556945/task/1210076795711877/comment/1210081312123646 for steps video)
1. Open https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections#cname-cloaking-protection
1. Tap on _Tracker Radar_ link
1. Scroll up after the new tab opens
2. Observe if the omni bar is visible after scrolling
Omni bar or tab can flicker or block for a split second during opening.
--- …

Update swiping tabs on navigating to new tab

---

iOS/DuckDuckGo/Refactoring/Common/OmniBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210076064653891
CC:
The state was not propagated to underlying view.  Fix was taken from PR that's already merged (https://github.com/duckduckgo/apple-browsers/pull/527).
1. Open a web page in new tab on **iPad**. 
2. Validate back and forward buttons are disabled.
3. Navigate to some link, verify back button is enabled.
4. Navigate back, verify forward button is enabled and back is disabled.
Buttons may remain in disabled state, preventing users from navigating through history.
--- …

Propagate navigation buttons state for iPad

---

iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/SuggestionTray.storyboard
iOS/DuckDuckGo/SuggestionTrayViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1210031492395115
CC:
This rolls back partial changes around `SuggestionTrayViewController` from https://github.com/duckduckgo/apple-browsers/pull/448/ which caused a crash in the background on iPad.
1. Make sure Experimental appearance is turned off in Settings. Restart app if the flag was on.
2. Edit OmniBar contents, to make suggestion tray appear.
3. Rotate the device
4. Retry these steps with favorites present.
Suggestion tray may not be aligned with OmniBar's URL field.
--- …

Revert changes around SuggestionTrayViewController

---

SharedPackages/AIChat/Sources/AIChat/Shared/AIChatConsumableDataHandling.swift
SharedPackages/AIChat/Sources/AIChat/Shared/AIChatScriptUserValues.swift
iOS/DuckDuckGo/MainViewController.swift
macOS/DuckDuckGo/AIChat/AIChatTabOpener.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatMessageHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1210025284896479?focus=true
When the user is on the SERP, we should not auto-submit the queries to duck.ai, instead it should only pre-fill the textbox.
Same steps for both iOS and macOS
1. Do a search, while you're on the SERP, click/tap the duck.ai button in the native app. It should open duck.ai with the SERP query pre-filled in the text box but not auto-submitted 
2. Start typing something in the address bar, click/tap the duck.ai button. It should open duck.ai with the query from the address bar automatically submitted.
Low: Improvement to existing features
Not auto-submitting when the user is typing the query in the address bar

macOS / iOS - Change auto-submit behavior on duck.ai

---

iOS/DuckDuckGo/ExperimentalThemingManager/ExperimentalThemingManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210065032087720
CC:
Disables the rounded corners WebView styling on iPhone.
1. Enable experimental appearance (internal user flag required). Restart app.
2. Check rounded corners are not visible for top and bottom bar setting and during pull-to-refresh.
Rounded corners could be only partially disabled.
---

Disable rounded corners treatment

---

macOS/DuckDuckGo/PrivacyDashboard/View/PrivacyDashboardViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210040780002107?focus=true
CC:
Redirect to the correct settings section when users tap ‘Disable in Settings’ for the cookie popup consent.
1. Go to https://vimeo.com/
2. Click the shield icon to open the privacy dashboard.
3. Click “Cookie Pop-up Hidden”
4. Click “Disable in Settings”
5. It should take you to the ‘Cookie Pop-Up Protection’ section instead of ‘Data Clearing'
Nothing.
I do not see any specific considerations.
Nothing specific, trivial change.
—
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/19906486 …

Redirect to correct settings on cookie popup consent

---

macOS/DuckDuckGo/Tab/Model/Tab.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabCrashRecoveryExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210080097969176?focus=true
CC: @mallexxx 
Turns out that on slower machines the webkit process termination may call navigationDidFail
callback before it calls webContentProcessDidTerminate. The former is then called with
the WebKit Termination error, and causes the termination error to be handled and webview state
altered to handle navigation error, which in fact isn’t a navigation error. That broke handling
webkit termination by the crash recovery extension.
This change updates navigationDidFail handler to return early in case of webkit termination error,
so that the termination handler can do its job.
I’ve tested it on:
* Big Sur, 
* Ventura
* Sequoia.
It was also an issue for Tak, who tested the build on his Ventura machine and …

Return early from navigationDidFail when it contains webkit termination error

---

macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210067811341178?focus=true
- Adds keyboard modifiers and middle click support to the home button
1. Right click navigation bar, show the Home button
2. Test using the home buttons with modifiers:
- ⌘-click -or- middle-click - opens a new background tab
- ⌘⇧ -or- ⇧-middle-click - new active tab
- ⌘⌥ -or- ⌥-middle-click - new background window
- ⌘⇧⌥ -or- ⇧⌥-middle-click - new active window
- when General → When opening links is On, all the actions listed above will open an Active tab instead of a Background tab by default; When ⇧ key is pressed, Background tab will be opened (the setting inverts the ⇧ modifier)
3. Set a custom Home page in the Settings, validate the above behaviors work
---
[Definition of …

Add modifiers support to the home button

---

macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210092843803521?focus=true
CC:
Fix a bug that lags opening and re-ordering standard tabs
1. Open a lot of new tabs with CMD+T (it shouldn’t be lagging)
2. Re-order them and check no lag is present
Hopefully nothing.
Nothing.
Nothing.
---

Fix lag when moving and opening standard tabs

---

SharedPackages/BrowserServicesKit/Sources/NetworkProtection/PacketTunnelProvider.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/inbox/1205736674596206/item/1210082295267504/story/1210084645776832?focus=true
CC: @miasma13 
In [this task](https://app.asana.com/1/137249556945/inbox/1205736674596206/item/1210082295267504/story/1210084645776832?focus=true) Thomas noticed that, with AuthV2, we are getting a lot of 401 errors from the macOS VPN SysExt.
**What the app was doing:**
the main app uses token T1
the main app sends T1 to the SysExt
the main app force refresh T1 and obtains T2
the main app uses T2 from now on
the SysExt receives T1 and uses T1 from now on
Issue: The first time SysExt tries to refresh the token, it fails because T1 has already been refreshed more than 1h before.
**The fix:**
the main app uses token T1
the main app sends T1 to the SysExt
the …

AuthV2 Token branching between main app and SysExt fix

---

.github/workflows/create_asana_pr_subtask.yml
.github/workflows/ios_adhoc.yml
.github/workflows/ios_pr_task_url.yml
.github/workflows/macos_pr_task_url.yml
iOS/scripts/get_tasks_in_last_internal_release.sh
macOS/scripts/get_tasks_in_last_internal_release.sh

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210099002002088?focus=true
This change fixes handling of Asana V1 inbox URLs with 'focus=true’ query parameters
in GHA workflows and bash scripts (fastlane plugin handles them correctly otherwise).
Verify that this:
```
perl -pe 's|.*https://app.asana.com/0/[0-9]+/([0-9]+)(?:/f)?|\1|; \
s|.*https://app.asana.com/1/[0-9]+(?:/[0-9a-z/]*)?/task/([0-9]+)(:?/[0-9a-z/]*)?(?:\?focus=true)?|\1|; \
s|.*https://app.asana.com/1/[0-9]+/inbox/[0-9]+/item/([0-9]+)/story/([0-9]+)(?:\?focus=true)?|\1|' \
<<< "https://app.asana.com/1/137249556945/inbox/1205736674596206/item/1210082295267504/story/1210084645776832?focus=true"
```
outputs this:
```
1210082295267504
```
---
[Definition of …

Fix handling Asana V1 inbox URLs in focused mode

---

SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
iOS/Core/PixelEvent.swift
iOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift
macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
macOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210107509728194?focus=true
The .migrationStarted adds no useful data to our dashboard but only noise. This removes it.
---

AuthV2 .migrationStarted pixel removed

---

macOS/DuckDuckGo/Bookmarks/Services/LocalBookmarkStore.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203108348835387/task/1209666483640712?focus=true
Adds a daily variant to the `bookmarksSaveFailed` pixel
You'll need to make two modifications to make testing easier.
1. Disable [this assertion](https://github.com/duckduckgo/apple-browsers/blob/8b93882266ecb0f0c223a5cb08fa5a3cff8e77ba/macOS/DuckDuckGo/Bookmarks/Services/LocalBookmarkStore.swift#L209).
2. Force-throw an error [here](https://github.com/duckduckgo/apple-browsers/blob/8b93882266ecb0f0c223a5cb08fa5a3cff8e77ba/macOS/DuckDuckGo/Bookmarks/Services/LocalBookmarkStore.swift#L317).
**Testing Steps:**
1. Launch console.app
2. Filter by "👾"
3. Run the app
4. Try adding a bookmark
5. Make sure Console.app shows something like this:
```
👾[Daily and Count-Fired] …
```

Adds a daily variant to bookmarksSaveFailed pixel

---

iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/SwipeTabsCoordinator.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210107711476853
CC:
Proper OmniBar was not attached to a selected tab, because the backing CollectionView was not refreshing the target cell. This makes sure the offset is updated properly and cells are refreshed.
Also the OmniBarVC instances were not removed properly from parent controller. This was also fixed here.
1. Perform any search on DDG SERP
2. Enable open Links In A New Tab in SERP Settings
3. Tap on any search result
4. Verify OmniBar responds to query changes, go keyboard key etc.
5. Swipe between two tabs back and forth, check if the count of OmniBarViewController instances are equal or less than number of open tabs. …

Fix OmniBar not responding to events after a link opens in new tab

---

iOS/DuckDuckGo/SyncSettingsViewController.swift
macOS/DuckDuckGo/Preferences/Model/SyncPreferences.swift
macOS/SyncE2EUITests/CriticalPathsTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210077330627570?focus=true
Fixes tests by always showing recovery screen. See context: https://app.asana.com/1/137249556945/project/414709148257752/task/1210091492822574?focus=true
https://github.com/duckduckgo/apple-browsers/actions/runs/14731588440
https://github.com/duckduckgo/apple-browsers/actions/runs/14734921075
1. Go to Settings -> Sync and Backup on both macOS and iOS
2. Make sure sync is not activated.
3. Select "Sync and Back Up This Device" on iOS.
4. Copy the recovery code.
5. Select "Turn off..."
6. Select "Sync With Another Device" again.
7. Select Manually Enter Code
8. Paste the code.
9. **You should see the recovery codes as part of the flow** 
10. Repeat steps 2 - 9 on macOS
--- …

Fix e2e sync tests by always showing recovery codes

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210115274395884?focus=true
Resolves a common build issue we've been seeing recently.
> error: remove failed remove(/Users/ddg/Library/Developer/Xcode/DerivedData/DuckDuckGo-cwxizrjfhszusnhlertkynlioqyr/Build/Products/Debug/DuckDuckGo Personal Information Removal.app/Contents/Resources/ContentScopeScripts_ContentScopeScripts.bundle/Contents/Resources/pages/new-tab/company-icons): Directory not empty (66) (in target 'DuckDuckGoDBPBackgroundAgent' from project 'DuckDuckGo-macOS')
This is caused by a script in the build steps that's called "Copy Swift Package resources".
It was implemented to resolve [this issue](https://forums.swift.org/t/swift-packages-resource-bundle-not-present-in-xcarchive-when-framework-u …

Fixes "ContentScopeScripts" building issue

---

macOS/DuckDuckGoVPN/VPNAppEventsHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207603085593419/task/1210114952670833?focus=true
Fixes an issue that was causing the VPN to start on its own during the auth v2 migration
1. To make testing easier you can force reproduce the issue by forcing [this condition](https://github.com/duckduckgo/apple-browsers/blob/0b3707d267adf0a7735002ef85fcb6e8f2e9b8fc/macOS/DuckDuckGoVPN/VPNAppEventsHandler.swift#L52) to succeed.  The same condition-change can be used to validate the original issue in `main` or disabling the guard added in this PR.
2. Please test using the "macOS VPN Agent" scheme.  You'll need to disable VPN agents following these steps in Terminal.app:
- `launchctl list | grep duck"
- Pick the ID for the agent you want to disable
- `launchtl remove <agent_id>` …

Fixes an issue that was causing the VPN to start on its own during the auth v2 migration

---

SharedPackages/BrowserServicesKit/Sources/Subscription/Storage/V2/SubscriptionTokenKeychainStorageV2.swift
iOS/Core/Pixel.swift
iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift
iOS/DuckDuckGo/Subscription/DefaultSubscriptionManager+AccountManagerKeychainAccessDelegate.swift
iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionAndNotificationTargets/InfoPlist.xcstrings
macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
macOS/DuckDuckGo/Subscription/SubscriptionManager+StandardConfiguration.swift
macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/30173902528854/task/1210090371034316?focus=true
CC: @miasma13 @diegoreymendez 
privacyProKeychainAccessError pixel's parameters were inconsistent between AuthV1, AuthV2, Old Pixel implementation and new PixelKit, now all params are aligned.
I've also added an `authVersion` to the pixel with v1 or v2.
The error sent has also been aligned, now it always is an AccountKeychainAccessError
No testing required
---

privacyProKeychainAccessError pixel parameters aligned

---

iOS/DuckDuckGo/PullToRefreshViewAdapter.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210054319052224?focus=true
CC:
When transitioning to hidden bars position, the color bled through the semi-transparent omni bar creating a bad visual effect. Additionally for sites with theme color defined as less neutral tone the effect was intensified. This removes the theme color from the bottom part of the main view.
1. Set bar position to bottom.
2. Go to a page with a theme color (e.g. github.com).
3. Scroll to hide bars
4. Verify the color of bottom bar is not affected by the theme color.
5. While performing pull to refresh verify the color matches the top section of UI.
---
[Definition of …

Prevent background color bleeding into bottom part of screen

---

macOS/DuckDuckGo/MainWindow/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1148564399326804/task/1210131003489346?focus=true
CC:
1. Run the app and open bunch of tabs (websites, new tabs and internal sites)
2. Verify CONTROL + SHIFT + TAB and CONTROL + TAB switches tabs
3. Optionally, verify other shortcuts like new tab, new window, CMD + number, etc..
Other keyboard shortcuts can break
---

Control + shift + tab shortcut fixed

---

iOS/DuckDuckGo/SwipeTabsCoordinator.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210122722180829
CC: @brindy 
#620 removed _real_ OmniBar's view controller from parent, effectively zero-ing safe area insets. This change prevents that from happening.
1. Set address bar position to top.
2. Rotate device to landscape
3. Check if OmniBarView is respecting safe area.
---

Fix OmniBar not respecting safeArea

---

.github/workflows/macos_pr_checks.yml
.github/workflows/macos_ui_tests.yml

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210139982909034?focus=true
CC:
This PR disables macOS UI test runs for all PRs (they will still run on main and release branch merges, and nightly), and moves the PR checks workflow to the free runners. These are a few minutes slower, so I'll communicate the change to the team and undo the change if the speed becomes a problem. Overall the important thing is that the UI test runs are less frequent.
---

macOS UI test workflow changes

---

macOS/DuckDuckGo/MainWindow/MainWindowController.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209813459676820?focus=true
This adds an overflow menu to the browser navigation bar. When the browser window is resized to a small width, and there are buttons pinned to the nav bar (e.g. the home button, or shortcuts like downloads, passwords), the overflow menu is displayed if the buttons overflow the available width.
* When a window/tab is opened, a new button is added to the navigation bar, or the window is resized, the overflow menu will appear if needed.
* When the overflow menu is needed, buttons will be moved one at a time from the navigation bar to the overflow menu.
* When more space is available in the navigation bar, buttons will be moved one at a time from the overflow menu back to the …

[macOS] Add overflow menu for pinned nav bar buttons

---

macOS/DuckDuckGo/History/View/Onboarding/HistoryViewOnboardingViewModel.swift
macOS/DuckDuckGo/Statistics/HistoryViewPixel.swift
macOS/UnitTests/History/View/Onboarding/HistoryViewOnboardingViewModelTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1209580853634525?focus=true
This change removes temporary pixels and updates a unit test to test the onboarding view model logic.
None
---

Remove temporary pixels for history view onboarding dialog

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210165870762384
CC:
Conditionally sets the menu on either `UIBarButtonItem` or a custom control that's set as a custom view.
1. Create a navigation history by navigating to a bunch of web pages in a single tab
2. Long press go back button - history menu should show up
3. Navigate back - long press go forward button - history menu should show up
4. Repeat with (or without) experimental appearance enabled.
Could break the same feature on production (regular) appearance.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | …

Fix back/forward menu not showing up when visual updates are enabled

---

SharedPackages/BrowserServicesKit/Sources/NetworkProtection/PacketTunnelProvider.swift
SharedPackages/BrowserServicesKit/Sources/Networking/Auth/OAuthClient.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/AppStore/AppStorePurchaseFlowV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/Extensions/SubscriptionManagerV2+SubscriptionTokenHandling.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/Managers/SubscriptionManagerMockV2.swift
SharedPackages/BrowserServicesKit/Tests/NetworkingTests/Auth/OAuthClientTests.swift
iOS/DuckDuckGo/SubscriptionDebugViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/inbox/1205736674596206/item/1210153624525907/story/1210153788477661?focus=true
CC:
A couple of improvements to the AuthV2 token adoption:
- `.missingTokens` error has been renamed `missingTokenContainer`
- `.missingRefreshToken` has been removed and replaced with a clearer `.missingTokenContainer`
The force refresh is now part of the adoption process, this shouldn't change anything but 
Normal Subscription + VPN operations
---

AuthV2 token adoption improvements

---

iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarView.swift
iOS/DuckDuckGo/SwipeTabsCoordinator.swift
iOS/DuckDuckGo/ToolbarStateHandling.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1209879279509902
CC:
Toolbar horizontal spacing is adjusted to align with OmniBar buttons. In order to fix safe area alignment for the OmniBar, changes containing a fix for OmniBar disappearing were cherry-picked from #657.
1. Enable experimental appearance. Restart the app.
2. Set address bar to bottom position.
3. Verify left-most and right-most buttons align with buttons on the toolbar.
4. Rotate to landscape and verify alignment.
5. Check the same on a device with different screen size.
**Disappearing OmniBar fix:**
1. Open example.com
2. Rotate device to landscape
3. Scroll to hide the bars, verify omni bar is not disappearing from container. (See [task](https://app.asana.com/1/137249556945/project/414709148257 …

Fix toolbar and OmniBar alignment

---

iOS/Core/PixelEvent.swift
iOS/DuckDuckGo/TabViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210184959177115?focus=true
Sometimes on switching tabs, the view of that selected tab is blank even if the tabs url is reloaded. We've been unable to replicate this, so to try and debug it, we'll add some short-term debug pixels to see if the webView:
- Isn't in the view hierarchy
- Isn't in the window
- Is hidden
- Has a zero frame size
1. Run iOS with the debugger connected
2. Open a few tabs and switch between them
3. Make sure that none of the pixels are firing
Low: Just simple pixels
They're the wrong pixels / they don't show up any issue we're looking for
Just the pixels mentioned
- How does this impact privacy/security?
As mentioned in the Privacy triage, the only …

iOS: Add debug pixels for potential webView issues

---

.github/workflows/bsk_pr_checks.yml
.github/workflows/ios_pr_checks.yml
.github/workflows/macos_pr_checks.yml
SharedPackages/BrowserServicesKit/scripts/report-failed-unit-test.sh
iOS/scripts/report-failed-unit-test.sh
macOS/scripts/report-failed-unit-test.sh

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210188079291154?focus=true
This change updates report-failed-unit-tests.sh scripts to exit cleanly on empty input.
This deals with a changed behavior of GHA runners where no input would cause the script to fail.
---

Fix the script reporting failed unit tests to Asana so that it gracefully handles empty input

---

.github/workflows/macos_pr_checks.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210190001303534?focus=true
Use distinct names for unittests.xml artifacts for macOS Sandbox and non-Sandbox flavors.
Verify that [macOS PR Checks workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/14907598981?pr=694) published 2 unittests.xml artifacts, for Sandbox and Non-Sandbox flavor.
---

Fix macOS PR checks artifacts

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/PrivacyConfigurationData.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1163321984198618/task/1209286025185882?focus=true
CC: @jonathanKingston 
Currently, the privacy config is encoded as JSON to be injected into the C-S-S script. This allows C-S-S to use values from the config after injection.
The current implementation 'pretty prints' the config data (i.e. adding tabs and new lines so it is human readable). This is not needed, as the data is just directly consumed by the JS parser after injection. Switching to this compact encoding reduced the config size by 49% (350k -> 180k), and the resulting C-S-S script size by 27% (638k -> 468k).
1. Validate that C-S-S is still working, e.g. by checking that the tests on https://privacy-test-pages.site/features/element-hiding/ still pass. …

Do not pretty print JSON injected into C-S-S script.

---

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Model/DataBroker.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/SecureVaultStorage/DataBrokerProtectionDatabaseMigrationsProvider.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/SecureVaultStorage/DataBrokerProtectionDatabaseProvider.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/SecureVaultStorage/Mappers.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/SecureVaultStorage/SchedulerSchema.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCoreTestsUtils/Mocks.swift
SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProfileQueryOperationManagerTests.swift
SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionDatabaseProviderTests.swift
SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionUpdaterTests.swift
SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/MapperToModelTests.swift
SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/MismatchCalculatorUseCaseTests.swift
SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/OperationPreferredDateUpdaterTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1205508328452434?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1209813786547143
CC:
Adds the new `etag` column to the BrokerDB table in a new migration step.
Scenario 1:
1. Run PIR as a new user
2. Open the DB browser
3. Expect to see the DataBrokers table with the new `etag` column
Scenario 2:
1. Run PIR as an existing user
2. Open the DB browser
3. Expect to see the DataBrokers table with the new `etag` column
Database migration
--- …

Remote broker delivery: Add eTag to BrokerDB

---

SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptHandlerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1209882303470922/task/1210209647989736?focus=true
This change fixes how inactive subscriptions are reported to SERP via SubscriptionUserScript.
1. Use this privacy config override for testing: https://duckduckgo.github.io/privacy-configuration/pr-3106/v4/macos-config.json
2. Set a breakpoint in SubscriptionUserScript.swift:51.
3. Enter a state where you have an inactive subscription.
4. Open https://duckduckgo.com (root domain URL).
5. Verify that the app stops at the breakpoint and that the function returns a subscription object with `isSubscribed: true`.
None: simple bugfix
--- …

Fix returning inactive subscription to the user script

---

macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
macOS/DuckDuckGo/VisualRefresh/TabStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210166303108615?focus=true
Visual refresh for hover state of unselected tabs
1. Set internal user and turn on the visual refresh feature flag
2. Open a new window with bunch of tabs, mouse mouse over them and verify the visual style is aligned with [Figma](https://www.figma.com/design/hiyClFzZVkiYfLicSaN3iJ/Toolbar-Spec-2025?node-id=36-0&m=dev)
3. Turn of the feature flag, open a new window with bunch of tabs and verify the design is unaffected
Note: I believe the label in the tab should be centered vertically. I think this is going to be covered in other PRs, so I rather didn't touch this logic to avoid conflicts. Let me know if you'd like me to handle it too
---
[Definition of …

Tab selection visual refresh

---

macOS/UITests/DownloadsTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210206165312650?focus=true
This change attempts fixing downloads UI test by scrolling the settings view in order to reveal
downloads-related checkbox on the screen.
Verify that [UI tests workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/14964878651) passes.
---

Fix Downloads UI test

---

macOS/DuckDuckGo/Fire/View/FirePopoverViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210218566503698?focus=true
This change updates Fire Popover so that when a new Fire Window is requested from the popover,
the popover is automatically closed.
1. Click Fire Button
2. Click “Open new Fire Window” button in the Fire popover.
3. Verify that the Fire Window is opened and that the Fire popover is closed.
Low: Minor visual bug fix.
Please note that the app will fail an assertion after closing Fire Window which is [a known issue tracked elsewhere](https://app.asana.com/1/137249556945/project/1201037661562251/task/1210156034682808?focus=true).
— …

Close Fire popover when opening new Fire Window

---

macOS/DuckDuckGo/Common/Localizables/UserText+NetworkProtection.swift
macOS/DuckDuckGo/Localizable.xcstrings
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarPopoverManager.swift
macOS/DuckDuckGo/Preferences/Model/VPNPreferencesModel.swift
macOS/DuckDuckGo/Preferences/View/PreferencesVPNView.swift
macOS/DuckDuckGoVPN/DuckDuckGoVPNAppDelegate.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203108348835387/task/1209396183178103
Removes the app exclusions feature flag from our codebase.  This flag is no longer needed as it's been rolled out and enabled for a while now.
1. Run the Sparkle target and make sure PrivacyPro is enabled.
2. You should see app exclusions in VPN settings as per the screenshot above.
3. Change Debug > Feature Flag Overrides > networkProtectionAppStoreSysex
5. Reopen VPN settings and make sure exclusions are always shown regardless of the status of said flag.
6. Uninstalling and re-enabling the VPN should always keep showing exclusions.
1. Run the App Store target and make sure PrivacyPro is enabled.
2. You should see app exclusions in VPN settings as per the screenshot above.
3. Change Debug …

Removes the app exclusions feature flag locally

---

iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarSearchView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210206286741189
CC:
PrivacyContainer was moved down in the view hierarchy so other views were intercepting touches.
1. Enable experimental appearance. Restart the app.
2. Open website with protections enabled. 
3. While tracker animation is ongoing tap on url area to enter edit mode. Animations should be canceled.
4. Open Privacy Dashboard by tapping shield. 
5. Switch protections off. Wait for the site to reload.
6. Open Privacy Dashboard by tapping the shield.
7. Tap on different places on URL bar and confirm editing is started.
--- …

Bring privacy info container to front to enable touches on the shield icon

---

macOS/DuckDuckGo/Bookmarks/View/BookmarkOutlineCellView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210231998767740?focus=true
This change skips applying sizing logic for narrow frames of BookmarkOutlineCellView until it’s added to the view hierarchy.
This ensures that the cell view is correctly sized before being displayed in a popover, while not breaking
existing logic to handle narrow application windows (when cells are used inside Bookmarks Manager).
1. Add bookmarks folder to boomarks
2. Show bookmarks bar
3. Click on a folder
4. Verify that bookmarks are not truncated.
5. Open Bookmarks Manager and shrink the window horizontally. Verify that bookmarks outline view (side panel) is correctly shrank.
---
[Definition of …

Fix rendering bookmarks bar popovers

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210239511758406?focus=true
This change adds a new observer to always layout suggestions window when the parent window frame changes.
It replaces the existing solution that would layout suggestions window only when address bar text field frame changed.
1. Type in the address bar to display autocomplete suggestions window.
2. While suggestions window is shown, resize the app window horizontally and vertically and move it freely. Verify that the suggestions window always follows address bar.
--- …

Layout suggestions window every time the window is resized

---

iOS/DuckDuckGoTests/FaviconsHelperTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210256798348696?focus=true
CC:
This PR fixes flaky favicon tests.
2. Run the test locally many times and check that it always passes - you can do this by right clicking the test indicator and selecting "Run Repeatedly"
You can force this failure with the original code by checking out `main`, commenting out the `clearDiskCache()` functions, and running the test suite. This is what was technically happening before, since `clearDiskCache()` wasn't able to complete in time.
None, only affects the test suite and the test was already flaky anyway :)
--- …

Fix flaky favicon tests

---

SharedPackages/BrowserServicesKit/Package.resolved
SharedPackages/DataBrokerProtectionCore/Package.resolved
macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/Application/AboutPanel.swift
macOS/DuckDuckGo/Menus/MainMenuActions.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210253905192916?focus=true
Add a static function to AboutPanelController that’s responsible for finding a panel on screen,
and only create a fresh one if not found.
1. Select Main Menu -> DuckDuckGo -> About DuckDuckGo
2. Verify that it presents the “About” panel
3. Don’t close the panel and repeat step 1. Verify that no new panel was created.
4. Don’t close the panel, activate the main app window and repeat step 1. Verify that the about panel was brought to front.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552 …

Only display 1 about panel at any given time

---

iOS/DuckDuckGo/SwipeTabsCoordinator.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210229858278888
CC: @amddg44 
Because "real" OmniBar was removed from the cell it probably meant it got reassigned to another one. This adds another reuse identifier distinguishing between the real and template OmniBars so that cells don't get cross-reused for these two cases.
More testing scenarios can be found in the [task](https://app.asana.com/1/137249556945/project/414709148257752/task/1210229858278888).
1. Create more than 3 tabs. Make sure there's no NTP tab at the end.
1. Swipe to the first tab.
1. Swipe to the last tab.
1. Drag more to create a new tab, but don't finish the gesture.
1. Make sure OmniBar is visible all the time. …

Use two reuse pools for OmniBar cells

---

iOS/DuckDuckGo/TabViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1210251291351493?focus=true
There's a rare bug where the webView appears to be invisible occasionally on navigating to a tab. Some pixels were added to fire from the iOS TabViewController when the webView is hidden, not in the hierarchy etc. After releasing these, I found that there were a few fired when webView.isHidden. However, this may be the case when an error is showing.
Goal
Rule out cases where the tab's error view is showing (with text). Only fire it if:
- The error is invisible
- The error is visible but contains no text
- Make sure you're running while plugged into the debugger
- Visit https://privacy-test-pages.site/network-error/drop
- Check that the `m_debug_webview_in_visible_tab_hidden` is …

Hidden webView pixel to fire only when error is invisible

---

macOS/DuckDuckGo/MainWindow/MainViewController.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210129405457243?focus=true
CC:
Expand the address bar height when it gets focused. The size should got back to normal when the address bar loses focus.
1. Set internal user state
2. Go to Debug -> Feature Flag Overrides, and override the `visualRefresh`
3. Open a new window, and select and unselect the address bar
4. Check the address bar height increases when it is focused, and it is back to normal when it loses focus
5. This should happen for all pages (new tab, home page, default)
6. Remove the feature flag override and check it doesn’t happen
My …

macOS visual refresh: Increase address bar height when is focused

---

macOS/DuckDuckGo/Tab/View/BrowserTabViewController.swift
macOS/IntegrationTests/Onboarding/BrowserTabViewControllerOnboardingTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210144780372343?focus=true
1. Go to debug menu -> Reset Data -> Reset Contextual onboarding
2. Go to DuckDuckGo you should see the first dialog
3. Continue until the tracker dialog
4. Open a new tab
5. go back to the original put the app out of focus and on focus again 
6. check the dialog does not reappaer
7. Navigate to another site -> you should see the fire dialog
8. Navigate to another site (so that you see the high five dialog on a site)
9. dismiss the high five dialog
10. Open a new tab
11. Go back to the previous tab
12. move app out and in focus again
13. The dialog should not appear anymore
<!— 
High: Could affect user privacy, lose user data, …

fix onboarding bug

---

macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210156034682808?focus=true
This change ensures that TabBarViewController subscribes to child windows always when its view has a window,
by moving the subscription from viewWillAppear to viewDidAppear.
1. Verify that using fire button and closing Fire Window doesn’t stop at an assertion when the app is run from Xcode.
2. Verify that this change doesn’t break the fix introduced in https://github.com/duckduckgo/apple-browsers/pull/483
--- …

Fix assertion in debug when playing Fire animation on macOS

---

macOS/DuckDuckGo/Application/AppDelegate.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210317072100185?focus=true
CC: @ayoy 
1. Launch the app.
2. Ensure that ”m_mac_daily_active_user” pixel is fired in the console log.
3. Put the app in background and foreground it again.
4. Ensure that this time “m_mac_daily_active_user” pixel is skipped in the console log.
Low
Wrong reporting of app launches
Checked the [following dashboards](https://dub.duckduckgo.com/duckduckgo/grafana-snapshots/search?q=%22m.mac.daily.active.user%22)
- **O-G:** Change is part of this objective.
- **O-J (macOS Pixels and macOS Errors):**:  Dashboards would also benefit from it
- **O-R:** This pixel is misused anyway. Needs a proper “launch” pixel, not a daily pixel as it is used for crash rate. O-R is …

Move app launch pixel to applicationDidBecomeActive

---

iOS/DuckDuckGo/TabSwitcherViewController.swift
iOS/DuckDuckGo/TabsModel.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210323647312903?focus=true
CC:
This PR updates the tab switcher to reload its collection view when the list of tabs change. This change is because the tab switcher doesn't do any deliberate reloads otherwise, but URLs can be modified when it's active, so the fix is to reload its data source more proactively.
1. See [Asana](https://app.asana.com/1/137249556945/project/1199333091098016/task/1210323647312903?focus=true) for steps
2. Check that tab persistence works as expected, just to make sure that `@Published` didn't have an effect on `NSCoding`
--- …

[Release PR] Reload the tab switcher when tabs change

---

macOS/DuckDuckGo/TabBar/View/Base.lproj/TabBar.storyboard
macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210331228149927?focus=true
CC:
Increases the size of the fire button to 32x32, to mimic the designs. It also aligns the fire button with the more options button, as shown in the following screenshot.
1. Set internal user state
2. Go to Debug -> Feature Flag Overrides, and turn the `visualRefresh` flag on
3. Reset the application
4. Check the fire button is aligned with the more options menu
5. Also, check the hover area of the fire button increases
6. Remove the flag and re-start it again
7. Check that doesn’t happen when the FF is off
This goes to production without the FF.
— …

macOS Visual refresh: Align fire button with more options menu

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210331228149931?focus=true
CC:
Updates the corner radius of the address bar to follow the new designs:
1. Set internal user state
2. Go to Debug -> Feature Flag Overrides, and override the `visualRefresh` flag.
3. Reset the application
4. Check the address bar have more curved corner radius and it fits better with the privacy shield and ai chat buttons
5. Remove the override flag, and restart the application
6. Check the address bar size is back to normal
The change goes to production without the FF.
Nothing specific
Nothing specific
—
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f …

macOS Visual Refresh: Update address bar radius for new style

---

iOS/DuckDuckGo/AutocompleteView.swift
iOS/DuckDuckGo/AutocompleteViewController.swift
iOS/DuckDuckGo/AutocompleteViewModel.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210109852223178
CC:
Updates the visual appearance of autocomplete. Note the change of the icon color to secondary is expected for both styles.
For the changes to be fully in-line [icons update](https://app.asana.com/1/137249556945/project/1206226850447395/task/1209809752047351?focus=true) must be done. However current design works with existing icons as well.
1. Enable experimental appearance. Restart device.
2. Check if autocomplete looks like on the spec in the [task](https://app.asana.com/1/137249556945/project/1206226850447395/task/1210109852223178?focus=true).
3. Turn off experimental appearance, see if regular appearance is not modified.
⚠️  Note the difference of alignment on a real …

Update visuals in Autocomplete list

---

iOS/DuckDuckGo/AIChat/AIChatViewControllerManager.swift
iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1210345665934128?focus=true
Fix issue opening duck.ai links from tab switcher
1. Go to the tab switcher
2. Search for “iphone prices"
3. Tap on a link
4. The tab switcher should be dismissed and you see the selected page
Breaking up some state outside of the tab switcher when tapping on links

Fix issue opening links

---

macOS/DuckDuckGo/MainWindow/MainView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210331120635171?focus=true
Fixes an issue that caused the bookmarks icon to blink when switching tabs.
1. Load a site in a tab.
2. Create another tab and switch to it.
3. When going back to the tab with the site loaded you'll see the bookmarks icon blinking.
Low
I don't think anything should.  But worst thing that could happen is I'm calculating visibility wrong for the icon.
Ensure the icon behaves correctly when moving the mouse into and outside of the address bar area.
NA
--- …

Fixes a bug with the bookmarks icon blinking when switching tabs

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/VisualRefresh/ColorsProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1142021229838617/task/1210355890591502?focus=true
CC:
1. Set internal state
2. Be sure that the `visualRefresh` flag override is not turned on by going to Debug -> Feature Flag Overrides.
3. Open a New Tab, check that the address bar has the outline border
4. Open a Fire Window, check that the address bar has the outline border
5. On a new tab or home, focus and remove focus from the address bar, the Dax logo to the left of the address bar should not flicker.
This gets shipped to users.
Nothing in particular
Nothing in particular
— …

Fix outer border color in address bar and flickering on dax logo on NTP

---

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/TabBorderView.swift
iOS/DuckDuckGo/TabViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210340616083163?focus=true
CC:
* Adds border to top and bottom edge of the Web View. This helps with marking the web content / bar boundary.
* Design can be found [here](https://www.figma.com/design/triNDLtPcx4by8Hsw9CzYt/🖍%EF%B8%8F-2025-Visual-Design-Update---1-Tap-AI-ChatOS---Android?node-id=7466-72205&p=f&m=dev).
1. Enable experimental appearance. Restart the app.
2. Open NTP, make sure borders are not visible.
3. Browse to any URL. Observe top and bottom edges are visible near the bars.
4. Scroll the website. Border should be moving along with the content.
5. Turn off experimental appearance. Restart the app. No border should be visible on website.
Low: Minor visual changes, small bug fixes, improvement to …

Draw top and bottom edge for webView

---

SharedPackages/DesignResourcesKitIcons/Package.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210376606467197?focus=true
Swift Tools 6.0 are not available on macOS 14 and 13 where UI tests are run in CI.
1. Verify that CI is green
2. Verify that [this UI tests workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/15247613708) is green.
---

Use Swift Tools 5.9 in DesignResourcesKitIcons

---

macOS/DuckDuckGo/Preferences/Model/AboutPreferences.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203108348835387/task/1210386545302221?focus=true
Ensure "Restart to Update" works well again.
1. Decrease the build number in `BuildNumber.xcconfig`
2. Run the app
3. You'll need to enable `autoUpdateInDEBUG` for debug builds
4. Check for updates, and when "Restart to Update" comes up, ensure it restarts the app.  Please be advised that the restart can appear to be a crash when running the App in Xcode.
Low.
Nothing I can think of with this specific change.
NA
NA
---

Changes the action for the restart-to-update button

---

macOS/UITests/BookmarksAndFavoritesTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210384592437146?focus=true
This change fixes a UI tests that uses coordinates to find menu items.
It got broken after adding “Open in New Fire Window” menu action.
Verify that [this UI tests workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/15286989981) is green.
---

Fix Bookmarks bar UI test

---

iOS/DuckDuckGo/HomeMessageView.swift
iOS/DuckDuckGo/HomeMessageViewModel.swift
iOS/DuckDuckGo/HomeMessageViewModelBuilder.swift
iOS/DuckDuckGo/NewTabPageMessagesModel.swift
iOS/DuckDuckGo/NewTabPageView.swift
iOS/DuckDuckGo/NewTabPageViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210368065427216?focus=true
CC:
This adjusts how Remote Message looks on NewTabPage when experimental appearance is on:
* Adjusted shadow parameters ([figma](https://www.figma.com/design/3W4vi0zX8hrpQc7zInQQB6/%F0%9F%8E%A8-Global-Colors---Styles?node-id=6152-21378&m=dev))
* Adjusted padding
* Adjusted corner radius
1. Set endpoint of RemoteMessagingClient to custom model (e.g. http://www.jsonblob.com/api/1377309266414854144)
2. To make testing of different cases easier disable marking message as seen by commenting out `homePageMessagesConfiguration.didAppear(homeMessage)` in `NewTabPageMessagesModel.viewDidAppear`
3. Make sure there's no difference when experimental updates are disabled
4. Turn on experimental …

Update RMF design for visual updates

---

macOS/DuckDuckGoVPN/VPNAppEventsHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207603085593419/task/1210406352665274?focus=true
Fixes an issue that was causing the VPN to start when it shouldn't, during the AuthV2 migration.
1. Enable the VPN on AuthV1.
2. Stop the VPN.
3. Switch to AuthV2
4. Relaunch the app
Ensure the VPN won't connect.
Medium.
The VPN restart logic is tricky.
NA
Just ensure the changes make sense.  We'd like the VPN to restart when already connected and not vice-versa.
---

Fixes the VPN restart logic for the authv2 migration

---

.maestro/privacy_tests/09_navigation_with_refresh.yaml
.maestro/release_tests/refresh.yaml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210408665240547?focus=true
CC: @brindy 
Update for automated tests after bringing back refresh button to the address bar (https://github.com/duckduckgo/apple-browsers/pull/859).
`browsing-menu` test was introduced along with the original refresh button removal, so I renamed it and added a check for it being present in the address bar now instead of browsing menu.
1. Make sure E2E tests pass (https://github.com/duckduckgo/apple-browsers/actions/runs/15332458391)
--- …

Fix e2e tests after refresh button changes

---

macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
macOS/DuckDuckGo/VisualRefresh/TabStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210441628866875?focus=true
CC:
There was some comments about pinned tabs looking weird, we decided to increase the width to make them look different without losing the corner radius.
1. Run the application
2. Check pinned tabs are wider than the production visual refresh
| Before | After |
| ------ | ----- |
Nothing.
—

macOS Visual Refresh: Increase pinned tab width

---

macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/SurfaceBackdrop.colorset/Contents.json
macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/SurfaceCanvas.colorset/Contents.json
macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/SurfacePrimary.colorset/Contents.json
macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/SurfaceSecondary.colorset/Contents.json
macOS/DuckDuckGo/Assets.xcassets/Colors/New-Theme-Colors/SurfaceTertiary.colorset/Contents.json

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210438924680754?focus=true
CC:
There was some feedback around active tabs were hard to differentiate from non-active. Bryan proposed some new colors for the `surface` palette. This PR adds the new values for those colors.
1. Run the app
2. Go to Settings -> Appeareance -> Select Dark mode
3. Open a lot of tabs, the current active tab should be more noticeable than the non-active ones.
Nothing.
Nothing.
Nothing.
— …

macOS Visual Refresh: Update surface dark colors

---

.maestro/release_tests/favorites.yaml
iOS/DuckDuckGo/AutocompleteView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210447750549951?focus=true
CC:
Adds identifiers for autocomplete list and uses it instead of icon name in the test.
1. Make sure favorite E2E test pass
---

Fix favorites E2E test

---

iOS/DuckDuckGo/LargeOmniBarState.swift
iOS/DuckDuckGoTests/LargeOmniBarStateTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210464532440978?focus=true
CC:
Respect duck.ai button settings
1. Disable duck.ai in settings
2. Make sure it’s not visible in the app

Show accessory button based on duckAI setting on iPad

---

macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
macOS/DuckDuckGo/Tab/Model/Tab.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
macOS/DuckDuckGo/VisualRefresh/TabStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210438924680753?focus=true
CC:
In the Ship Review, we added some logic to hide adjacent separators when hoving a standard tab. Now, we are adding the same for pinned tabs.
https://github.com/user-attachments/assets/c82f9e67-3162-4e28-b692-4ab8869be6f7
1. Run the app
2. Pin some tabs
3. Hover the pinned tabs, check that adjacent separators are hidden when hovering.
4. Turn the visual refresh flag off (Debug -> Feature Flags Overrides, visualRefresh)
5. Check that adjacent separators are always visible on legacy UI
This goes to production.
Nothing specific
Nothing specific
—
[Definition of …

macOS Visual Refresh: Hide adjacent separators when hovering pinned tabs

---

macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/Localization/Localizable.xcstrings

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210385325328078?focus=true
CC:
1. Edit macOS Browser scheme and set a different App language from English. 
2.Launch the App.
3. Ensure the copy reflects the changes discussed in [Asana](https://app.asana.com/1/137249556945/task/1210420724089523/comment/1210454186090892?focus=true)
---

[macOS] Add Translations for SAD/ATT prompts

---

macOS/DuckDuckGo/LoginItems/LoginItemsManager.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/VPNAppEventsHandler.swift
macOS/UnitTests/NetworkProtection/Mocks/MockLoginItemsManager.swift
macOS/UnitTests/NetworkProtection/VPNAppEventsHandlerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203108348835387/task/1210470416862601?focus=true
We want to disable the VPN login item when the subscription is expired even if the login item was manually disabled by the user in System Settings.  This helps ensure the VPN menu app won't load when enabled back by the user.
1. Connect the VPN so login items are loaded.
2. Disconnect it.
3. Restart the app, ensure the login items are restarted but not disabled.
4. Force [this](https://github.com/duckduckgo/apple-browsers/blob/06a80cdad3e04dc878cc096e4179be5a823a4869/macOS/DuckDuckGo/Waitlist/VPNFeatureGatekeeper.swift#L62) to return false.
5. Go to System Settings > General > Login Items & Extensions, and disable our login item
6. Start the App again
7. Go to System Settings > …

macOS: Disable VPN login items on expired subscriptions even if they are manually disabled by the user

---

.github/actions/asana-failed-pr-checks/action.yml
.github/workflows/bsk_pr_checks.yml
.github/workflows/dbp_pr_checks.yml
.github/workflows/ios_pr_checks.yml
.github/workflows/macos_pr_checks.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210472527506627?focus=true
This change fixes calling asana-failed-pr-checks action by passing the GitHub token as a required parameter.
---

Pass GitHub token to asana-failed-pr-checks action

---

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/RemoteMessagingConfigMatcherProvider.swift
iOS/DuckDuckGoTests/MockInternalUserDecider.swift
iOS/DuckDuckGoTests/RemoteMessage/RemoteMessagingConfigMatcherProviderTest.swift
iOS/DuckDuckGoTests/Subscription/SubscriptionFeatureFlagMappingTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210454132810101
CC: @amddg44 
Uses value established at launch instead of live feature flag. This prevents prematurely showing visual updates remote message that's based on `visualUpdates` subfeature, in case when the visual updates are not yet applied at runtime (app was not relaunched).
1. Run the app, override the remote config with `https://www.jsonblob.com/api/1379474116607926272` (visualUpdates flag enabled)
2. In Debug -> Remote Messaging reset all to start with a clean state.
3. Override RMF config to https://staticcdn.duckduckgo.com/remotemessaging/config/staging/pre/ios-config.json (visual updates message from https://github.com/duckduckgo/remote-messaging-config/pull/189)
4. In …

Prevent showing remote message before visual updates are applied in runtime

---

macOS/DuckDuckGo/VisualRefresh/AddressBarStyleProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210467121144321?focus=true
CC:
We want to increase the size of the suggestions rows from `28` to `32`.
1. Run the app
2. Type something into the address bar
3. Check the size of the suggestion table view
4. Compare it with the production app
5. Check this one is taller
Nothing
Nothing
—

macOS Visual Refresh: Increase suggestion row size from 28 to 32

---

SharedPackages/DesignResourcesKitIcons/Sources/DesignResourcesKitIcons/DesignSystemImages+Glyphs.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
macOS/DuckDuckGo/Permissions/View/PermissionButton.swift
macOS/DuckDuckGo/VisualRefresh/AddressBarPermissionButtonsIconsProviding.swift
macOS/DuckDuckGo/VisualRefresh/IconsProviding.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210388032589569?focus=true
CC:
Updates some of the address bar permissions icons to the new ones. It doesn’t update the microphone and the camera ones, because those two are being revisited. 
This also fixes the size of those permission buttons, now the buttons have the correct size of 28 instead of 32.
1. Open the application
2. Go to Google Maps, and try to fetch location (but tapping the locate me button)
3. The location icon should appear in the address bar
4. Check the size when hovering matches the privacy shield hover (this means they have the same padding)
5. The same with the zoom icon
6. Go to Debug, Feature Flag Overrides, and tap the `visualRefresh` to disable the flag, kill …

macOS Visual Refresh: Update permission buttons to new icons and fix size

---

iOS/fastlane/Fastfile

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210498413174262?focus=true
This change forces read-only mode for fastlane match calls due to the breakage recently
introduced by Apple: https://github.com/fastlane/fastlane/issues/29499
Verify that AdHoc build [from `dominik/fastlane-fix` branch](https://github.com/duckduckgo/apple-browsers/actions/runs/15534620889) works.
Verify that AdHoc build [from `main` branch](https://github.com/duckduckgo/apple-browsers/actions/runs/15534616163) fails to build.
--- …

Use read-only mode when syncing signing assets for iOS AdHoc builds

---

SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift
iOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/Subscription/AuthV2PixelHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210453926427230
- now all pixels related to invalid refresh token detected and mitigation are managed by the pixel handler
- in case of an unrecoverable state the logout is performed only after the failed recovery attempt
---

Invalid refresh token detected and mitigation pixels improved

---

.github/actions/asana-failed-pr-checks/action.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210503429415007?focus=true
This change fixes asana-failed-pr-checks action to only map GitHub user to Asana user ID
when creating Asana task. Closing Asana task doesn’t require any Asana user ID and that
ID has never been passed to the action when closing the task.
🤷  trust me
---

Fix auto-closing PR Checks failed Asana tasks

---

SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionAuthV1toV2Bridge.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManager.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionTokenProvider.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/Managers/SubscriptionAuthV1toV2BridgeMock.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/Managers/SubscriptionManagerMock.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/Managers/SubscriptionManagerMockV2.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+CustomURL.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+Redirect.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/PrivacyProSubscriptionV2IntegrationTests.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Authentication/DataBrokerProtectionSubscriptionManaging.swift
iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift
iOS/DuckDuckGo/AppServices/DBPService.swift
iOS/DuckDuckGo/AppServices/VPNService.swift
iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
macOS/DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/DeveloperIDTarget/NetworkProtectionSubscriptionEventHandler.swift
macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
macOS/DuckDuckGo/Subscription/SubscriptionManager+StandardConfiguration.swift
macOS/DuckDuckGo/Waitlist/VPNFeatureGatekeeper.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205842942115003/task/1210449733678950
CC: @miasma13 
- `isUserAuthenticated` now relies on cached (UserDefaults) values and can't fail
- `func isFeatureEnabledForUser(feature: Entitlement.ProductName)` The entitlements check used by the VPN, is now relying on cached user entitlements and can't fail
Subscription + VPN functioning as expected
High, the subscription and VPN could be impacted
---

AuthV2 - isUserAuthenticated and entitlements check improvements

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210490815748267
- load localhost
- tab over somewhere else
- back to localhost tab
- check the favicon on the address bar is the little globe
---

fix local host favicon image

---

iOS/DuckDuckGo/NewTabPageView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210379416433601/task/1210482721397279?focus=true
CC:
This reverses the performance issue caused by using UIKit's UIScrollView inside a SwiftUI stack.
1. Add many (> 500 favorites) 
2. Open tab switcher and go back to new tab page. Make sure there's no noticeable delay.
3. 
The performance issue may still be there, but manifesting in a different way, but that's unlikely since the previous implementation was live for a long time on production and didn't show any kinds of performance issues.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | …

Use SwiftUI ScrollView instead of UIScrollView on NewTabPage

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Feedback/Resources/internal-feedback-autofiller.js
macOS/DuckDuckGo/Tab/Model/Tab+Navigation.swift
macOS/DuckDuckGo/Tab/TabExtensions/InternalFeedbackFormTabExtension.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/42792087274227/task/1210519390344797?focus=true
This change adds a tab extension that runs small JS script on Internal Feedback Form page
in order to prefill fields like platform, OS version and app version, so that internal users
don’t need to fill them out themselves. The tab extension is only active for internal users
and otherwise is transparent to regular users.
1. Launch the app and set internal user state.
2. Open Hamburger menu -> Send Feedback -> Send Browser Feedback. Perform Duo authentication if needed. Verify that you land on Internal Feedback Form page with macOS browser, your OS version and app version prefilled.
3. Repeat the test with the App Store app and verify that you see app version with `(App Store)` …

Autofill known fields in the Internal Feedback Form

---

macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/Feedback/View/FeedbackPresenter.swift
macOS/DuckDuckGo/Feedback/View/FeedbackViewController.swift
macOS/DuckDuckGo/NewTabPage/Features/ActiveRemoteMessageModel+NewTabPage.swift
macOS/DuckDuckGo/RemoteMessaging/ActiveRemoteMessageModel.swift
macOS/DuckDuckGo/UnifiedFeedbackForm/UnifiedFeedbackFormViewController.swift
macOS/DuckDuckGo/Windows/View/WindowControllersManager.swift
macOS/UnitTests/NewTabPage/NewTabPageCoordinatorTests.swift
macOS/UnitTests/RemoteMessaging/ActiveRemoteMessageModelTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210510946680683?focus=true
CC:
We need to support the `navigation` action on macOS for remote messages. The new remote message we will show for the visual updates needs to navigate to the feedback dialog. 
https://github.com/duckduckgo/remote-messaging-config/pull/192/files
We also need to support showing an initial report in the feedback dialog, so that when it is displayed, a category is pre-loaded.
1. Go to `RemoteMessagingClient`, and change the DEBUG URL to use `https://jsonblob.com/api/1380594945500569600`. That JSON shows the new remote message for the Visual Updates (it does not add the feature flag parameter to make it easier to test)
2. Start the app
3. Remove internal state
4. …

Support navigation to feedback dialog from NTP

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1142021229838617/task/1210519540757012?focus=true
This change defines a new Privacy Config feature flag to control short history menu.
1. Launch the app and make sure shortHistoryMenu feature flag override is off.
2. Verify that you see daily history groupings in the history menu.
3. Use this privacy config: https://duckduckgo.github.io/privacy-configuration/pr-3297/v4/macos-config.json
4. Verify that you can’t see daily history groupings in the history menu.
--- …

Connect shortHistoryMenu feature flag to shortHistoryMenu Privacy Feature

---

.maestro/release_tests/autoclear.yaml
iOS/DuckDuckGo/BlankSnapshotViewController.swift

Task/Issue URL:  https://app.asana.com/1/137249556945/project/392891325557410/task/1210507196399705?focus=true
CC:
Updates the autoclear test to wait for the tab switcher button instead of asserting against the blank snapshot view and uses correct chat AI icon.
1. Check that tests have passed: https://github.com/duckduckgo/apple-browsers/actions/runs/15561761081
2. Turn on autoclear (settings > data clearing > automatically clear data > app exit)
3. Background the app
4. Then view the app in the app switcher - should show the blank snapshot view.  Chat button should be correct icon.
Snapshot view could still be wrong. 
---
[Definition of …

fix autoclear test and update snapshot view

---

iOS/DuckDuckGo/DuckDuckGoAlpha.entitlements
iOS/Gemfile
iOS/Gemfile.lock
iOS/fastlane/Fastfile
iOS/fastlane/Matchfile
macOS/Gemfile
macOS/Gemfile.lock

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210473120077094?focus=true
This change updates fastlane to a version containing a fix for iOS AdHoc builds code signing:
https://github.com/fastlane/fastlane/issues/29499
It also reverts a workaround forcing read-only mode in CI, and removes template_name parameter
from the Matchfile, as it’s no longer supported and custom entitlements are enabled via settings
in the App Identifier in Developer Portal (already in place for the iOS app bundle ID).
Verify that the [iOS AdHoc Alpha workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/15606980631) and [iOS AdHoc Release workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/15606119933) work fine.
None: Internal tooling, …

Update fastlane to 2.228.0 that fixes iOS AdHoc builds code signing

---

macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/Windows/View/WindowControllersManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210535371053608?focus=true
CC:
We added a new navigation from RMF to show the feedback dialog. We want to ensure that internal users are still redirected to the internal feedback form.
1. Go to `RemoteMessagingClient` line `51` and replace the URL with `https://jsonblob.com/api/1380594945500569600`
2. Make sure the internal state is set to on
3. Go to Debug -> Remote Messaging Framework -> Reset Remote Messages
4. Go to Debug -> Remote Messaging Framework -> Refresh Config (if the blue Help Us Improve! RMF appears, close it and do another Refresh Config)
5. Open a new tab page
6. The ‘DuckDuckGo got a refresh` message should appear.
7. Tap on `Share feedback` it should take you to the internal feedback form
8. …

macOS Visual Refresh: Send internal users to internal feedback form

---

macOS/DuckDuckGo/AIChat/AIChatTabOpener.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatMessageHandler.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScript.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScriptHandling.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarPresenter.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarViewController.swift
macOS/DuckDuckGo/Tab/TabExtensions/AIChatTabExtension.swift
macOS/UnitTests/AIChat/AIChatUserScriptTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1209671977594486/task/1210012482760771?focus=true
CC: @ayoy 
Add support for Duck.ai chat context handoff to sidebar or new tab when clicking chat button on SERP results.
**Handoff from SERP to sidebar**
1. Use search query that shows Duck.ai Assist enhanced results e.g. "star wars movies ranked"
2. Make sure that on current tab the Duck.ai sidebar is collapsed
3. Click Duck.ai "Chat" button on SERP
4. 
**Expected:** The Duck.ai sidebar is open and the query context is passed into it 
--
**Handoff from SERP to a new tab** 
5. Make sure that on current tab the Duck.ai sidebar is open
5. Use search query that shows Duck.ai Assist enhanced results
6. Click Duck.ai "Chat" button on SERP
**Expected:** The Duck.ai …

macOS Duck.ai Sidebar: 3. Duck.ai chat context handoff from SERP to sidebar (or new tab)

---

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureV2Tests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210228242617803
1.  Note that this cannot be fully tested at this stage since the FE is not implemented
2. Go to SubscriptionPagesUseSubscriptionFeatureV2.swift and make feature selection return .paidAIChat (let featureSelection: FeatureSelection = FeatureSelection(productFeature: .paidAIChat))
3. Go through the subscription and/or email flow
4. When you are on the welcome page click on any features and check it opens a duck.ai tab
— …

macOS: implement duck ai pro welcome messaging

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
iOS/Core/FeatureFlag.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/OnboardingExperiment/Manager/OnboardingManager.swift
iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingIntroViewModel.swift
iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingView.swift
iOS/DuckDuckGo/OnboardingExperiment/Pixels/OnboardingPixelReporter.swift
iOS/DuckDuckGo/OnboardingExperiment/VideoPlayer/VideoPlayerCoordinator.swift
iOS/DuckDuckGoTests/OnboardingIntroViewModelTests.swift
iOS/DuckDuckGoTests/OnboardingManager+SetDefaultBrowserPipVideoExperimentTests.swift
iOS/DuckDuckGoTests/OnboardingManagerTests.swift
iOS/DuckDuckGoTests/OnboardingPixelReporterTests.swift
iOS/DuckDuckGoTests/VideoPlayer/VideoPlayerCoordinatorTests.swift
iOS/SharedTestUtils/Mocks/OnboardingManagerMock.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210454186090910?focus=true
CC:
- Setup the Set Default Browser PiP Experiment.
- Implement the logic to show the Set Default Browser PiP video to the treatment group.
**Prerequisites:**
- PiP can only be tested on a real device.
- Ensure the device runs a version of iOS >= 18.2 to enroll in the experiment.
**Scenario 1 - Flow Control Group**
1. Ensure that 'Internal User’ is on in the Debug Menu and device OS version is >= 18.2+.
2. Tap the the 'Feature Flags’ menu item and in ‘Experiments’ ‘onboardingSetAsDefaultBrowserPiPVideo’ select the `control` cohort.
3. Go back to the `Debug Menu`, tap the `Onboarding` item and select ’New User'.
4. Tap the ‘Preview Onboarding’ button.
5. Get to the browser comparisons …

[iOS] Onboarding - Set Default Browser Picture In Picture Video Experiment Setup  

---

iOS/DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iOS/DuckDuckGo/LargeOmniBarState.swift
iOS/DuckDuckGoTests/LargeOmniBarStateTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/392891325557410/task/1210556646320677?focus=true
CC:
Prevents search loupe showing on iPad when in visual updates view.
1. Launch on iPad
2. Enable visual updates (internal user + visualUpdates feature flag + restart app)
3. Browse to a web page and focus the address bar
4. Dismiss button should appear to allow keyboard to be hidden
Some new weird omni bar state.
n/a
n/a
---

prevent dismiss and search loop appearing on top of each other on iPad

---

iOS/DuckDuckGo/SubscriptionDebugViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1209882303470922/task/1210548294316839?focus=true
CC:
The action sheet presentation on iPad requires a setup of origin view, and without it, it produces a crash. This fix alters the presentation in subscription debug menu for the subscription environment and custom URL actions sheets to alert.
**Subscription Environment (Use iPad for testing)**
1. Open Settings -> All debug options -> Subscription 
2. Attempt changing environment
3. Alert requiring confirmation to restart should appear
4. Check after restart if the environment was persisted
**Custom base subscription URL(Use iPad for testing)**
1. Open Settings -> All debug options -> Subscription 
2. Attempt changing custom base subscription URL
3. Alert …

Fix for crashing actionSheet presentation in Subscription debug menu on iPad

---

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
SharedPackages/BrowserServicesKit/Package.swift
SharedPackages/BrowserServicesKit/Sources/NetworkingTestingUtils/MockOAuthClient.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionAPIService.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionEndpointServiceV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/AppStore/AppStorePurchaseFlowV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/Stripe/StripePurchaseFlowV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/APIs/SubscriptionEndpointServiceMockV2.swift
SharedPackages/BrowserServicesKit/Tests/CrashesTests/CrashLogMessageExtractorTests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/API/SubscriptionEndpointServiceV2Tests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+CustomURL.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests+Redirect.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/SubscriptionManagerV2Tests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/PrivacyProSubscriptionV2IntegrationTests.swift
iOS/DuckDuckGo/RemoteMessagingConfigMatcherProvider.swift
iOS/DuckDuckGo/SettingsViewModel.swift
iOS/DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModelV2.swift
iOS/DuckDuckGo/Subscription/Views/SubscriptionSettingsView.swift
iOS/DuckDuckGo/SubscriptionDebugViewController.swift
macOS/DuckDuckGo/RemoteMessaging/RemoteMessagingConfigMatcherProvider.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/DebugMenu/SubscriptionDebugMenu.swift
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionSettingsModelV2.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1200019156869587/task/1209608044788440?focus=true
**iOS and macOS**
These changes fix the issue where the subscription can become unavailable when the device is offline.
1. kill the app
2. Enable "Network Link Conditioner" to 100% loss
3. open settings
4. No subscription is available, this could be ok
5. go online (disable "Network Link Conditioner")
6. subscription is never available, the app needs to be killed.
1. kill the app
2. Enable "Network Link Conditioner" to 100% loss
3. open settings
4. No subscription is available, this could be ok
5. go online (disable "Network Link Conditioner")
6. subscription must be visible
--- …

Improving Subscription behaviour when the device is offline

---

iOS/Core/PixelEvent.swift
iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/TabViewControllerBrowsingMenuExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/392891325557410/task/1210592355928739?focus=true
CC:
Fixes AI chat firing with regards to if AI chat had already been used.
Funnels all firing code for this feature through a single call which fires a different pixel depending on the source.
* Address bar -> `m.aichat.addressbar.icon`
* Menu when on new tab page -> `m.aichat.menu.newtabpage`
* Menu when on web page (inc SERP) -> `m.aichat.menu.webpage`
* Tab switcher -> `m.aichat.tabmanager.icon`
1. Clean install.  
2. Tap chat button on address bar and confirm `m.aichat.addressbar.icon` pixel is fired with `"was_used_before": "0"` parameter
3. Tap it again and check that `"was_used_before": "1"` parameter
4. Check pixel is fired for each of above sources and …

fix ai chat usage pixel

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210503995054107?focus=true
CC:
Show the dax logo
1. Enable the new UI (Settings -> Appearance -> Experimental)
2. Enable duck.ai experimental (Settings -> Duck.ai -> Experimental)
3. Without favorites, open the new omnibar, see if we display the dax logo on both search (when empty) and duck.ai mode
4. With favorites, open the new omnbiar, see if we display the dax logo only on duck.ai mode
Show the logo at the wrong state, for example, above auto-complete results

Show logo on new switch omnibar

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarHandler.swift
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift
iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/OmniBarDelegate.swift
iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarViewController.swift
iOS/DuckDuckGo/VoiceSearchFeedbackViewModel.swift
iOS/DuckDuckGo/VoiceSearchViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210503995054108?focus=true
Add the voice search button on the new switch bar with duck.ai
1. Enable the new UI (Settings -> Appearance -> Experimental)
2. Enable duck.ai experimental (Settings -> Duck.ai -> Experimental)
3. Enable Voice-search (Settings -> Accessibility)
4. Make sure voice-search button still works for the unfocused omnibar
5. Select the omnibar see if the voice-search button appears when there's no text
6. Tap on it from the search mode, it should open voice-search with search selected
7. Tap on it from the duck.ai mode, it should open voice-search with duck.ai selected
Regressions on the old omnibar
Animations are …

Add voice search button in the new Switch Bar

---

iOS/DuckDuckGo/DuckPlayer/NativeUI/DuckPlayerNativeUIPresenter.swift
iOS/DuckDuckGoTests/DuckPlayer/DuckPlayerNativeUIPresenterTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210613997565723?focus=true
Tech Design URL: N/A
CC: N/A
Fixes a background crash in DuckPlayer's constraint handling. Crash was occurring during Auto Layout constraint processing
**Key Changes:**
- Remove all force unwrapping (`\!`) from constraint-related code
- Add proper nil checks and guard statements for weak references
- Send UI updates in `DispatchQueue.main.async`
- Improve cleanup in `deinit` and `removePillContainer()` methods
- Add weak captures in sink closures to prevent retain cycles
1. Navigate to a YouTube video page
2. Confirm DuckPlayer pill presentation
3. Go to Settings > Appeareance and Change Address bar position
4. Confirm DuckPlayer Pill properly attaches to Toolbar or Omnibar
N/A …

Fix DuckPlayer constraint crash by removing force unwraps

---

macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/Localization/Localizable.xcstrings
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarPresenter.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarProvider.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarViewController.swift
macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift
macOS/DuckDuckGo/Tab/View/BrowserTabViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1209671977594486/task/1210012482760771?focus=true
CC:
This PR contains various fixes and visual tweaks related to Duck.ai sidebar feature:
- fix for crash when sidebar was toggled after the feature flag was changed without restart
- clean up of right click menu in the sidebar
- fix background color and dark mode of the sidebar
- add tooltips for sidebar buttons
- fix for crash when sidebar was toggled repeateadly and rapidly
**Fix for crash when sidebar was toggled after the feature flag was changed without restart**
1. Check if feature flag for sidebar is disabled
2. Open tab and navigate to website
3. Click the Duck.ai address bar button (it should open a new tab)
4. Enable feature flag for the sidebar
5. …

macOS Duck.ai Sidebar: 6. Visual tweaks and fixes

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
iOS/DuckDuckGo/Refactoring/Updated/UpdatedOmniBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210601460385822?focus=true
Do not show suggestion when tapping the bar from a website
1. Enable the new UI (Settings -> Appearance -> Experimental)
2. Enable duck.ai experimental (Settings -> Duck.ai -> Experimental)
3. Open a website, tap the omnibar, check that the logo is being displayed (or favorites)
4. Open the SERP, tap the omnibar, check that we're displaying the suggestions
Regressions when opening the omnibar
There's a flash on the animation that happens when the view is displayed. This is expected, it will be fixed lated

Do not show suggestion when tapping the bar from a website

---

macOS/DuckDuckGo/Fire/View/Fire.storyboard
macOS/DuckDuckGo/Fire/View/FireViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210626259488220?focus=true
CC:
Show the new icon when the fire animation is running.
1. Run the app 
2. Check you are seeing the new UI
3. Tap the fire button and clear
4. When the fire animation is running, you should see the new icon not the old one
Nothing.
—

macOS: Show new icon when fire animation is happening

---

SharedPackages/BrowserServicesKit/Tests/BrowserServicesKitTests/Autofill/AutofillVaultUserScriptTests.swift
iOS/Core/FeatureFlag.swift
iOS/Core/PixelEvent.swift
iOS/DuckDuckGo/KeyboardInputAccessory/CreditCardInputAccessoryView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210618971158384?focus=true
CC:
Add pixels for credit card keyboard accessory actions
1. Enable the credit card feature flag in Debug menu and ensure you have at least 1 card saved
2. Go to https://privacy-test-pages.site/autofill/credit-card-various-inputs.html and tap into a card field.
3. Dismiss the prompt and tap into a card field again so that the credit card keyboard accessory 
4. Select a card and confirm pixel `autofill.cards.keyboard.fill.confirmed` is fired
5. Tap into a card field again and this time tap on the manage button.
6. Confirm pixel `autofill.cards.keyboard.open.settings` is fired
—
[Definition …

Pixels for autofill keyboard accessory

---

.github/actions/asana-failed-pr-checks/action.yml
.github/actions/asana-failed-pr-checks/report-failed-pr-checks.sh
.github/actions/fetch-commit-info/action.yml
.github/workflows/bsk_pr_checks.yml
.github/workflows/dbp_pr_checks.yml
.github/workflows/ios_pr_checks.yml
.github/workflows/macos_pr_checks.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210625492570315?focus=true
This change updates the `asana-failed-pr-checks` GitHub Action to ensure that post-merge failed PR Checks tasks are only assigned to Apple team members. If a PR was authored by a non-Apple team member, the PR reviewer will be assigned.
It can break reporting PR Checks failures and it can’t really be tested without previously merging it...
---

Don’t assign post-merge failed PR Checks tasks to non-Apple team members

---

macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/MainWindow/MainViewController.swift
macOS/DuckDuckGo/Menus/MainMenu.swift
macOS/DuckDuckGo/Menus/MainMenuActions.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210567792963681?focus=true
This change adds a new local feature flag to control AI chat text summarization. It’s disabled by default
and will remain disabled until it’s ready to be tested internally.
Also an action is added to Main Menu to support shift+Enter keyboard shortcut for text summarization
when the feature flag is enabled.
1. Run the app and open a website. Make sure that the address bar is not focused.
2. Filter Xcode logs for “Summarize”.
3. Press command+shift+Enter and verify that nothing happens and nothing gets logged.
4. Enable aiChatTextSummarization feature flag from Feature Flag Overrides menu.
5. Press command+shift+Enter and verify that “Summarize” gets logged.
Low: Minor visual …

Add aiChatTextSummarization feature flag

---

SharedPackages/AIChat/Sources/AIChat/Shared/AIChatUserScriptMessages.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatMessageHandler.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScript.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScriptHandling.swift
macOS/DuckDuckGo/Menus/MainMenuActions.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarPresenter.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarViewController.swift
macOS/DuckDuckGo/Tab/Model/Tab+UIDelegate.swift
macOS/DuckDuckGo/Tab/Model/Tab.swift
macOS/DuckDuckGo/Tab/TabExtensions/AIChatTabExtension.swift
macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift
macOS/DuckDuckGo/Tab/UserScripts/ContextMenuUserScript.swift
macOS/DuckDuckGo/Tab/View/WebView.swift
macOS/UnitTests/AIChat/AIChatUserScriptTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201621708115095/task/1210567792963682?focus=true
This change adds a webView context menu action that allows users to summarize selected text using Duck.ai.
It currently uses a simple summarization prompt (while we wait for the proper summarization FE API) and
a regular FE UI (while we wait for the summarization UI).
Summarization is also triggered by cmd+shift+enter shortcut (if there’s any text selected).
1. Launch the app and ensure that `aiChatTextSummarization` feature flag is not enabled.
2. Select text on a website and verify that the context menu doesn’t contain “Summarize with Duck.ai” option.
3. Select text on a website and verify that pressing cmd+shift+enter has no effect.
4. Enable `aiChatTextSummarization` feature …

Add context menu option to summarize selected text with Duck.ai

---

SharedPackages/VPN/Sources/VPN/Diagnostics/NetworkProtectionError.swift
SharedPackages/VPN/Sources/VPN/NetworkProtectionDeviceManager.swift
iOS/Core/PixelEvent.swift
iOS/DuckDuckGo/EventMapping+NetworkProtectionError.swift
iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
macOS/DuckDuckGo/NetworkProtection/AppAndExtensionAndAgentTargets/NetworkProtectionPixelEvent.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/EventMapping+NetworkProtectionError.swift
macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207603085593419/task/1210618804136019?focus=true
⚠️ This will be merged against the internal macOS branch.  When merging we want to also cherry-pick into the iOS release branch.
Fires a pixel when the VPN learns the subscription has expired after calling `VPNAuthTokenBuilder.getVPNAuthToken`.
See the privacy triage [here](https://app.asana.com/1/137249556945/project/69071770703008/task/1210625635821516).
Test in both iOS and macOS.
1. Just start the VPN normally and ensure it connects.
1. Open Console.app, start streaming (make sure to pick the right device for macOS vs iOS).
2. Filter by "vpn_access_revoked"
3. Go to [this line](https://github.com/duckduckgo/apple-browsers/blob/ba52c52a8f104eba76a7c05ec4552d7add2169ea/SharedPac …

Fire a pixel when the VPN tunnel detects access revoked.

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
iOS/Core/FeatureFlag.swift
iOS/DuckDuckGo/FeatureFlagsDebugSettings/FeatureFlagsSettingViewModel.swift
iOS/DuckDuckGo/TabSwitcherBarsStateHandler.swift
iOS/DuckDuckGo/TabSwitcherViewController+MultiSelect.swift
iOS/DuckDuckGo/TabSwitcherViewController.swift
iOS/DuckDuckGoTests/TabSwitcherBarsStateHandlerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/715106103902962/task/1210647253853346?focus=true
CC: @graeme 
Restores previous version of tab switcher bars state code and uses strategy pattern to respect the feature flag.  TabSwitcherViewController checks the state of the flag directly for everything else.
1. Check current production app and go to the tab switcher - this is the "legacy layout"
1. Launch app from current head of main - check tab manager layout - this is the new "default layout" aka "June 2025 tab manager layout changes"
2. Upgrade app using this branch - check tab manager layout - should be unchanged
3. Go to debug screen > Feature Flags and turn off `june2025TabManagerLayoutChanges` 
4. Without restarting the app, go back to the tab …

killswitch for tab manager changes

---

macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/DefaultBrowserAndAddToDockPrompts/DefaultBrowserAndDockPromptCoordinator.swift
macOS/UnitTests/DefaultBrowserAndAddToDockPrompts/DefaultBrowserAndDockPromptCoordinatorTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210646559468282?focus=true
CC:
This PR addresses an issue with the onboarding completion check. The value used to determine if onboarding was completed was passed as a variable rather than utilizing a closure that evaluates the condition on demand.
**Issue:**
The prompt to the user was not displayed after they finished onboarding unless the app was closed in the meantime.
**Solution:**
By implementing a closure for the onboarding completion check, the app will now evaluate the status each time, ensuring that the prompt is presented immediately after onboarding is completed, regardless of whether the app was closed or not.
Ensure new unit test pass.
Low: Improvement on existing code.
Added …

Fix an issue where SAD/ATT prompts would not show if user do not close the app after onboarding

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/AIChat/AIChatPixel.swift
macOS/DuckDuckGo/AIChat/AIChatSummarizationRequest.swift
macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScriptHandling.swift
macOS/DuckDuckGo/MainWindow/MainViewController.swift
macOS/DuckDuckGo/Menus/MainMenuActions.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarPresenter.swift
macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210625543706130?focus=true
This change adds pixels agreed upon in the Privacy Triage and implements firing the summarization pixel.
1. Enable `aiChatTextSummarization` feature flag.
2. Filter logs by PixelKit category.
3. Select some text, open context menu and select “Summarize with Duck.ai”.
4. Verify that `m_mac_aichat_summarize_text` was fired with "source": "context-menu” (and also the _daily pixel).
5. Select some text and press cmd+shift+enter.
6. Verify that `m_mac_aichat_summarize_text` was fired with "source": “keyboard-shortcut” (the _daily pixel should be skipped this time).
---
[Definition of …

Add Duck.ai summarization pixels and implement 'summarize text' pixel

---

.maestro/release_tests/autoclear.yaml
.maestro/release_tests/backgrounding.yaml
iOS/DuckDuckGo/SettingsCompleteSetupView.swift
iOS/DuckDuckGo/SettingsPrivacyProtectionsView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210645804719021?focus=true
CC:
Update E2E tests to reflect changes in the Settings screen
1. Confirm [workflow](https://github.com/duckduckgo/apple-browsers/actions/runs/15898961240) runs successfully 
---

Fix E2E tests after Settings change

---

SharedPackages/BrowserServicesKit/Tests/DDGSyncTests/DDGSyncTests.swift
SharedPackages/BrowserServicesKit/Tests/DDGSyncTests/SyncConnectionControllerTests.swift
macOS/UnitTests/Sync/SyncPreferencesTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210659317398374?focus=true
Disables a bunch of flaking sync tests to be reenabled later: https://app.asana.com/1/137249556945/project/1202926619870900/task/1210659317398376?focus=true
Just green CI
---

Disable all potentially flakey macOS sync tests

---

iOS/DuckDuckGoTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureForStripeTests.swift
macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1210674657043954?focus=true
CC:
Fix flaky tests due to not thread-safe access to `pixelsFired` used to gather and assert fired pixels.
1. Repeatedly 1000 run tests from `SubscriptionPagesUseSubscriptionFeatureTests`
None, fix for tests.
---

Fix flaky subscription tests

---

iOS/Core/QRunInBackgroundAssertion.swift
iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/AppServices/StatisticsService.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/856498667320406/task/1210672892676451?focus=true
CC:
Statistic Loader can trigger two async operations (fetches) that could take some time to complete. When done, notification is posted, that can invoke `AutofillPixelReporter` and cause SecureVault fetches. If that coincide with transition from Background to Suspended, app is getting killed as it is not allowed to hold an active lock on a DB file.
This is actually impossible to trigger with debugger attached, and nearly impossible to trigger in general unless you prolong the operations - so just sanity check for the logic is needed here.
Current setup does not cancel the in flight requests in case of the timeout, assuming it will be extremely rare situation for …

Add background task to Statistics Loader

---

macOS/DuckDuckGo/NetworkProtection/AppTargets/DeveloperIDTarget/NetworkProtectionSubscriptionEventHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210669615202799?focus=true
Fixes an issue where entitlements are sometimes absent at startup, which was causing a huge number of attempts to enable the login item to stop the VPN.
There are no steps to reproduce the original crash.
1. Remove the subscription
3. Restart the App
4. Ensure VPN is disabled if it was previously enabled, or stays disabled if not (and the menu item doesn't come up).
1. Start on AuthV1
2. Enable the VPN
3. Restart the App
4. Ensure the VPN stays connected
This is disabling all features at first launch, but that's beyond scope for this PR.
1. Start on AuthV1
2. Enable the VPN
3. Restart the App
4. Ensure the VPN stays connected
High impact, medium risk
Impact is likely high in a …

Fixes an issue where entitlements are sometimes absent at startup.

---

iOS/DuckDuckGo/DuckPlayer/NativeUI/DuckPlayerNativeUIPresenter.swift
iOS/DuckDuckGo/DuckPlayer/NativeUI/NativeDuckPlayerNavigationHandler.swift
iOS/DuckDuckGoTests/DuckPlayer/DuckPlayerNativeUIPresenterTests.swift
iOS/DuckDuckGoTests/DuckPlayer/NativeDuckPlayerNavigationHandlerTests.swift
iOS/DuckDuckGoTests/DuckPlayer/YoutublePlayerNavigationHandlerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204099484721401/task/1210690063272434?focus=true
Tech Design URL: N/A
CC:
Fixed DuckPlayer pill incorrectly showing on DuckDuckGo search result pages (SERP). Added validation to prevent pill presentation on SERP pages while maintaining correct behavior for YouTube pages.
1. Search for "Metallica videos"
2. Tap a Youtube result.
3. Close video
4. Confirm pill does not appear
**Medium**: Fixes incorrect UI behavior that could confuse users
- Pill not showing on valid YouTube pages: Mitigated by comprehensive test coverage
- SERP-to-YouTube navigation breaking: Tested and verified delegate navigation still works
Added tests for this specific case, and remove flaky test.
---
[Definition of …

Fix DuckPlayer pill showing on SERP pages

---

SharedPackages/BrowserServicesKit/Tests/NavigationTests/ClosureNavigationResponderTests.swift
SharedPackages/BrowserServicesKit/Tests/NavigationTests/DistributedNavigationDelegateTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1206506149377247?focus=true
- disable navigation delegate webcontent process termination tests since the handler is broken on macOS 15.5+
1. Validate Navigation tests pass locally and on CI
Low
We lose track of termination handlers stop working
---

disable WebKit termination tests

---

SharedPackages/AIChat/Sources/AIChat/iOS/PublicAPI/AIChatDebugSettingsHandling.swift
SharedPackages/AIChat/Sources/AIChat/iOS/PublicAPI/AIChatRequestAuthorizationHandling.swift
SharedPackages/AIChat/Tests/AIChatTests/AIChatRequestAuthorizationHandlerTests.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptTests.swift
iOS/DuckDuckGo/AIChat/AIChatSettings.swift
iOS/DuckDuckGo/AIChatDebugView.swift
iOS/DuckDuckGo/Subscription/UserScripts/SubscriptionPagesUseSubscriptionFeature.swift
iOS/DuckDuckGo/UserScripts.swift
iOS/DuckDuckGoTests/AIChat/AIChatSettingsTests.swift
macOS/DuckDuckGo/AIChat/AIChatRemoteSettings.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
macOS/DuckDuckGo/Preferences/View/PreferencesRootView.swift
macOS/DuckDuckGo/Preferences/View/PreferencesViewController.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
macOS/DuckDuckGo/Tab/UserScripts/UserScripts.swift
macOS/UnitTests/AIChat/AIChatRemoteSettingsTests.swift
macOS/UnitTests/AIChat/AIChatUserScriptTests.swift
macOS/UnitTests/Preferences/RootViewV2Tests.swift
macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureV2Tests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210686986062299
cc: @Bunn 
On both platforms 
1. Go to Debug -> AI Chat -> Web Communication -> Set Custom URL to https://euw-serp-dev-testing10.duck.co/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1 (for iOS go to all debug settings -> Set Custom AI Chat URL)
2. Go to Duck.ai from address bar, from Duck.ai subscription menu and check you get the testing duck ai (with the drop down menu on the right)
3. Go to Debug -> AI Chat -> Web Communication -> Reset custom URL (for iOS go to all debug settings -> Reset Custom URL)
4. Go to Duck.ai from address bar, from Duck.ai subscription menu and check you get the production duck ai
<!-- Describe specific scenarios and how you've …

test paid duckai serp messages

---

macOS/DuckDuckGo/Menus/MainMenuActions.swift
macOS/UITests/FireWindowTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1210613509788456?focus=true
CC:
This PR ensures that Developer menu items are disabled in empty Fire windows. Previously, the menu items appeared enabled but had no effect when clicked.
1. Launch the app and open a new Fire window (File > New Fire Window).
2. Verify that the menu items under View > Developer are disabled.
Low: This change only affects access to Developer tools in new Fire windows.
Developer tools might be unintentionally disabled or enabled in the wrong state, but the added UI tests should catch regressions.
Two UI tests were added to cover the expected behavior:
* Developer menu items are disabled in a new Fire window.
* Developer menu items are enabled in a Fire window …

Disable developer menu items in an empty Fire window

---

iOS/DuckDuckGo/DuckPlayer/NativeUI/NativeDuckPlayerNavigationHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204099484721401/task/1210584560074598?focus=true
CC: N/A
Moves `notifyUserScriptOfURLChange` to always execute early in the URL change flow, ensuring user scripts receive consistent notifications regardless of DuckPlayer's handling mode.
1. Navigate to video with shorts listed: (https://m.youtube.com/watch?v=L3gOf2XDp8Y&pp=ygUHRGlzbmV5dA%3D%3D)
2. Open Duck Player
3. Close Duck Player (Observe video is paused)
4. Tap a short
5. Observe shorts plays (Before the fix, shorts were paused)
**Impact Level: Low** - Improves user script communication reliability
- Additional notifications might affect user script behavior
**Mitigation:**
- User scripts designed to handle URL changes efficiently
- No changes to main …

Always call urlChange for DuckPlayer

---

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/AIChat/AIChatViewControllerManager.swift
iOS/DuckDuckGo/AIChat/SubscriptionAIChatStateHandler.swift
iOS/IntegrationTests/AiChat/AIChatViewControllerManagerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210723156401816
Tech Design URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210723156215684
1. Make sure you are unsubscribed
2. Turn paidAiChat feature flag on
3. go to all debug settings -> Set Custom AI Chat URL  to https://euw-serp-dev-testing10.duck.co/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1 
4. Open Duck.ai which should have a drop down menu at the top and should shoe the “Free” logo
5. Subscribe to DuckDuckGo
6.  Open Duck.ai which should have a drop down menu at the top and should shoe the “Subscribed” logo
7. Go to subscription settings and remove subscription from device 
8. Open Duck.ai which should have a drop down menu at the top and should shoe the “Free” logo
9. Close …

iOS: implement Duck.ai session update based on subscription state

---

SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionAPIService.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionEndpointService.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/API/SubscriptionEndpointServiceV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/AccountManager.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/V1toV2Bridging/SubscriptionAuthV1toV2Bridge.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/API/SubscriptionEndpointServiceV2Tests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/AccountManagerTests.swift
SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Authentication/DataBrokerProtectionSubscriptionManaging.swift
iOS/DuckDuckGo/AppServices/VPNService.swift
iOS/DuckDuckGo/MainViewController.swift
iOS/DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModel.swift
iOS/DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModelV2.swift
macOS/DuckDuckGo/DBP/DataBrokerProtectionAppEvents.swift
macOS/DuckDuckGo/DBP/DataBrokerProtectionFeatureGatekeeper.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/DeveloperIDTarget/VPNSubscriptionEventsHandler.swift
macOS/DuckDuckGo/Waitlist/VPNFeatureGatekeeper.swift
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionSettingsModelV1.swift
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Preferences/PreferencesSubscriptionSettingsModelV2.swift
macOS/UnitTests/DBP/Tests/DataBrokerProtectionFeatureGatekeeperTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1210746879873137?focus=true
Fixes a regression with entitlement checks on AuthV1.
The issue was introduced in [this line](https://github.com/duckduckgo/apple-browsers/pull/936/files#diff-ef31b1cf1db6fe730b6cadd9926e1466fd19b34e0fd567a3144ee6ecee597cf3R90) and [this line](https://github.com/duckduckgo/apple-browsers/pull/936/files#diff-ef31b1cf1db6fe730b6cadd9926e1466fd19b34e0fd567a3144ee6ecee597cf3R95).
Local cache expires after 20 minutes, so the first line would often return an error about no cache being available.  The second line would then proceed to inform there are no entitlements to the app.
1. Throw an error here.
2. Start the app.
3. See that the VPN and DBP are disabled.
Medium
This is making …

Fix v1 entitlements regression

---

SharedPackages/AIChat/Sources/AIChat/macOS/PublicAPI/AIChatPreferencesStorage.swift
macOS/DuckDuckGo/AIChat/AIChatMenuVisibilityConfigurable.swift
macOS/DuckDuckGo/Preferences/Model/AIChatPreferences.swift
macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift
macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift
macOS/UnitTests/AIChat/AIChatMenuConfigurationTests.swift
macOS/UnitTests/Menus/MainMenuTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210750726093985?focus=true
This change adds a checkbox in AI Features settings to control summarization menu action visibility.
1. Launch the app, ensure that feature flags are in the default state (`aiChatSidebar` on, `aiChatTextSummarization` off)
2. Right click text on a website, trigger context menu and verify that “Summarize with Duck.ai” is not present in the menu.
3. Go to Settings -> AI Features and verify that the option to control summarization is not present.
4. Enable `aiChatTextSummarization` feature flag.
5. Switch to another Settings pane and back to AI Features and verify that the option to control summarization is present.
6. Right click text on a website, trigger context menu and verify …

Add Summarization to AI Features settings

---

.github/workflows/create_asana_pr_subtask.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210752234516847?focus=true
It appears that sometimes this workflow is triggered without a reviewer parameter.
Verify that CI is green 🤷 
---

Skip creating PR review task when reviewer is not provided

---

macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210750726093985?focus=true
This change connects text summarization feature to a checkbox in AI Features settings
related to controlling Duck.ai shortcuts in menus.
1. Launch the app, ensure that `aiChatTextSummarization` feature flag is enabled.
3. Go to Settings -> AI Features and verify that the _Show “New Duck.ai chat” in File and application menus_ option is enabled.
4. Right click text on a website, trigger context menu and verify that “Summarize with Duck.ai” is present in the menu.
5. Verify that summarization works by opening a sidebar or new tab (depending on the sidebar setting in AI Features).
6. Go to Settings -> AI Features and disable _Show “New Duck.ai chat” in File and application menus_ …

Make summarization dependent on Duck.ai application menus settings

---

iOS/LocalPackages/SetDefaultBrowser/Package.swift
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/DefaultBrowserPromptModalView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210758893284409?focus=true
CC:
This PR fix the dependency graph of SetDefaultBrowserUI in iOS and resolve SwiftUI previews not showing in package.
1. Select ‘SetDefaultBrowserUI' scheme.
2. Open ‘DefaultBrowserPromptModalView’.
3. Ensure SwiftUI Preview loads fine. If not ensure that ‘Use Legacy Preview Execution’ is unchecked. See below screenshot.
None, internal SwiftUI Previews used for development.
<!— 
- How does this affect performance?
- What documentation needs updating?
- How does this impact privacy/security?
—>
<!-- …

[iOS][Set As Default] Enable SwiftUI previews for package

---

.github/workflows/macos_publish_dmg_release.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210784601649457?focus=true
This change updates macos_publish_dmg_release.yml to allow cancelling the publishing job.
---

Allow to cancel Publish DMG release workflow

---

macOS/DuckDuckGo/DataImport/Model/DataImportViewModel.swift
macOS/DuckDuckGo/DataImport/View/DataImportView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199230911884351/task/1210785808806844?focus=true
When [✓ Display copyable error messages on the import UI](https://app.asana.com/1/137249556945/task/1210732287708280) was merged, there was a bug where the error view could not be dismissed by pressing the button
I've now changed the logic so that the debug view only shows in production if the user is internal and there were errors during import.
In the linked task above.
If the logic was wrong, this debug view could show for production users. But the test steps should cover that.
--- …

Fix internal import debug view bug

---

macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/Statistics/GeneralPixel.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210763248257877?focus=true
This change adds ml.mac.app-launch pixel fired at every app launch. This is to count crash-free sessions.
1. Launch the app and verify that `ml.mac.app-launch` pixel is fired.
---

Add macOS launch pixel

---

macOS/DuckDuckGo/Bookmarks/Model/BookmarkManager.swift
macOS/DuckDuckGo/Bookmarks/Services/BookmarkStore.swift
macOS/DuckDuckGo/Bookmarks/Services/BookmarkStoreMock.swift
macOS/DuckDuckGo/Bookmarks/Services/LocalBookmarkStore.swift
macOS/DuckDuckGo/DataImport/Bookmarks/BookmarkImport.swift
macOS/DuckDuckGo/DataImport/Bookmarks/CoreDataBookmarkImporter.swift
macOS/DuckDuckGo/DataImport/Bookmarks/HTML/BookmarkHTMLImporter.swift
macOS/DuckDuckGo/DataImport/Bookmarks/Safari/SafariBookmarksReader.swift
macOS/DuckDuckGo/DataImport/Bookmarks/Safari/SafariDataImporter.swift
macOS/DuckDuckGo/DataImport/Logins/Chromium/ChromiumDataImporter.swift
macOS/DuckDuckGo/DataImport/Logins/Firefox/FirefoxDataImporter.swift
macOS/DuckDuckGo/DataImport/Model/DataImportViewModel.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
macOS/UnitTests/Bookmarks/Services/LocalBookmarkStoreTests.swift
macOS/UnitTests/DataImport/BookmarksHTMLImporterTests.swift
macOS/UnitTests/DataImport/ChromiumDataImporterTests.swift
macOS/UnitTests/DataImport/DataImportMocks.swift
macOS/UnitTests/DataImport/FirefoxDataImporterTests.swift
macOS/UnitTests/DataImport/SafariBookmarksReaderTests.swift
macOS/UnitTests/HomePage/Mocks/MockBookmarkManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210726801397642?focus=true
This PR updates the bookmarks import feature for Safari: 
* “Favorites” from Safari are still imported in the Bookmarks root.
* “Bookmarks” from Safari are still imported into a folder off the root, but with the name “Bookmarks” (previously “Other bookmarks”)
* “Favorites” are still marked as favorites (e.g. on the new tab page), up to a limit of 12. This includes topping up the favorites list if there are already favorites.
This new behavior is behind a feature flag and is disabled by default.
⚠️ These changes are based on https://github.com/duckduckgo/apple-browsers/pull/1235 ⚠️ 
1. Go to Debug menu > Feature flag overrides > Other > enable `updatedBookmarksFavoritesImport` …

macOS: Update behavior for Safari bookmarks import

---

macOS/DuckDuckGo/DataImport/Bookmarks/Firefox/FirefoxBookmarksReader.swift
macOS/DuckDuckGo/DataImport/Logins/Firefox/FirefoxDataImporter.swift
macOS/DuckDuckGo/DataImport/Model/DataImportViewModel.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
macOS/UnitTests/DataImport/FirefoxBookmarksReaderTests.swift
macOS/UnitTests/DataImport/FirefoxDataImporterTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210674932129669?focus=true
This updates the folder structure when bookmarks are imported from Firefox. Previously, bookmarks from both the bookmarks bar and bookmarks menu went into the Bookmarks root, and the “Other Bookmarks” folder became a folder off the root. Now, the imported bookmarks more closely match the Firefox folder structure:
* "Bookmarks Toolbar" goes to the root
* "Bookmarks Menu" becomes a folder off the root (new behavior)
* "Other Bookmarks" becomes a folder off the root
These changes are behind a feature flag that is disabled by default.
Firefox setup:
1. Install Firefox if needed.
2. Add at least one bookmark to each folder in Firefox (Bookmarks Toolbar, Bookmarks Menu, Other …

macOS: Update folder structure for Firefox bookmarks import

---

iOS/DuckDuckGo/DefaultBrowserPrompt/EventMappers/DefaultBrowserPromptManagerDebugPixelHandler.swift
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserCore/CheckDefaultBrowserService/CheckDefaultBrowserManager.swift
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserCore/CheckDefaultBrowserService/Dependencies/DefaultBrowserPromptEventMapping.swift
iOS/LocalPackages/SetDefaultBrowser/Tests/SetDefaultBrowserTests/CheckDefaultBrowserManagerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210806442029210?focus=true
CC:
This PR enhances the logging for the manager that checks if the browser is set as the default. If the API encounters an unknown error, we will log the error to gather more information about the cause.
1. Ensure tests pass.
Smoke Test
1. Put a breakpoint at Line 37 in ‘DefaultBrowserPromptManagerDebugPixelHandler.swift'
2.In DefaultBrowserManager defined in iOS/LocalPackages/SetDefaultBrowser replace line 50 with 'let defaultBrowserResult: Result<Bool, CheckDefaultBrowserServiceError> = .failure(.unknownError(NSError(domain: "test Alessandro", code: 0, userInfo: nil)))’
3. Fresh install the App
4. Skip Onboarding
5. Open Debug menu 
6. Set internal user state …

[iOS] Enhance logging of Set As Default manager

---

macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1210821773361686?focus=true
Use clear background color for trailingButtonsBackground
1. Launch the app and switch to dark mode
2. Verify that address bar buttons don’t display black background (on the screenshot below the bookmark button is hovered)
---

Fix address bar trailing buttons appearance in dark mode

---

.github/workflows/macos_alpha_release.yml
.github/workflows/macos_build_appstore.yml
.github/workflows/macos_build_notarized.yml
iOS/Gemfile.lock
iOS/fastlane/Pluginfile
macOS/Configuration/App/Sparkle.xcconfig
macOS/DuckDuckGo/Menus/MainMenu.swift
macOS/Gemfile.lock
macOS/fastlane/Pluginfile
macOS/scripts/archive.sh

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210800425272850?focus=true
This change adds macos_alpha_release.yml workflow that builds and publishes
Alpha release to Sparkle and TestFlight.
Additionally, the regular app gets a Debug Menu option to get the Alpha build.
This change doesn’t cover enabling the alpha workflow in main branch.
1. Run the regular macOS Browser scheme.
2. Select Main Menu -> Debug -> Download DuckDuckGo Alpha Build.
3. Install downloaded Alpha DMG and launch it.
4. Run [macos_alpha_release.yml](https://github.com/duckduckgo/apple-browsers/actions/workflows/macos_alpha_release.yml) (this needs to happen via CLI: `gh workflow run macos_alpha_release.yml --ref dominik/macos-alpha-release-workflow`) and wait until it finishes …

Add macOS alpha release workflow

---

.github/workflows/macos_build_appstore.yml
.github/workflows/macos_build_notarized.yml
SharedPackages/BrowserServicesKit/Sources/Common/AppVersion.swift
SharedPackages/BrowserServicesKit/Sources/Common/Extensions/BundleExtension.swift
SharedPackages/BrowserServicesKit/Tests/CommonTests/AppVersionExtensionTests.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/Application/AboutPanel.swift
macOS/DuckDuckGo/Preferences/Model/AboutPreferences.swift
macOS/DuckDuckGo/Preferences/View/PreferencesAboutView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1210823981470909?focus=true
This change sets macOS Alpha builds version to 9999.9.9 and sets commit sha in the Info.plist to be displayed in the app.
1. Update internal build to 1.148.0.493
2. Download Alpha build via Debug Menu -> Download DuckDuckGo Alpha Build
3. Launch the Alpha build and verify that About settings look like this (ALPHA label will appear only after setting internal user state)
4. Select Main Menu -> DuckDuckGo -> About DuckDuckGo and verify that the ALPHA label is present.
5. Run `plutil -extract DDG_COMMIT_SHA raw /Applications/DuckDuckGo\ Alpha.app/Contents/Info.plist` and verify that it outputs `bcf0a70aeed3ddc1584600910d0638d3f0acd9a8`
—
[Definition of …

Set commit SHA in Info.plist for alpha builds

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/DaxLogoManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204912272578138/task/1210818370845271?focus=true
CC:
Prevents conflicting SwiftUI / UIKit layout by converting logo view into UIView.
1. Enable Search Input under AI Features
2. Focus in Search Input while browsing and on NTP.
3. In each case switch between Search and Duck.ai using toggle and swiping
4. Repeat pt. 3 with autocomplete visible and favorites visible (empty search term)
5. Rotate the device while Search Input is active.
Medium/High: Could not remove the UI hang entirely making app unusable (only for internal feature)
The hang was most likely caused by using keyboardLayoutGuide to layout and implicitly size a SwiftUI view. I tried applying `ignoresSafeArea` modifier but while it was not adjusting …

Prevent switcher hang by using UIKit for logo

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/SwipeContainerManager.swift
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210809108643490?focus=true
CC:
Recalculates ScrollView size and offset based on the target size and runs the change alongside the rotation transition.
1. Enable Search Input in AI Features
2. Select Duck.ai mode.
3. Rotate to landscape.
4. Verify the mode selection and offset is valid.
5. Verify selected mode is used to process the query.
6. Rotate back to portrait, revalidate steps 4 - 5
7. Select search, validate steps 3 - 6
Scroll offset may be not aligned to a page.
--- …

Adjust scroll content offset and size along rotation transition

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/SuggestionTrayManager.swift
iOS/DuckDuckGo/FavoriteHomeCell.swift
iOS/DuckDuckGo/FavoritesHomeViewSectionRenderer.swift
iOS/DuckDuckGo/FavoritesOverlay.swift
iOS/DuckDuckGo/SuggestionTrayViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210830406472517?focus=true
CC:
* Prevents adding the border around FavoritesOverlay when styled for Search Input.
* Renames the variable to avoid confusion, as the border is part of NTP styling right now.
1. Enable Search Input in AI Features.
2. Having Favorites, start search.
3. Make sure there's no top/bottom border around favorites.
4. Make sure the border is still visible when Search Input is disabled.
--- …

Don't show favorites border when Search Input active

---

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
SharedPackages/BrowserServicesKit/Sources/Navigation/Extensions/WKNavigationActionExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202406491309510/task/1210800458942617?focus=true
- disable the assertion warning when doing anchored same-doc navigations
1. Navigate to an anchored link (`<a href="#link"><br><br><br><a id="navlink">a navlink</a>`), validate everything's fine and the address bar is updated
The assertion removal brings no risks
Nothing
---

Remove the assertion

---

macOS/DuckDuckGo/DataImport/Logins/Firefox/FirefoxLoginReader.swift
macOS/UnitTests/DataImport/DataImportResources/TestFirefoxData/No Primary Password/logins-all-deleted.json
macOS/UnitTests/DataImport/DataImportResources/TestFirefoxData/No Primary Password/logins-with-deleted-entries.json
macOS/UnitTests/DataImport/DataImportResources/TestFirefoxData/No Primary Password/logins-with-malformed-entries.json
macOS/UnitTests/DataImport/DataImportResources/TestFirefoxData/Primary Password/logins-all-deleted.json
macOS/UnitTests/DataImport/DataImportResources/TestFirefoxData/Primary Password/logins-with-deleted-entries.json
macOS/UnitTests/DataImport/DataImportResources/TestFirefoxData/Primary Password/logins-with-malformed-entries.json
macOS/UnitTests/DataImport/FirefoxLoginReaderTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1202926619870900/task/1210798627853091?focus=true
Firefox password import is failing with DecodingError.keyNotFound for hostname field during JSON parsing. This is because the import code attempts to decode deleted login entries that lack required fields like hostname. These are common entries for users who have synced.
I've fixed this by excluding "deleted": true entries as well as skipping over any entries that don't parse rather than failing the whole import.
1. Download Firefox https://download.mozilla.org/?product=firefox-stub&os=win&lang=en-US
2. Save some logins (Nav menu -> Passwords)
3. Click Sign In to Sync
4. Either sign up yourself or ask me for my test credentials
5. Delete >=1 login
6. Open DuckDuckGo
7. Go to File …

Firefox login import JSON decoding bug

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/NavigationActionBarView.swift
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1210823147637787?focus=true
When on duck.ai mode, if you type a valid URL (or the URL is already present) in the text field, the submit button should change to a globe, and pressing it should open the website instead of going to duck.ai
1. Enable the new input field on AI Features -> Search input
2. Type random queries on both search mode and duck.ai modes, check if they go to their respective options
3. Type a valid URL on both modes, check if we display a globe button in the FAB regardless of which mode you have selected, tapping on it (or go in the keyboard) should open the website
Incorrectly display the globe button when it …

Change duck.ai button to a globe when there's a valid URL

---

macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/Localization/Localizable.xcstrings
macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210845216393904?focus=true
This change updates 1 string in the UI and adds translations for another one related to text summarization.
Verify that AI Features settings look like this (the middle checkbox says “Show Duck.ai shortcuts in menus”):
---

Add translations for Duck.ai text summarization

---

iOS/DuckDuckGo/FavoriteIconView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1210844584732074?focus=true
CC: @amddg44 
* Fixes the size of the favicon background to prevent it from becoming smaller than required.
* Enforces the fake favicon size to match the NTP.
1. Add favorites for the following:
1. https://dummyimage.com/100/100/fff?text=page98
2. https://api.dicebear.com/9.x/adventurer/svg?seed=page98
3. Any SERP result
4. https://robohash.org/page81
5. https://hello.com/
2. Verify if they all look fine on NTP.
3. Enable Search Input
4. Focus on input, check if the favorite icons look the same as on NTP.
Sizing of the favorites on NTP may be off or they can be misaligned.
---
[Definition …

Prevent favicon background from scaling down

---

SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/SubscriptionUserScript/MockSubscriptionUserScriptHandler.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptHandlerTests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptTests.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Tab/TabExtensions/AIChatTabExtension.swift
macOS/DuckDuckGo/Tab/TabExtensions/SubscriptionTabExtension.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift
macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210749020623120?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1210754463607480?focus=true
1. "Debug" → "Feature Flag Overrides” → Others, check that paidAIChat feature flag is enabled if not then select 
2. "Debug" → "Feature Flag Overrides” → Others, check that PrivacyProAuthV2 feature flag is enabled if not then select it
3. “Debug” → “AI Chat” → "Web Communication” → “Set custom URL” set URL to https://euw-serp-dev-testing10.duck.co/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
4. Open Duck.ai it and should show your current subscription status
5. leave the tab open and subscibe
6. Reopen the previous Duck.ai Tab and check the UI reflects the subscription state …

Authentication change  subscription message

---

SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/SubscriptionUserScript/MockSubscriptionUserScriptHandler.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptHandlerTests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptTests.swift
iOS/DuckDuckGo/Subscription/SubscriptionURLNavigationHandler.swift
iOS/DuckDuckGoTests/Subscription/SubscriptionURLNavigationHandlerTests.swift
macOS/DuckDuckGo/Subscription/SubscriptionNavigationCoordinator.swift
macOS/UnitTests/Subscription/SubscriptionNavigationCoordinatorTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204186595873227/task/1210821475040699?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1210810535079321
On both platforms
1. "Debug" → "Feature Flag Overrides” → Others, check that paidAIChat feature flag is enabled if not then select it
2. "Debug" → "Feature Flag Overrides” → Others, check that PrivacyProAuthV2 feature flag is enabled if not then select it
3. “Debug” → “AI Chat” → "Web Communication” → “Set custom URL” set URL to https://euw-serp-dev-testing10.duck.co/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1
4. Make sure you are NOT subscribed
5. Go to Duck.ai settings
6. Click on Subscribe to DuckDuckGo
7. Check it navigates to the subscription flow and the url contains the origin …

pass origin to subscription purchase url from duck.ai

---

macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScriptHandling.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebar.swift
macOS/DuckDuckGo/Tab/AIChatSidebar/AIChatSidebarViewController.swift
macOS/UnitTests/AIChat/AIChatUserScriptHandlerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210855725388312?focus=true
This change changes behavior of the summarization source link when in a full-size tab.
The link will now open in a new tab instead of the current tab, and when such tab is already open,
it will switch to the open tab instead.
The behavior for sidebar chats is the same and clicking the link will open the website in the current tab.
1. Have sidebar enabled
2. Summarize some text (it happens in the sidebar).
3. Navigate to another website in the same tab.
4. Click Summarization source link in the summarize chat bubble and verify that the source website is opened in the current tab.
5. Expand the sidebar to a full-size tab.
6. Click Summarization source link and verify that you’re redirected to an already …

Open summarization source links in new tab when Duck.ai chat is in a full-size tab

---

macOS/DuckDuckGo/Tab/TabExtensions/ContextMenuManager.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1142021229838617/task/1210860639120454?focus=true
Don’t show "Summarize with Duck.ai" context menu option on Duck.ai tabs.
1. Open Duck.ai chat and start a conversation (you can do it by summarizing text on some website)
2. If Duck.ai is in the sidebar, expand the sidebar to a full tab.
3. Select some text on Duck.ai, open context menu and verify that “Summarize with Duck.ai” option is not present.
---

Don't offer text summarization on Duck.ai

---

macOS/DuckDuckGo/AIChat/UserScript/AIChatUserScriptHandling.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199230911884351/task/1210855725388312?focus=true
Ensure that when opening a link from the sidebar always opens the URL in the current tab.
1. Make sure that sidebar is enabled in AI Features settings.
2. Open a website, select text, and activate “Summarize with Duck.ai” option from context menu.
3. Duplicate current website.
4. In the tab with the sidebar, navigate to another website.
5. Click the link in the summarization chat bubble and verify that the URL loads in the current tab.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) …

Don't switch to open tab when activating summarization source website link in the sidebar

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarButtonModel.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/VPNUpsellVisibilityManager.swift
macOS/DuckDuckGo/Onboarding/ContextualOnboarding/ContextualDialogsManager.swift
macOS/IntegrationTests/Onboarding/BrowserTabViewControllerOnboardingTests.swift
macOS/UnitTests/Fire/FirePopoverViewModelTests.swift
macOS/UnitTests/NetworkProtection/NetworkProtectionNavBarButtonModelTests.swift
macOS/UnitTests/NetworkProtection/VPNUpsellVisibilityManagerTests.swift
macOS/UnitTests/Onboarding/ContextualOnboarding/ContextualDialogsManagerTests.swift
macOS/UnitTests/Onboarding/ContextualOnboarding/OnboardingPixelReporterTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1210649122070618?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1210649122070619?focus=true
CC: @SabrinaTardio 
This PR adds targeting/appearance logic for the VPN upsell button.
* `VPNUpsellVisibilityManager` will decide whether to show the upsell button or not
* `NetworkProtectionNavBarButtonModel` subscribes to the manager’s output and refresh visibility of the button
* Added a publisher to `ContextualDialogsManager`
Since the feature is not ready yet, just make sure the regular flow works as expected:
1. Launch the app without a subscription -> VPN button should not show
2. Launch the app as subscriber -> VPN button should show
None: New logic is behind …

VPN Upsell - targeting logic

---

SharedPackages/VPN/Sources/VPN/NetworkProtectionOptionKey.swift
iOS/DuckDuckGo/NetworkProtectionTunnelController.swift
macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionTunnelController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206580121312550/task/1210845165145900?focus=true
Adds useful information to controller start failures
Test the VPN works fine in auth v1 and v2 for both macOS and iOS - or at least if it's not, that you don't see errors in the `controller_start` pixels.
Force failures in the iOS and macOS tunnel controllers and check that you see the correct error information in the pixels depending on which error you're forcing.
Medium.
I could've made a mistake in the logic, causing the tunnel not to start in either macOS or iOS.
NA
NA
--- …

Apple VPN: Adds useful information to controller start failures

---

.github/workflows/bsk_pr_checks.yml
.github/workflows/dbp_pr_checks.yml
.github/workflows/ios_build_hotfix_release.yml
.github/workflows/ios_bump_internal_release.yml
.github/workflows/ios_code_freeze.yml
.github/workflows/ios_end_to_end.yml
.github/workflows/ios_pr_checks.yml
.github/workflows/ios_sync_end_to_end.yml
.github/workflows/macos_build_hotfix_release.yml
.github/workflows/macos_bump_internal_release.yml
.github/workflows/macos_code_freeze.yml
.github/workflows/macos_pr_checks.yml
.github/workflows/macos_sync_end_to_end.yml
.github/workflows/macos_ui_tests.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1210878342031201?focus=true
This change sets up rules related to running various workflows concurrently, aiming to reduce the number
of unneeded workflow runs (e.g. made redundant by a new commit to a branch) and to guard us from errors
such as requesting internal release bump twice in a quick succession (e.g. by different team members that
haven’t communicated with each other).
1. Verify that these workflow runs have been cancelled (that’s because I pushed a commit while they were running):
* [bsk_pr_checks](https://github.com/duckduckgo/apple-browsers/actions/runs/16497725260?pr=1479)
* [dbp_pr_checks](https://github.com/duckduckgo/apple-browsers/actions/runs/16497725273?pr=1479)
* …

Set concurrency requirements for CI workflows

---

DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
SharedPackages/AIChat/Sources/AIChat/macOS/PublicAPI/AIChatRemoteSettingsProvider.swift
SharedPackages/BrowserServicesKit/Package.swift
macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
macOS/DuckDuckGo/AIChat/AIChatMenuVisibilityConfigurable.swift
macOS/DuckDuckGo/AIChat/AIChatRemoteSettings.swift
macOS/DuckDuckGo/AIChat/AIChatSummarizer.swift
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
macOS/DuckDuckGo/Preferences/Model/AIChatPreferences.swift
macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlagCategory.swift
macOS/UnitTests/AIChat/AIChatMenuConfigurationTests.swift
macOS/UnitTests/Menus/MainMenuTests.swift
macOS/UnitTests/Menus/MoreOptionsMenuTests.swift
macOS/UnitTests/NewTabPage/NewTabPageAIChatShortcutSettingProviderTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210702047347360?focus=true
CC:
Adds feature flag for the global AI switch and improves the logic used to show/hide elements based on its value.
1. Ensure `aiChatGlobalSwitch` feature flag is disabled.
2. Open settings -> AI Features
3. Verify that section options should be unchanged as in production build
--
4. Enable `aiChatGlobalSwitch` feature flag.
5. Open settings -> AI Features
6. "Enable Duck.ai" check box should be visible and toggled
7. Uncheck "Enable Duck.ai" option
8. Verify that all Duck.ai related options and in the app all AI related features are hidden (sidebar, Duck.AI menu and address bar shortcuts, summarisation)
--
9. Disable `aiChatGlobalSwitch` feature flag.
10. Verify …

Global AI Switch 1. Add feature flag and improve logic

---

macOS/DuckDuckGo/Updates/UpdateCheckState.swift
macOS/DuckDuckGo/Updates/UpdateController.swift
macOS/UnitTests/Updates/UpdateCheckStateTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210873627461949?focus=true
Failed update checks no longer count towards the update rate-limiting quota.
1. Launch the app without a connection.
2. Open release notes.
3. You'll see empty release notes - this is a known issue that's unrelated to rate-limiting.
4. Reconnect to internet
5. Go to Settings > About, click check for updates
6. Ensure the release notes are showing
Low.
Nothing I can think of.
NA
NA
---

macOS: Failed update checks no longer count towards the update rate-limiting quota

---

iOS/DuckDuckGo/Subscription/AsyncHeadlessWebview/AsyncHeadlessWebView.swift
iOS/DuckDuckGoTests/Subscription/AsyncHeadlessWebViewSettingsTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210857545758178
Security Triage: https://app.asana.com/1/137249556945/project/1199892415909552/task/1210867225045705
To enable purchase of Subscriptions via Stripe in our modal web view, we are adding `checkout.stripe.com` to the list of allowed domains. See [related security triage](https://app.asana.com/1/137249556945/project/1199892415909552/task/1210867225045705).
**Note:** E2E testing of actual Stripe purchase will be done once FE changes are in place.
1. Ensure you have no active subscription
2. Launch, navigate to the Subscription landing page, and purchase a subscription via the app store
3. Ensure it succeeds as expected and the subscription is active on the device
Low
Subscription purchase is impacted. 
—
[Definition of …

iOS: Add checkout.stripe.com to Async Web View Allowed Domains

---

iOS/Core/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210903469838658?focus=true
CC:
Enable feature flag override for Set As Default browser PiP tutorial
1. Check Feature Flag in Debug menu supports override as per attached screenshot
---

Make default browser PiP tutorial feature flag overridable

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/392891325557410/task/1210858335866742?focus=true
CC:
1. Enter some text into the unified text view and select it.  The colour of the handles should match the same on the existing omnibar.
Tint applies in some unexpected way
---

[iOS][AI Search Toggle] fix selection handle tint

---

.github/workflows/bsk_pr_checks.yml
.github/workflows/dbp_pr_checks.yml
.github/workflows/ios_nightly.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199333091098016/task/1210905604852698?focus=true
CC:
This PR updates unit test workflows to use `check_retries`, in cases where we are using the retry iterations feature. Without this change, a retry can succeed but the test summary will show as a failure.
---

Add `check_retries` to unit test jobs that are missing it

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/ContentBlocking/ContentBlockingRulesCompilationTask.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/949243614371883/task/1210912586079501?focus=true
CC:
Call WebView init before CBR compilation.
1. Add `_ = WKWebView()` to `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: ` before anything else
2. Comment out `_ = WKWebView()` in `ContentBlockingRulesCompilationTask` at line 95
3. Clean install and run the app with above code
4. App should crash
5. Remove line from app delegate
6. Comment back in the line in `ContentBlockingRulesCompilationTask`
7. Run the app - it should launch
8. Smoke test the app
Unexpected consequences of init WebView in this location
---
[Definition of …

[iOS] CBR Crash Fix

---

macOS/IntegrationTests/Onboarding/BrowserTabViewControllerOnboardingTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210912369794512
CC:
Disable an onboarding test that causes test suite flakiness 
1. Ensure CI pass.
---

[macOS][Flaky Tests] Disable onboarding test to check the highglight view is dismissed correctly

---

SharedPackages/BrowserServicesKit/Tests/DDGSyncTests/DDGSyncTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1210924861103056?focus=true
CC:
- disable testWhenSyncGetsDisabledBeforeStartingOperationThenOperationReturnsEarly
- ensure CI is green
No
Nothing
---

disable testWhenSyncGetsDisabledBeforeStartingOperationThenOperationReturnsEarly

---

SharedPackages/BrowserServicesKit/Sources/MaliciousSiteProtection/Services/UpdateManager.swift
SharedPackages/BrowserServicesKit/Tests/MaliciousSiteProtectionTests/MaliciousSiteProtectionUpdateManagerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1209019077143944?focus=true
- Fix testWhenPeriodicUpdatesAreCancelled_noFurtherUpdatesReceived flakiness by awaiting for `Task.value` after the update task cancellation
- Refactor `testWhenPeriodicUpdatesStart_forScam_andFlagOff_dataSetsAreNotUpdated` so it doesn't actually sleeps for 1sec since we're using mock clock in the tests but instead rely on sleep interval expectations
1. Validate CI is green
2. Run `MaliciousSiteProtectionUpdateManagerTests` locally for 1000 times (right click the TestCase in the Tests inspector and choose Test repeatedly), validate the tests pass
No
Nothing
--- …

fix flaky MaliciousSiteProtectionUpdateManagerTests

---

iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserCore/CheckDefaultBrowserService/CheckDefaultBrowserService.swift
iOS/LocalPackages/SetDefaultBrowser/Tests/SetDefaultBrowserTests/CheckDefaultBrowserServiceTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210878147492704?focus=true
CC:
We observed a few crashes happening in SystemCheckDefaultBrowserService. This is a wrapper on Apple [isDefault(.webBrowser)](https://developer.apple.com/documentation/uikit/uiapplication/isdefault(_:)). 
The crashes are occurring only for users on iOS 18.2, which leads us to believe that they may be caused by an internal Apple issue with this framework in that version.
This PR defensively address the issue by ensuring the API can be queried only by users running iOS 18.3+ as discussed in [Asana](https://app.asana.com/1/137249556945/task/1210878147492704/comment/1210903471317985?focus=true).
1. Ensure CI pass.
Low: While this fix will prevent showing the …

[iOS][Set As Default Browser] Increase the minimum version to check if the browser is the default to 18.3

---

SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionURL.swift
SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionURLTests.swift
SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptHandlerTests.swift
iOS/DuckDuckGo/Subscription/SubscriptionURLNavigationHandler.swift
iOS/DuckDuckGoTests/Subscription/SubscriptionURLNavigationHandlerTests.swift
macOS/DuckDuckGo/Subscription/SubscriptionNavigationCoordinator.swift
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Resources/Localizable.xcstrings
macOS/UnitTests/Subscription/SubscriptionNavigationCoordinatorTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210891403305046
On both iOS and macOS
1. Make sure paidAiChat feature flag is on and you are not subscribed
2. Go to Duck.ai
3. Go to Duck.ai settings and click on “Subscribe to DuckDuckGo"
4. On macOS you should see the landing page with Duck.ai as first item also the URL in the address bar should contain featurePage=duckai parameter
5. on iOS from the debugger look for "HeadlessWebViewCoordinator - webView(_:decidePolicyFor:decisionHandler:) .allow: https://duckduckgo.com/subscriptions” and check it has the featurePage=duckai parameter parameter
<!— 
Focus on what …

Open subscriptions landing page on Duck.ai emphasised page

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210916875279073?focus=true
CC:
Prevents showing unpopulated predictive text suggestions and in the same time prevents Dax logo from jumping up during mode toggle.
1. Enable Search Input under AI Features settings.
2. Enter Search Input and toggle back and forth between two modes. Verify y location is not changing when doing that.
3. Type anything and switch to other mode, do any interaction with the text view (e.g. change caret position). Verify the accessoryView is updated to a proper value, which is no suggestions for Search, suggestions for Duck.ai.
4. Repeat pt 3 starting with other mode.
Suggestions are not working as expected or not …

Reload Search Input's input views only after text change

---

macOS/DuckDuckGo/Preferences/View/PreferencesSidebar.swift
macOS/LocalPackages/SubscriptionUI/Sources/SubscriptionUI/Resources/Subscription.xcassets/Icons/Close-16.imageset/Contents.json

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210977456754447?focus=true
1. Make sure paidAiChat and subscriptionRebranding feature flags are on
2. Test the app in dark mode and in Subscription Settings and check the X of the rebranding message is visible
3. Check the New badge next to Duck.ai in settings items is like in https://www.figma.com/design/uLcRB1C1ifps7pwQv6Mnkb/Subscription-Settings---Rename-from-Privacy-Pro-to-DuckDuckGo-Subscription?node-id=0-1&p=f&m=dev 
Note: Stephen has already looked at screenshots and said they are ok
<!— 
- How does this affect …

Fix X on rebranding message and adjust new badge

---

iOS/DuckDuckGo/DuckPlayer/WebUI/WebDuckPlayerNavigationHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210379416433601/task/1210922940139837?focus=true
This PR reverts the changes from #1310 that prevented Duck Player audio from continuing in background tabs.
- Removed media playback suspension when tabs become inactive
- Removed media playback resumption when tabs become active  
- Reverted `WebDuckPlayerNavigationHandler.swift` to allow audio to continue playing when switching between tabs
The previous implementation that paused media when switching tabs was causing issues with the intended Duck Player experience. Users expect audio to continue playing in background tabs, similar to standard web video players.
Make sure CI is green.  No new functionality added.
--

Revert "Fix Duck Player audio continuing in background tabs"

---

iOS/DuckDuckGo/SettingsCell.swift
iOS/DuckDuckGo/Subscription/Views/SubscriptionSettingsView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210964598062836?focus=true
1. Turn SubscriptionRebranding feature flag on
2. Go to Subscription settings and check the rebranding message appears semibold (Igor checked and approved the ship review)
3. Check Edit email and add to device look like the other cell (Igor checked and approved the ship review)
4. Test both link work
5. Check duck.ai “New” badge is centered (Igor checked and approved the ship review)
<!— 
- How does this affect performance?
- What documentation needs updating?
- How …

make subscription rebranding message semibold

---

iOS/DuckDuckGo/OnboardingExperiment/OnboardingIntro/OnboardingIntroViewModel.swift
iOS/DuckDuckGoTests/OnboardingIntroViewModelTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210974837151617?focus=true
CC:
1. Start Onboarding flow. (Degug Menu -> Onboarding -> Preview Onboarding Intro)
2. On ‘Privacy Activated!’ screen, tap ‘Choose your browser’ button
3. Ensure that “m_preonboarding_choose_browser_pressed” is fired.
Low: small bug fix for missing pixel
Nothing really
---

[iOS][Onboarding] Re-add removed pixel when user taps ‘Choose your browser’ CTA

---

iOS/DuckDuckGoTests/DuckPlayer/DuckPlayerNativeUIPresenterTests.swift
iOS/DuckDuckGoTests/DuckPlayer/DuckPlayerViewModelTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204099484721401/task/1210917586418509?focus=true
Tech Design URL: N/A
CC: N/A
Removed two flaky tests from the DuckPlayer test suite to improve test reliability:
- `testRoundedPageSheetDismissal_TriggersReEntryPill` from DuckPlayerNativeUIPresenterTests
- `testHandleYouTubeNavigation_SameVideo_NoPublisherEvents` from DuckPlayerViewModelTests
CI should be 🥬 
**Impact Level: None**

Remove flaky DuckPlayer tests

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/DaxLogoManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1210980392990014?focus=true
CC:
Disables interactions on logo, so it does not capture swipe gestures.
1. Enable Experimental Address Bar
2. Open search, type something and try to tap on rows where the logo would normally be.
3. Try to swipe between modes swiping in the area where the logo would be displayed.
---

Prevent capturing touch events by Dax logo

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/SuggestionTrayManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/392891325557410/task/1210977117977431?focus=true
CC:
Shows suggestions when tapping on text in the address bar, but not for URLs which are shown as fixed height still.
1. Type something in that has suggestions (e.g. music)
2. Perform the search
3. Tap on the text in the address bar
4. The suggestions should show
5. Cancel that and click on a link in the serp
6. After website loads tap the address bar
7. URL should be shown (with logo or favorites below) on a single line which expands when tapped (as before).
--- …

[iOS] fix auto suggestions in new toggle

---

SharedPackages/BrowserServicesKit/Sources/DDGSync/SyncConnectionController.swift
SharedPackages/BrowserServicesKit/Tests/DDGSyncTests/SyncConnectionControllerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1210707877097609?focus=true
I hastily made the whole connection controller an actor which was a bit of a sledgehammer tactic, particularly given this would cause a deadlock if its delegate were to call back into it during a callback. As such, I've made it a class again and instead extracted the mutable state into an actor.
1. Green UI tests https://github.com/duckduckgo/apple-browsers/actions/runs/16652014315
2. Could give sync a quick smoke test.
Can't really think of anything. This is correct use of actors.
--- …

Pull mutable connection controller state into separate actor

---

macOS/DuckDuckGo/AIChat/AIChatPixel.swift
macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift
macOS/PixelDefinitions/pixels/aichat_settings_pixels.json5

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210702047347360?focus=true
CC:
Pixels and pixel definitions
1. Open "AI Feature" settings
2. Click "Disable Duck.ai..." and confirm the dialog.
3. Verify that `m_mac_aichat_settings_global-toggle_off_daily` and `m_mac_aichat_settings_global-toggle_off_count` were fired.
4. Click "Enable Duck.ai"
5. Verify that `m_mac_aichat_settings_global-toggle_on_daily` and `m_mac_aichat_settings_global-toggle_on_count` were fired.
Pixels being fired in wrong use case
--- …

Global AI Switch 4. Pixels

---

macOS/DuckDuckGo/Application/AppDelegate.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1210994867667249?focus=true
This change updates launch pixel to be fired from appDidFinishLaunching.
1. Launch the app and filter logs by `ml_mac_app-launch`
2. Verify that the pixel was sent
3. Focus some other app and refocus the browser, verify that the pixel wasn’t sent.
None
---

Only fire launch pixel once per app launch

---

iOS/DuckDuckGo/TabSwitcherViewController+MultiSelect.swift
iOS/DuckDuckGo/TabSwitcherViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206226850447395/task/1210977113880963
CC:
Prevents performing batch updates with invalid internal state after the model has been modified by adding a new tab. 
This is a **speculative fix**, as I couldn't reproduce it manually. It can be reproduced by adding the following code at the very top of `TabSwitcherViewController.didChange(tab:)` and closing all of new tabs in tab switcher:
```
let hasNewTab = tabsModel.tabs.contains { $0.link == nil }
if !hasNewTab {
addNewTab()
}
```
What it does is it's modifying data model just before the batch updates caused by notifying observer is performed (e.g. after refresh or redirect happens for one of tabs), simulating the specific events timing that triggers the …

Prevent TabSwitcher collection inconsistency when adding new tab

---

macOS/DuckDuckGo/AIChat/AIChatMenuVisibilityConfigurable.swift
macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210702047347360?focus=true
CC:
This PR implements change to "AI Features" settings discussed in https://app.asana.com/1/137249556945/task/1210881343994632/comment/1210999247146358?focus=true :
- removing the "Open New Chats" section
- for all users using the global AI toggle default to the "sidebar enabled" experience
1. Disable the `aiChatGlobalSwitch` flag
2. Open settings -> AI Features
3. Uncheck "Open Duck.ai in the sidebar" option.
4. Open a new tab and navigate to a website
5. Click "Duck.ai" in the address bar to ensure full page "Duck.ai" navigation happens.
--
1. Enable the `aiChatGlobalSwitch` flag
2. Open settings -> AI Features
3. Ensure that the "Open New Chats" section with …

Global AI Switch 5. Settings update

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210975209610640?focus=true
Auto select the keyboard on duck.ai
1. Enable Experimental address bar for duck.ai (AI Features -> Experimental)
2. Add at least one favorite
3. Select the address bar, scroll the favorites to dismiss the keyboard
4. Go to duck.ai, validate that the keyboard is automatically selected

Auto select the keyboard on duck.ai

---

iOS/scripts/get_tasks_in_last_internal_release.sh
macOS/scripts/get_tasks_in_last_internal_release.sh

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1211022602360101?focus=true
Drop characters after matched task ID.
Run this and verify that it returns `1210975209610639`:
```
perl -pe 's|.*https://app.asana.com/0/[0-9]+/([0-9]+)(?:/f)?.*|\1|; \
s|.*https://app.asana.com/1/[0-9]+(?:/[0-9a-z/]*)?/task/([0-9]+)(:?/[0-9a-z/]*)?(?:\?focus=true)?.*|\1|; \
s|.*https://app.asana.com/1/[0-9]+/inbox/[0-9]+/item/([0-9]+)/story/([0-9]+)(?:\?focus=true)?.*|\1|' \
<<< 'https://app.asana.com/1/137249556945/project/1204167627774280/task/1210975209610639?\'
```
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | …

Fix regex for checking tasks in last internal release

---

macOS/DuckDuckGo/AIChat/AIChatMenuVisibilityConfigurable.swift
macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210702047347360?focus=true
CC:
This PR implements change to "AI Features" settings screen as discussed in https://app.asana.com/1/137249556945/task/1210881343994632/comment/1211022228644970?focus=true with the major changes being:
- keep the sidebar setting and nest it under "Show in address bar"
- when "Show in address bar" is unchecked then render nested sidebar setting in disabled (greyed out) state
- don't introduce any changes to sidebar/new conversation logic as part of the global switch feature
1. Open Settings -> AI Features
2. Ensure "Open Duck.ai in the sidebar" is rendered as a nested setting under "Show in address bar"
3. Disabling "Show in address bar" should also make "Open …

Global AI Switch 6. Move sidebar setting as a nested option

---

iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/DefaultBrowserPromptPresenter.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211030690383959?focus=true
CC:
The inactive modal will not be presented if any other modal is on the screen. This affects monitoring, as we will report showing the prompt, but since the prompt is only displayed once, the user may never see it.
This PR addresses the issue by presenting the full-screen prompt on top of any currently displayed modal, preserving the user's ongoing operation. When the prompt is dismissed, we will ensure that only the prompt is removed, and any previous modal remains on the screen.
1. In `DefaultBrowserModalPresenter` comment lines 43-48 and 50 to force inactive modal to appear when the app comes to foreground.
2. Open settings menu.
3. Background and foreground the app.
4. Ensure …

[iOS][Set As Default Browser] Fix prompt presentation when other modals are on screen

---

macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1210891681561459?focus=true
CC:
When we added the new visuals, we introduced a new way of calculating the size and position of the add tab button, which caused an issue when calculating the dragging space after the tab bar. Now, by removing the size of the add button, the drag space is okay again.
1. Grab the area that is just next to the add tab button (the +) in the tab bar.
2. Check that it is possible to drag the window when doing that.
Nothing.
--- …

macOS: Fix dragging space after tabs

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1210975282087890?focus=true
Do not automatically select the omnibar in the last onboarding step if the new omnibar is enabled
1. Start the onboarding
2. When available, go to settings and enable the AI Features experimental address bar
3. Continue the onboarding 
4. Check if the last step (high five) doesn't automatically select the omnibar
Regression in the omnibar

Fix onboarding on the new omnibar

---

iOS/DuckDuckGo/AppServices/SystemSettingsPiPTutorialService.swift
iOS/LocalPackages/SystemSettingsPiPTutorial/Sources/SystemSettingsPiPTutorial/SystemSettingsPiPTutorialManager.swift
iOS/LocalPackages/SystemSettingsPiPTutorial/Tests/SystemSettingsPiPTutorialTests/SystemSettingsPiPTutorialManagerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1211011039245367?focus=true
CC:
The [stack trace](https://errors.duckduckgo.com/organizations/ddg/issues/506092/?project=8&query=is%3Aunresolved+firstSeen%3A-9d&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=0) shows that the service introduced to show the PiP video crashes for several users when the app launches. The crash happens in AVPictureInPictureController.init. This PR attempts to fix the crash by deferring the initialisation of the video components till they’re needed.
Prerequisites:
- Ensure to test on a physical device. PiP is not supported on iOS simulator
**Scenario 1 - “Onboarding"**
1. Open Debug Menu.
2. Select ‘Onboarding’.
3. Tap ‘Preview Onboarding Intro’ …

[iOS][Picture In Picture] Attempt Fix crash

---

macOS/DuckDuckGo/TabBar/ViewModel/TabCollectionViewModel.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1211054479138273?focus=true
Ignore tab preloader in Fire Windows, as they don’t use HTML New Tab Page and don’t need preloading.
1. Launch the app
2. Enable `newTabPagePerTab` feature flag if disabled
3. Open Fire Window
4. Open new tab in the Fire Window
5. Verify that it doesn’t crash.
---

Fix a crash when opening new fire tab when newTabPagePerTab is enabled

---

iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/bg.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/cs.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/da.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/de.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/el.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/es.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/et.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/fi.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/fr.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/hr.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/hu.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/it.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/lt.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/lv.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/nb.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/nl.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/pl.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/pt.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/ro.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/ru.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/sk.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/sl.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/sv.lproj/Localizable.strings
iOS/LocalPackages/SetDefaultBrowser/Sources/SetDefaultBrowserUI/Resources/tr.lproj/Localizable.strings

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1210723746045883?focus=true
CC:
Import Translations for Default Browser Prompt for Inactive Users
Smoke test prompt to ensure UI translations are reflected.
1. Edit 'iOS Browser’ scheme -> Options -> App Language and pick one of the languages we support (E.g. Italian)
2. In “DefaultBrowserModalPresenter.swift” comment lines 43-48 and 50 to always show the prompt.
3. Run the app and ensure the prompt is showing translated strings.
---

Add translations for inactive default browser prompt

---

macOS/DuckDuckGo/Updates/ReleaseNotesTabExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1211096471236167?focus=true
Shows the "Update DuckDuckGo" blue button when the latest update is loaded from cache.
**Preparation:**
The steps described below can be used to both reproduce the original issue in the release branch and test it's fixed in this branch.
1. Make sure we get an update while testing:
1. Edit `macOS/Configuration/BuildNumber.xcconfig` and set the build number to 400.
2. Edit `macOS/Configuration/Version.xcconfig` and set the marketing version to 1.151.0
3. Run the app once in debug mode, and enable  the `autoUpdateInDebug` feature flag.
2. Make sure we set-up the exact conditions that make the bug show up.  Add the following two lines of code …

Fixes an issue where cached update information doesn't allow updating

---

iOS/DuckDuckGo/AppServices/AuthenticationService.swift
iOS/DuckDuckGo/AppServices/AutoClearService.swift
iOS/DuckDuckGo/UICoordination/OverlayWindowManager.swift
iOS/DuckDuckGoTests/AuthenticationServiceTests.swift
iOS/DuckDuckGoTests/Mocks/MockOverlayWindowManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201392122292466/task/1211024438380986?focus=true
1. Open any site.
2. Have authentication and data clearing turned off.
3. Background the app.
4. Open App Switcher and notice the site is visible.
5. Open the app and notice the site is immediately visible.
1. Turn on authentication.
2. Background the app.
3. Open App Switcher and notice the site is NOT visible.
4. Open the app and notice the site is NOT visible until authenticated.
1. Turn off authentication and turn on data clearing (5 minutes). You can change this line of code  `return elapsedTime > 5 * 60` to `return elapsedTime > 2` and wait 2 seconds instead of 5 minutes.
2. Also, add this line: `try? await Task.sleep(nanoseconds: 5_000_000_000)` under `await …

Fix content appearing when foregrounding app and before authentication

---

macOS/DuckDuckGo/Common/Extensions/NSOpenPanelExtensions.swift
macOS/DuckDuckGo/Common/Localizables/UserText.swift
macOS/DuckDuckGo/Localization/Localizable.xcstrings
macOS/DuckDuckGo/Menus/MainMenu.swift
macOS/DuckDuckGo/Menus/MainMenuActions.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
macOS/UnitTests/Menus/MainMenuTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/276630244458377/task/1211090698913983?focus=true
CC:
Adds a new menu item to the `File` menu that allows users to open PDFs, TXTs, and HTML files. The shortcut will be CMD+O (like other browsers)
1. Open the application, make sure you are an internal user and the feature flag `openFileFeature` is ON (it should be ON by default for internal users)
2. Check that if you go to the menu `File`, you see the `Open File` menu item above the `Open Location`.
3. Tap CMD+O, or tap the menu item
4. A picker should be opened
5. Select a pdf, txt or html file
6. Make sure the file is opened in a new tab
7. Close all the windows (but do not close the app)
8. Tap File -> Open File (or CMD+O)
9. A new window should be opened, …

macOS: Add Open File feature

---

.github/workflows/ios_build_hotfix_release.yml
.github/workflows/ios_bump_internal_release.yml
.github/workflows/ios_code_freeze.yml
.github/workflows/macos_build_hotfix_release.yml
.github/workflows/macos_bump_internal_release.yml
.github/workflows/macos_code_freeze.yml
.github/workflows/report_failed_release_workflow.yml
iOS/Gemfile.lock
iOS/fastlane/Pluginfile
macOS/Gemfile.lock
macOS/fastlane/Pluginfile

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201899738287924/task/1211100722861855?focus=true
Fastlane plugin PR: https://github.com/duckduckgo/fastlane-plugin-ddg_apple_automation/pull/55
This change leverages a new action from the fastlane plugin to post a comment to the release task notifying
about a failed workflow run. It’s applied to code freeze, bump internal release and build hotfix release workflows
for iOS and macOS.
See [this workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/17139845872/job/48624681985) for an example of the action being triggered.
See [this task](https://app.asana.com/1/137249556945/project/1201621708115095/task/1211112466075936?focus=true) for example comments.
Pretty low risk as the …

Notify release task about a failed workflow

---

.github/actions/measure-app-size/action.yml
.github/actions/measure-app-size/parse_app_size.sh
.github/workflows/ios_adhoc.yml
.github/workflows/ios_bump_internal_release.yml
.github/workflows/ios_code_freeze.yml
.github/workflows/ios_release.yml
iOS/adhocExportOptions.plist
iOS/alphaAdhocExportOptions.plist
iOS/alphaExportOptions.plist
iOS/appStoreExportOptions.plist

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1211098882149655
CC:
Add iOS App Size Tracking to CI Workflows
**Summary**
- Implemented app size measurement for iOS ad-hoc builds and release builds
- Created reusable GitHub Action to parse App Thinning Size Reports and send pixel metrics
- Integrated with existing workflows
**Changes Made**
New GitHub Action: measure-app-size
- Script: Parses "App Thinning Size Report.txt" to extract universal variant sizes
- Outputs: Download size (compressed) and installation size (uncompressed)
- Pixels: Automatically sends pixel metrics to improving.duckduckgo.com/t/ with app version and build number parameters
Workflows Integrations
ios_release.yml
- Added: Optional measure-app-size boolean input …

[QWD][iOS] Autogenerate app size report and fire pixels for release build

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
iOS/Core/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211003501974970?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1211032403913073?focus=true
Following up on https://github.com/duckduckgo/privacy-configuration/pull/3623, add the subfeature `inactivityNotification` to `BrowserServicesKit` and `FeatureFlag`
1. Build app and run
None. The subfeature is not used anywhere. 
None. The subfeature is not used anywhere. 
---

[iOS] Add Provisional Push Notification Local Config

---

macOS/DuckDuckGo/Common/Extensions/NSOpenPanelExtensions.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211126561190944?focus=true
CC:
Limit the file types we can open from the `Open File` menu item. The main problem before was that if we used the whole range of images, some types of files (like .psd) would open as a download instead of opening the file in the browser.
1. Open the app
2. Tap CMD+O, or go to File -> Open File
3. Make sure that only PNG, GIF, JPEG, SVG, and WebP images can be opened.
— …

macOS: Limit file types in Open File menu item

---

.github/actions/measure-app-size/action.yml

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203301625297703/task/1211119966980600?focus=true
CC:
Remove unit from app size to make Grafana transformations easier. 
Check CI Run https://github.com/duckduckgo/apple-browsers/actions/runs/17149525701
---

[QWD][iOS] Remove unit from sizes before sending the pixels for easier transformation

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1211128949335601?focus=true
CC:
Fixes toolbar items not updating properly when showing new tab page.
1. Launch the app clean - toolbar buttons shows bookmarks and passwords
2. Open web page - toolbar buttons shows back/forward
3. Open new tab page - toolbar buttons shows bookmarks and passwords
4. Repeat above but use fire button
5. Repeat with experimental input turned off
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | [Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552) | [Tech Design Template](https://app.asana.com/0/59792373528535/184709971311 …

fix toolbar items on new tab page

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/TextEntry/SwitchBarTextEntryView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/392891325557410/task/1210916875279070?focus=true
CC: @Bunn 
Fixes multi-line text clearing in the experimental search experience.
1. Enable the new experience (Settings > AI Features > Experimental)
2. Perform a search for Lorem Ipsem and either use the SERP or DuckAi to generate some for you
3. Copy and paste a large chunk of text into the field and scroll it
4. Tap the clear button, the field should return to a single line height
5. Visit a web site
6. Tap the url, the field should populate to a single line
7. Smoke test around entering URLs / searches, browsing and asking Duck.ai
Could break the input field
---
[Definition of …

[iOS][Duck.ai input] fix multi-line text clearing in new search experience

---

iOS/PixelDefinitions/pixels/push-notification.json5

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211003501974958?focus=true
Tech Design URL: https://app.asana.com/1/137249556945/project/481882893211075/task/1211032403913073?focus=true
Added a new pixel definition: `m_push-notification_local-provisional_inactive-user-tap`
- Fires when a user taps a local provisional push notification scheduled due to inactivity to measure engagement with provisional push notifications on iOS
- Captures: appVersion, pixelSource, daysInactive, copyNumber, and form_factor.
1. Build and run the app.
2. Confirm parameters are correctly defined.
No risks — pixel definition only
Likely none. Incorrect parameter type definitions could lead to dropped events.
Definition follows schema conventions
- Added param `daysInactive` due to …

[iOS] Add Push Notification Pixel Definition

---

macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211141466427685?focus=true
Enable Feature Flag for the duck.ai SERP settings
1. Already tested here https://github.com/duckduckgo/apple-browsers/pull/1760

[macOS] Enable feature flag for duck.ai SERP settings

---

iOS/Core/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1199230911884351/task/1211143145900569?focus=true
Enable Feature Flag for the duck.ai SERP settings
1. Already tested here https://github.com/duckduckgo/apple-browsers/pull/1758

[iOS] Enable feature flag for duck.ai SERP settings

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/NavigationActionBarView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201011656765697/task/1211142604441314?focus=true
Remove the return button from the search mode on the new experimental bar experience
1. Enable AI Features experimental address bar
2. Select the address bar, make sure we don't display the return key on search mode, only on duck.ai
Don't display the return key on duck.ai

Remove the return button from the search mode [Experimental address bar]

---

SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1148564399326804/task/1211121799241568?focus=true
Internal feature flags related to NTP search box replaced with remote feature flags
1. Run the app and make sure the NTP search box is visible only for internal users
2. Also, make sure the NTP for internal users is independent for each tab (you can have separate states of New Tab Page on each tab)
NTP search box will be visible for external users sooner than planned
-
--- …

NTP feature flags connected to Privacy Configuration

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211121614418052?focus=true
Ensure Legacy Omnibar Pixel is Only Sent When Input is Legacy Mode
1. Launch and set input to legacy mode
2. Tap the ai chat button in the omnibar when the omnibar is unfocused
3. Ensure `m.aichat.legacy.omnibar.aichat.button.pressed.count` is sent
4. Tap the ai chat button in the omnibar when the omnibar is focused
5. Ensure `m.aichat.legacy.omnibar.aichat.button.pressed.count` is sent
6. Switch to new input mode
7. Tap the ai chat button in the omnibar when the omnibar is unfocused
8. Ensure `m.aichat.legacy.omnibar.aichat.button.pressed.count` is **NOT** sent
Low, minor bug fix
—
[Definition of …

iOS: Ensure Legacy Omnibar Pixel is Only Sent When Input is Legacy Mode

---

macOS/DuckDuckGo/Updates/ReleaseNotesTabExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/276630244458377/task/1211161833367142?focus=true
Fixes an issue with cached updates showing an update button when they shouldn't
Before testing, run the app once and see what the latest version of the app is in the release notes page.  Take note of version and build.
1. Open Version.xcconfig and match the latest version
2. Open BuildNumber.xcconfig and match the latest version
3. Run the app once without modifications so it caches the correct last version.
4. Disconnect from internet.
5. Run the app, ensure you see the same as before.  There should be NO update button.
6. Open Version.xcconfig and be below the latest version
7. Open BuildNumber.xcconfig and be below the latest version
4. Disconnect from internet if necessary.
5. …

Fixes an issue with cached updates showing an update button when they shouldn't

---

SharedPackages/BrowserServicesKit/Tests/NavigationTests/Helpers/DistributedNavigationDelegateTestsHelpers.swift
SharedPackages/BrowserServicesKit/Tests/NavigationTests/Helpers/NavigationTestHelpers.swift
SharedPackages/BrowserServicesKit/Tests/NavigationTests/Helpers/WKWebView+KillWebContentProcess.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1205237866452338/task/1211041653522693?focus=true
- Terminate web content process after each Navigation test run to reduce the resource consumption
1. Validate CI is green
---

kill web content process after each Navigation test

---

macOS/DuckDuckGo/Updates/UpdateController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1211168798749256?focus=true
This change adds a `#DEBUG` and `autoupdateInDEBUG` feature flag check to
`checkForUpdateRespectingRollout` that is now also called in response to
didResignKeyNotification event.
1. Set build number in BuildNumber.xcconfig to a value lower than the latest one (e.g. 500).
2. Launch the app
3. Make sure that `autoupdateInDEBUG` feature flag is disabled. If you had it enabled, relauch the app.
4. Launch the app and wait for a bit.
5. Quit the app and recompile and rerun.
6. Verify that it runs fine (and the compilation doesn’t fail on code signing issue).
None: should only affect debug builds.
---
[Definition of Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) | …

Don't check for updates in macOS Debug builds

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/715106103902962/task/1211196986755529?focus=true
CC: @aataraxiaa @miasma13 
1. Enable experimental search 
2. Search for batman
3. Long press tab button to open a new tab (or use new tab from tabswitcher)
4. Ensure omnibar is in new state
Break new tab page
---

fix bug where previous tab data would show in new tab omnibar

---

iOS/DuckDuckGo/WebTrackingProtectionView.swift

Fixed circle border rendering for icons in the Web Tracking Protection settings on iOS. The icons were not showing circular borders around them as intended.
1. Navigate to Settings → Web Tracking Protection
2. Scroll down to view the feature grid with icons
3. Verify that each icon now has a visible circular border around it
**Low**: Minor visual improvement to existing feature. No functional changes.

iOS: Fix circle border rendering in Web Tracking Protection settings

---

SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/QueueManaging/BrokerProfileJobQueueManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203581873609357/task/1211198697406015?focus=true
CC:
In a certain error case resetMode()  isn't called, which could potentially cause the queue to block scheduled operations from running
Make it so the completion handler is always called after resetting mode
1. Smoke test PIR on macOS
2.
---

PIR: queue manager resetting logic changes

---

iOS/DuckDuckGoTests/AppUserDefaultsTests.swift
iOS/DuckDuckGoTests/LargeOmniBarStateTests.swift
iOS/DuckDuckGoTests/SmallOmniBarStateTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210947754188321/task/1211181054046850
This PR is an addition to the main PR https://github.com/duckduckgo/apple-browsers/pull/1790 that adds unit tests to it.
None: unit tests
---

[iOS] Option to hide refresh in address bar - unit tests

---

iOS/DuckDuckGo/SettingsViewModel.swift

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211221733324862?focus=true
CC:
Prevents over-firing the enable experimental duck.ai pixel by only triggering the call if the value really has changed.
Also removed some dead code.
1. Go to Settings > AI Features and toggle between the input states
2. Ensure pixel is fired and state change is applied
3. Go to Settings > AI Features and tap the currently selected state several times
4. Ensure no pixel is fired and the state is not changed 
Changing the state of the experimental input might break.
--- …

prevent over firing the enabling experimental duck.ai pixel on iOS

---

macOS/DuckDuckGo/StateRestoration/AppStateRestorationManager.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1209825025475019/task/1211255127092280?focus=true
CC: @tomasstrba 
There is a new post-crash restore prompt that is triggered when the app does not terminate as expected. This can be triggered by sudden app terminations in test runs, causing the prompt to appear and interfere with unrelated UI tests.
This PR disables the prompt during UI tests by skipping the check for unexpected app terminations. This is a bit risky because it alters the app behavior during UI tests, but as of now we aren’t doing any explicit UI testing of this prompt and it causes spurious failures. This allows the prompt to continue working normally outside of UI tests, e.g. in normal runs of debug/review builds. (I’ll raise this in the …

macOS: Prevent post-crash restore prompt from interfering with UI tests

---

SharedPackages/BrowserServicesKit/Sources/Configuration/CustomConfigurationURLProvider.swift
SharedPackages/BrowserServicesKit/Tests/ConfigurationTests/ConfigurationURLProviderTests.swift
iOS/DuckDuckGo/DebugScreensViewModel.swift
iOS/IntegrationTests/Configuration/ConfigurationManagerIntegrationTests.swift
macOS/DuckDuckGo/Application/AppConfigurationURLProvider.swift
macOS/DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift
macOS/DuckDuckGo/Menus/MainMenuActions.swift
macOS/IntegrationTests/Configurations/ConfigurationManagerIntegrationTests.swift
macOS/UnitTests/AppDelegate/AppConfigurationURLProviderTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204912272578138/task/1211185941851033
1. Run defaults write com.duckduckgo.macos.browser.debug custom.configuration.url https://jsonblob.com/api/1404775931268227072
2. open the app foo to the debug menu and check the privacy config url is not overriden
3. override it from the debug menu and check the value is updated
4. Reset the configuration url from the debug menu and check it is updated
Low: Internal tooling but touching prod code
—

macOS: Fix config url overriding bug

---

iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarSubmissionMetrics.swift
iOS/DuckDuckGoTests/SwitchBar/SwitchBarSubmissionMetricsTests.swift
iOS/PixelDefinitions/pixels/experimental_omnibar_metrics.json5

Task/Issue URL: https://app.asana.com/1/137249556945/task/1211206058788136
Add metrics to understand text input patterns - query/prompt length distribution for searches vs Duck.ai usage  
Add `text_length_bucket` parameter to 2 existing pixels:
1. `m_aichat_experimental_omnibar_query_submitted`
2. `m_aichat_experimental_omnibar_prompt_submitted`
* **Prereqs**: Enable experimental omnibar, ensure in search mode
* **Steps**: Type short query (1-15 chars) → Submit
* **Expected**: `m_aichat_experimental_omnibar_query_submitted` pixel fires with `text_length_bucket: "short"`
* **Prereqs**: Ensure in search mode
* **Steps**: Type medium query (16-40 chars) → Submit
* **Expected**: `m_aichat_experimental_omnibar_query_submitted` pixel fires with `text_length_bucket: "medium"`
* **Prereqs**: …

iOS: New Search/Duck.ai Input Metrics - Query/Prompt Length Distribution

---

SharedPackages/BrowserServicesKit/Sources/SyncDataProviders/Bookmarks/internal/BookmarkEntity+Syncable.swift
SharedPackages/BrowserServicesKit/Sources/SyncDataProviders/Bookmarks/internal/BookmarksResponseHandler.swift
SharedPackages/BrowserServicesKit/Sources/SyncDataProviders/Common/MetricsEvent.swift
iOS/Core/BookmarksStateValidation.swift
iOS/Core/LegacyBookmarksCoreDataStorage.swift
iOS/Core/LegacyBookmarksStoreMigration.swift
iOS/Core/PixelEvent.swift
iOS/Core/SyncMetricsEventsHandler.swift
iOS/DuckDuckGo/AppConfiguration/AppConfiguration.swift
iOS/DuckDuckGo/AppConfiguration/PersistentStoresConfiguration.swift
iOS/DuckDuckGo/AppLifecycle/AppStates/Foreground.swift
iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
iOS/DuckDuckGo/AppLifecycle/AppStates/Simulated.swift
iOS/DuckDuckGo/AppLifecycle/AppStates/Terminating.swift
iOS/DuckDuckGo/AppServices/CrashCollectionService.swift
iOS/DuckDuckGo/BookmarksDatabaseSetup.swift
iOS/DuckDuckGoTests/BookmarksDatabaseSetupTests.swift
iOS/DuckDuckGoTests/BookmarksMigrationTests.swift
iOS/DuckDuckGoTests/BookmarksStateValidationTests.swift
iOS/PixelDefinitions/pixels/crash_pixels.json5
macOS/DuckDuckGo/Sync/SyncMetricsEventsHandler.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211050177427683?focus=true
CC: @brindy 
1. Added 5 diagnostic parameters to identify root causes (sync status, recent errors, file marker presence)
2. Replaced 1 generic database error pixel with 10 specific error pixels for precise failure identification
3. Added pixel to track sync attempts to delete root folders
4. Added pixel to correlate structure loss with app crashes
5. Refactored legacy fatalError calls to structured error throwing with detailed tracking
6. Added file marker system to possibly distinguish backup restores from actual db corruption
1. Since there is no straightforward way to confirm that all errors are handled, the recommended approach is to review each error type originating from the …

Add more metrics and diagnostics to better understand bookmarks lost structure issue

---

iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414709148257752/task/1211140989378405?focus=true
CC:
Adds a layout reset for iOS 26 and later for invalid/missing keyboard frame updates when keyboard is shown and hidden rapidly.
On both iOS 18 and iOS 26 (using simulator is fine)
1. Set address bar position to bottom
2. Open SERP with any query
3. Tap on SERP Region filter and close the dialog.
4. OmniBar and keyboard will attempt to show and hide quickly.
5. Verify OmniBar position updates properly.
6. Verify find in page layout is not broken.
7. Open a few other tabs and browse to any URL and do a keyboard smoke check.
Low: Minor visual changes, small bug fixes, improvement to existing features. Fix targets iOS 26 only.
Because of additional keyboard frame …

Add a workaround for invalid keyboard frame on iOS 26

---

macOS/DuckDuckGo/MainWindow/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201048563534612/task/1211298478693282?focus=true
CC:
Crash triggered by changing accessibility setting change fixed
1. Run the app
2. Go to System Settings → Accessibility → Display → and toggle "Invert Colors"
Technically almost nothing
---

Crash related to accessibility setting change fixed

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/Application/AppDelegate.swift
macOS/DuckDuckGo/Updates/LatestReleaseChecker.swift
macOS/UnitTests/Updates/LatestReleaseCheckerTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1211319503505031?focus=true
CC:
This PR adds the class responsible for getting the latest version available of the App Store build from our CDN. This PR only adds the code; it doesn’t connect it yet. That will come in follow-up PRs.
Add this piece of code to the `applicationDidFinishLaunching`:
```swift
Task {
try? await LatestReleaseChecker().getLatestReleaseAvailable(for: .macOSAppStore)
}
```
1. Run the application and add a breakpoint inside the `getLatestReleaseAvailable` function
2. Check the `metadata` object is correctly parsed
3. The metadata should be the same as the JSON here: https://staticcdn.duckduckgo.com/macos-desktop-browser/release_metadata.json
Low: Minor visual changes, …

macOS: Add code to check for latest AppStore version

---

.github/workflows/macos_upload_version_metadata.yml
fastlane/README.md
macOS/fastlane/Fastfile

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204006570077678/task/1211383429781102?focus=true
CC:
The previous workflow was fetching the version and build numbers from the xcconfig files; the problem is that those numbers pointed to the current internal release. These new changes uses the https://docs.fastlane.tools/actions/app_store_build_number/ fastlane action to get the latest version from the App Store.
- Check that https://github.com/duckduckgo/apple-browsers/actions/runs/17799694385/job/50595871839 works as expected in this branch.
- https://staticcdn.duckduckgo.com/macos-desktop-browser/release_metadata.json should have the correct version.
---
[Definition …

macOS: Fix upload metadata workflow to get the correct version and build numbers

---

macOS/DuckDuckGo/Statistics/GeneralPixel.swift
macOS/DuckDuckGo/Statistics/PixelKit+Assertion.swift
macOS/PixelDefinitions/pixels/debug_assertion_failure.json5

Task/Issue URL: https://app.asana.com/1/137249556945/project/1201037661562251/task/1211368892557106?focus=true
CC:
We use the `pixelAssertionFailure(_:file:line:)` global function to send an assertion_failure pixel. The issue arises when firing the pixel with `PixelKit.fire(DebugEvent(GeneralPixel.assertionFailure(message: message(), file: file, line: line)))`. In this case, the convenient initializer for DebugEvent sets the event type to custom, which prevents the assertion failure parameters from being sent.
This has been fixed by using the designated initializer for DebugEvent and explicitly passing the event type
1. In AppDelegate -> `applicationDidFinishLaunching` line 1013. add call `pixelAssertionFailure(“Test Fix”)`
2. Ensure parameters are printed in the console …

[macOS] Fix assertion failure pixel call

---

iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1210988181212493?focus=true
Show voice modal from new addressbar
1. Enable voice search under Settings -> Accessibility 
2. Enable the new address bar under Settings -> AI Features
3. Select the address bar, and on both search and duck.ai mode, tap the mic button
4. The voice feedback view should appear, dismissing it should take you back to the focused mode
5. Submitting a query should dismiss the focused mode and go to either search or duck.ai
Not performing the voice-search correctly

Show voice modal from new addressbar

---

.maestro/shared/add_login_from_settings.yaml
.maestro/shared/remove_local_logins.yaml
.maestro/shared/sync_verify_logins.yaml
.maestro/shared/sync_verify_unified_favorites.yaml
iOS/DuckDuckGo/AutofillEditableCell.swift
iOS/DuckDuckGo/AutofillEditableMaskedCell.swift
iOS/DuckDuckGo/AutofillLoginDetailsView.swift
iOS/DuckDuckGo/CreditCardManagement/CreditCardDetails/AutofillCreditCardDetailsView.swift
iOS/LocalPackages/SyncUI-iOS/Sources/SyncUI-iOS/Views/SyncSettingsViewExtension.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/414235014887631/task/1211379898690459?focus=true
UI tests randomly started failing due to tap areas not working / changing. I've updated the UI tests to tap the right places. This involved moving some accessibility IDs to more precise view.
https://github.com/duckduckgo/apple-browsers/actions/runs/17858612529
---

Fix tap areas for sync and autofill maestro tests

---

macOS/DuckDuckGo/Common/View/AppKit/LoadingProgressView.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1203108348835387/task/1211406158148089?focus=true
The site loading progress bar sometimes goes away while a request is still ongoing, creating the wrong impression the site has fully loaded, and leaving the UI in a weird state.
There's a video in [this task](https://app.asana.com/1/137249556945/project/1203108348835387/task/1211406158148089?focus=true) showcasing the issue.
You can use the same steps to reproduce the original issue in `main`.  The progress bar sometimes goes away before an error is shown making it look like the site has finished loading.
1. Load any site.
2. Set Network Link Conditioner to 100% loss
3. Try loading another site, make sure the progress bar is always visible at least until an error page is shown …

Ensure progress bar is always shown while navigation is ongoing

---

macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/VPNUpsellNew/VPNPopoverPresenter.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1207340338530322/task/1211437903660692?focus=true
CC:
Although I was unable to repro the exact crash, I found that the code was calling `NSViewController.loadView()` directly, which caused the crash. From the [docs](https://developer.apple.com/documentation/appkit/nsviewcontroller/loadview()):
> Do not call this method. If you require this method to be called, access the [view](https://developer.apple.com/documentation/appkit/nsviewcontroller/view) property.
So I did just that.
1. Open macOS app
2. Reset upsell state via Debug > VPN > Upsell > Reset Upsell State and relaunch
3. Show toolbar upsell button via Debug > VPN > Show Upsell Button, and verify that the layout is still correct.
Low: removes a low …

Avoid `loadView` for creating popover view

---

SharedPackages/URLPredictor/Package.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211450429415883?focus=true
This change updates URLPredictor to use the Rust library compiled as static library. This will slightly
reduce the size of the resulting bundle and speed up app launch, by only compiling required symbols
into the main DuckDuckGo binary.
Verify that CI is green
Verify that the DMG produced by [this workflow run](https://github.com/duckduckgo/apple-browsers/actions/runs/17984135975) runs fine.
---

Update URLPredictor to use a static library

---

iOS/DuckDuckGo/AIChat/NewAddressBarPicker/NewAddressBarPickerContentView.swift
iOS/DuckDuckGo/MainViewController.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1204167627774280/task/1211457477666070?focus=true
Fix iOS 26 iPad force-choice screen
1. Open the force choice screen on iPad 26. 
2. Check if no text is cropped and it looks like the screenshot on asana
Issues in the UI like cropping text

Fix iOS 26 iPad force-choice screen

---

scripts/smartling/pr_comment_parser.sh
scripts/smartling/smartling_upload.sh

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1211443495906924
CC: @ayoy 
This PR adds the following change:
When creating a translation job, it will add the date to the job name as suffix. The change needed to enable creating a new translation job from the same branch (i.e when we encounter [this](https://app.asana.com/0/0/1210223145394340)). I also updated the comment lookup logic to take the latest job id, instead of the first one 
1. Add label `start ios translation`
2. Verify that the created job has today’s date as suffix
N/A
N/A
N/A
N/A
— …

Smartling automation: append date to job name

---

iOS/DuckDuckGo/OnboardingExperiment/VideoPlayer/VideoPlayerCoordinator.swift
iOS/DuckDuckGoTests/VideoPlayer/VideoPlayerCoordinatorTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1206329551987282/task/1211300957879410?focus=true
CC:
This PR attempt to fix crashes when the AudioSession is created or set active by delaying its creation until the video gets loaded. This happens when we’re about to show PiP to the user.
**Scenario 1 - “Onboarding"**
1. Open Debug Menu.
2. Select ‘Onboarding’.
3. Tap ‘Preview Onboarding Intro’ button.
4. Progress linear onboarding till ‘Protections Activated!’ screen.
5. Tap ‘Choose Your Browser’ button.
6. Ensure that the app deeplinks to the settings and PiP Video is playing.
7. Go back to the App.
8. Ensure that the PiP video is not playing anymore and the onboarding flow has progressed to:
9. ‘Add me to your Dock’ screen for iPhone.
10. 'Choose App Icon …

[iOS][PiP] Audio Session crash fix attempt

---

macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
macOS/DuckDuckGo/NavigationBar/View/FreeTrialBadgePersistor.swift
macOS/DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift
macOS/UnitTests/Menus/FreeTrialBadgePersistorTests.swift
macOS/UnitTests/Menus/MoreOptionsMenuTests.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/1210594645229050/task/1211380911418738
CC: @vkraucunas 
This PR makes sure that the “Try for Free” label is hidden after the user has opened the overflow menu 4 times.
1. Enable `privacyProFreeTrial` (Debug > Feature Flag Overrides)
2. Remove subscription (Debug > Subscription > Remove Subscription From This Device)
3. Switch to Stripe platform to force free trial eligibility (Debug > Subscription > Purchase platform > Stripe, then restart the app)
4. Upon next app launch, you should see the free trial badge next to the subscription item in the overflow menu
5. Open/close the menu 4 times -> confirm that the badge disappears on the 5th open.
Low: Minor visual changes, small bug fixes, improvement to existing …

Hide free trial promotion from overflow menu after 4 views

---

SharedPackages/BrowserServicesKit/Sources/Navigation/WKProcessTerminationReason.swift
macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
macOS/DuckDuckGo/Tab/Model/Tab.swift
macOS/DuckDuckGo/Tab/TabExtensions/TabCrashRecoveryExtension.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
macOS/UnitTests/TabBar/View/MockTabViewItemDelegate.swift

Task/Issue URL: https://app.asana.com/1/137249556945/project/72649045549333/task/1211198745312534?focus=true
Debounce macOS webkit termination pixel to deal with pixel bursts.
Also added a new crash-testing option to make the tab crash multiple times in a row.
1. Enable Feature Flag > Other > `tabCrashDebugging`
2. Open a tab.
3. Right click on the tab title, select "Crash Tab"
```
👾[Daily and Count-Skipped] m_mac_debug_webkit_did_terminate_daily ["appVersion": "1.158.0", "available_diskspace": "5.03", "available_memory": "53", "d": "WKErrorDomain", "e": "2", "os_version": "15.7.0", "pixelSource": "browser-dmg", "ud": "WKErrorDomain", "ue": "2"]
👾[Daily and Count-Fired] m_mac_debug_webkit_did_terminate ["appVersion": "1.158.0", "available_diskspace": "5.03", "available_memory": "53", "d": …
```

Debounce macOS webkit termination pixel to deal with pixel bursts
